### ISSUE TITLE
歌曲标签乱码问题

### ISSUE THREAD

**Issue by changyexing** [Moriafly/SaltPlayerSource#100]
#### 基本信息 The basic information

软件版本 Software version：2021110503
系统版本 System version：Android11

#### 反馈内容 Content of the feedback

有一些歌曲（准确的说都是mp3格式）会出现音乐标签是乱码的问题

![Screenshot_20211117-132659](https://user-images.githubusercontent.com/47708150/142140509-2e10863b-2513-4d93-984c-07a0a3cf483c.png)

![Screenshot_20211117-132703](https://user-images.githubusercontent.com/47708150/142140553-1907f163-e2c3-4f7a-a8e5-fc67e4278be7.png)

用“音乐标签”查看又没有问题

![Screenshot_20211117-132711](https://user-images.githubusercontent.com/47708150/142140578-b7a861bc-6236-4b2c-88a1-e37a63964544.png)

我不了解是什么问题导致的，求解答

**Comment by Moriafly** [comment]
应该是标签的编码问题，可以尝试使用音乐标签修改下编码为 UTF-8，然后进行校准。![IMG_20211117_133432.jpg](https://user-images.githubusercontent.com/62319450/142141026-df4d0d59-f9df-403d-b4a3-b4cd948ecde4.jpg)

**Comment by changyexing** [comment]
> 应该是标签的编码问题，可以尝试使用音乐标签修改下编码为 UTF-8，然后进行校准。![IMG_20211117_133432.jpg](https://user-images.githubusercontent.com/62319450/142141026-df4d0d59-f9df-403d-b4a3-b4cd948ecde4.jpg)

将编码修改为UTF-8后保存，丢失歌曲标签

![Screenshot_20211117-133903](https://user-images.githubusercontent.com/47708150/142141427-a5b1ba3f-34cd-4cde-910d-c8193cb7644e.png)

![Screenshot_20211117-133858](https://user-images.githubusercontent.com/47708150/142141438-4967ae30-4444-4fff-837b-b68b546a60a2.png)

**Comment by Moriafly** [comment]
尝试点击搜索按钮，重新网络匹配。

**Comment by changyexing** [comment]
> 尝试点击搜索按钮，重新网络匹配。

手机上重新匹配确实解决问题了。

我是在电脑上用“音乐标签”修改的，而且只有mp3格式的出错，是我哪里设置不对吗？为什么会有乱码出现呢？

**Comment by Moriafly** [comment]
暂时我也不太清楚造成这个的原因，可能默认使用了某些中文编码（GB 开头的一些），像现在也存在许多使用非 UTF-8 的歌词（举个例子）。
