### ISSUE TITLE
请求开发一个支持安卓4.3的版本

### ISSUE THREAD

**Issue by yrd3d** [Moriafly/SaltPlayerSource#1004]
我知道这个要求很过分，都2024年了嘛。但我真的很喜欢椒盐。遗憾的是我的车机系统就是安卓4.3，能用的车机播放器极少，希望我的车机也能用上椒盐音乐，功能嘛不要求很强大，只要能播放本地无损音乐、能在宽屏显示器上能同时显示歌曲自带的歌曲封面和歌词就行了（歌词能自定义大小），这两条目前我尝试过大多数车机播放软件都做不到，我就好奇怪到底为啥。

**Comment by Moriafly** [comment]
您好抱歉，我想无法完成此需求
