### ISSUE TITLE
歌曲图标错乱

### ISSUE THREAD

**Issue by fangyong125** [Moriafly/SaltPlayerSource#101]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：4.6.0-release-2021110503（此时相望不相闻）
系统版本 System version：鸿蒙2.0

#### 反馈内容 Content of the feedback

歌曲图标错乱。
播放器歌曲图标
![7279d6c8cbc986ca8ab84987742a27f](https://user-images.githubusercontent.com/34147363/142417579-7a856f79-6fff-4da8-bbbe-348c63de6572.jpg)

音乐标签歌曲图标
![cac0e5966ad3c6f890a44399538d87a](https://user-images.githubusercontent.com/34147363/142417763-ac290776-f5a9-429c-88c5-ad19657e4df3.jpg)

**Comment by Nachogao** [comment]
你试着给歌曲加专辑标签，或者是在设置中的“歌曲”—“专辑”中的“忽略媒体库封面”关掉

**Comment by Moriafly** [comment]
尝试使用其他音乐编辑软件更改添加封面图片。歌曲封面按照专辑封面显示，若歌曲专辑一致（专辑名相同且专辑艺术家相同），则会显示相同的封面。可以尝试在应用设置中开启忽略媒体库存储。
