### ISSUE TITLE
能不能加个声音淡入淡出功能，入耳耳机一下子干懵了

### ISSUE THREAD

**Issue by jzx765** [Moriafly/SaltPlayerSource#102]

**Comment by Moriafly** [comment]
4.4.0 版本后已经支持。

**Comment by jzx765** [comment]
> 4.4.0 版本后已经支持。



> 4.4.0 版本后已经支持。

抱歉，我是蓝牙耳机，刚刚特意更新到最新5.0的测试版本，点开音乐还是没有淡入淡出效果，直接就是设置的最高音，手机是小米官方稳定版系统。软件也没有找到可以设置的地方，请问是默认淡入淡出还是有设置的地方，我没有找到？

**Comment by Moriafly** [comment]
好的感谢返回，会在后续版本尝试提供设置 0 ms / 500 ms / 1000 ms 的淡入淡出的设置选项
