### ISSUE TITLE
增加 跟随系统 选项

### ISSUE THREAD

**Issue by JingwenWang-Jingle** [Moriafly/SaltPlayerSource#103]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

<感觉这个应该不算UI的建议吧🥺，希望在 深色流光 和 浅色流光 之外，能够添加一个 「跟随系统」来控制深浅流光，就像用户界面可以选择跟随系统一样，这样早、晚听歌的时候不用自己改![Screenshot_2021-11-21-08-42-34-435_com.salt.music.jpg](https://user-images.githubusercontent.com/88672087/142745051-2b351eab-c8cb-4342-acde-1dd9c3d92df4.jpg)>

**Comment by Moriafly** [comment]
在发布界面尝试更新 5.0.0-beta02 版本。
