### ISSUE TITLE
[BUG] 无法识别 DSF 格式文件的元信息

### ISSUE THREAD

**Issue by sherlcok314159** [Moriafly/SaltPlayerSource#1031]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 设备型号 Device Model

Huawei P40

### 系统版本 System Version

Android 12（鸿蒙3）

### 软件版本 App Version

10.5.2

### 描述问题 Describe issue

 当使用音乐标签软件编辑后，回到椒盐音乐，无法识别 DSF 格式文件，糟糕的是无论是歌词，还是封面，以及歌手等等信息，没有一个是可以读取出来的

很多发烧友都是用 DSF 格式，这对于大家很重要，以往也有人提出 #673 ，希望开发者能够抽空修复

最后，感谢开发者为开发该软件付出的精力

**Comment by Moriafly** [comment]
此格式已不再收到支持，详见 https://github.com/Moriafly/SaltPlayerSource/blob/main/articles%2F240902_Deprecated_DSD.md

**Comment by sherlcok314159** [comment]
那请问你使用何种方式来进行 DSF 格式转换呢？

**Comment by Moriafly** [comment]
您好，我建议放弃这些 DSD 数字音源，重新找无损 FLAC 格式，如果需要转换可以使用 FFmpeg
