### ISSUE TITLE
桌面歌词控制器的颜色

### ISSUE THREAD

**Issue by Nachogao** [Moriafly/SaltPlayerSource#104]
#### 基本信息 The basic information

软件版本 Software version：5.0.0-beta02
系统版本 System version：MiUi 12.5.1（Android 11）

#### 反馈内容 Content of the feedback

在桌面歌词的控制器中，选择颜色的“白色”选项在暗黑模式下会变成黑色而难以看到。

**Comment by Nachogao** [comment]
这是个很小的错误，此前的版本似乎就在了

**Comment by Moriafly** [comment]
修复 7.1.0-release
