### ISSUE TITLE
希望增加音乐无缝播放功能 Hope to add seamless music playback functionality.

### ISSUE THREAD

**Issue by DEVILISALIE** [Moriafly/SaltPlayerSource#1050]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 描述 Describe

希望增加音乐无缝播放功能
Hope to add seamless music playback functionality.

**Comment by Moriafly** [comment]
#183

**Comment by DEVILISALIE** [comment]
不准备做无缝播放吗
