### ISSUE TITLE
Sunshine 导致 SPW 亚克力和云母样式无效

### ISSUE THREAD

**Issue by Qhzy1411** [Moriafly/SaltPlayerSource#1053]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 设备型号 Device Model

机械革命翼龙15pro

### 系统版本 System Version

Windows 11 23H2 (10.0 amd64) Build 22631

### 软件版本 App Version

1.0.766演示版

### 描述问题 Describe issue

![PixPin_2024-11-29_16-33-52](https://github.com/user-attachments/assets/4dbed075-fb23-4401-a1a6-f59ae0812e03)
上图为浅色+椒盐经典，整体UI无异样
![PixPin_2024-11-29_16-33-40](https://github.com/user-attachments/assets/642aa911-0190-40aa-9036-7e1507892f09)
![PixPin_2024-11-29_16-33-47](https://github.com/user-attachments/assets/b5d18d83-9fb6-4ac8-a259-37b9cc6b082a)
上图为浅色+云母/亚克力，可以看到大UI仍是深色，侧边栏字体根本看不清

**Comment by Moriafly** [comment]
您好，模式改为【深色】，云母亚克力效果正常吗

**Comment by Qhzy1411** [comment]
> 您好，模式改为【深色】，云母亚克力效果正常吗

深色是正常的

**Comment by Qhzy1411** [comment]
![PixPin_2024-11-29_17-57-53](https://github.com/user-attachments/assets/a56fcc04-dadb-4102-839e-a10e45f0248b)
![PixPin_2024-11-29_17-57-58](https://github.com/user-attachments/assets/5089a6d0-9d39-40a5-b439-ee1c87c6b902)
![PixPin_2024-11-29_17-58-03](https://github.com/user-attachments/assets/54fa8a24-d0de-4cb3-b018-af31e59f2690)
好像也不正常，只不过是深色模式下纯黑背景好像没什么违和感，所以一眼没察觉不对（）

**Comment by Moriafly** [comment]
应该是样式应用失败，我也在 23H2 上测试过但未发现异常，可能和其他因素有关

**Comment by Moriafly** [comment]
请问 CPU 和 GPU 型号是？

**Comment by Qhzy1411** [comment]
> 应该是样式应用失败，我也在 23H2 上测试过但未发现异常，可能和其他因素有关

经测试，应该与sunshine有关，后台关闭sunshine后云母/亚克力样式均正常，测试了几个sunshine版本好像都有这个问题，从v2024.823.131748到目前的最新版

**Comment by Moriafly** [comment]
> > 应该是样式应用失败，我也在 23H2 上测试过但未发现异常，可能和其他因素有关
> 
> 经测试，应该与sunshine有关，后台关闭sunshine后云母/亚克力样式均正常，测试了几个sunshine版本好像都有这个问题，从v2024.823.131748到目前的最新版
> 

可以提供下对应软件安装包吗？

**Comment by Qhzy1411** [comment]
> > > 应该是样式应用失败，我也在 23H2 上测试过但未发现异常，可能和其他因素有关
> > 
> > 
> > 经测试，应该与sunshine有关，后台关闭sunshine后云母/亚克力样式均正常，测试了几个sunshine版本好像都有这个问题，从v2024.823.131748到目前的最新版
> 
> 可以提供下对应软件安装包吗？

[sunshine-windows-installer.zip](https://github.com/user-attachments/files/17959064/sunshine-windows-installer.zip)

**Comment by Moriafly** [comment]
我测试了下还真是，运行了 Sunshine 后就不正常了，我得调查下原因

**Comment by Moriafly** [comment]
785 版本添加了 DXGI 兼容模式，可以暂时避免此问题

**Comment by Qhzy1411** [comment]
> 785 版本添加了 DXGI 兼容模式，可以暂时避免此问题

👌🏻
