### ISSUE TITLE
【稳定复现】快速双击一次“上\下一曲”按钮导致无法播放

### ISSUE THREAD

**Issue by univers629** [Moriafly/SaltPlayerSource#1056]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 设备型号 Device Model

11400H  RTX3060Laptop

### 系统版本 System Version

Windows 10 专业版 22H2 19045.5198

### 软件版本 App Version

Salt Player for Windows 1.0.766

### 描述问题 Describe issue

只需要快速双击“上\下一曲”按钮一次，触发成功会直接跳到第三首歌，并且时间显示为00:-1
![屏幕截图 2024-11-29 233415](https://github.com/user-attachments/assets/fde06d89-172a-4783-9e5a-0aa6251b7a78)
![屏幕截图 2024-11-29 233415(1)](https://github.com/user-attachments/assets/fcef39c1-d6da-411b-83eb-f1bb6f0ee2db)
进入该状态后播放器无法再播放音乐

**Comment by univers629** [comment]
PS：当第二首歌时长只有两三分钟时有概率不触发跳转到第三首歌（或者是点慢了）

**Comment by Moriafly** [comment]
1.0.830 应该完成了修复
