### ISSUE TITLE
小红车和windows的音控无法获取和控制音频信息

### ISSUE THREAD

**Issue by ALBDF** [Moriafly/SaltPlayerSource#1059]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 设备型号 Device Model

Windows 10 (10.0 amd64) 22H2

### 系统版本 System Version

Windows 10 (10.0 amd64) 22H2

### 软件版本 App Version

版本 1.0.766 演示版本

### 描述问题 Describe issue

猜测是系统媒体传输控件 （SMTC）不支持的问题，如下图是酷狗播放同一音乐文件的截图：
![image](https://github.com/user-attachments/assets/f5f82a1c-9fb2-4862-8b87-7d139c5ed37e)
![image](https://github.com/user-attachments/assets/cf65fd02-f901-4215-99e9-7c32109c11e0)
使用本软件则为下图红框所示：
![bug5](https://github.com/user-attachments/assets/3641d221-d15e-4e15-b6fe-d5b29e03906c)

**Comment by Moriafly** [comment]
1.0.905 完成
