### ISSUE TITLE
希望可以增加独占全屏/无边框全屏窗口

### ISSUE THREAD

**Issue by user2046** [Moriafly/SaltPlayerSource#1061]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 描述 Describe

![123](https://github.com/user-attachments/assets/f22aa3f4-8c4d-460d-989f-c81f096c9bd8)
希望可以增加类似QQ音乐的全屏功能，spw全屏后还剩个任务栏在屏幕2，看起来不太舒服

**Comment by user2046** [comment]
标题可能因为在想别的问题导致打错字，应该是“独占全屏/全屏无边框窗口”，

**Comment by Moriafly** [comment]
1.0.830 添加了全屏模式
