### ISSUE TITLE
歌词反复时无法识别同行多个时间戳

### ISSUE THREAD

**Issue by abcdesteve** [Moriafly/SaltPlayerSource#1064]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 设备型号 Device Model

HUAWEI matepad air 11.5

### 系统版本 System Version

HarmonyOS 4.2.0.220/Android12

### 软件版本 App Version

10.6.0.1 2024111702 Moriafly

### 描述问题 Describe issue

例如
```
[00:00]歌词
[00:21][01:10][02:14][03:04][03:20]反复部分
[00:24][01:14][02:18][03:08][03:24]反复部分
[00:37]歌词
```
椒盐音乐完全无法识别这类歌词

**Comment by Moriafly** [comment]
此歌词不符合时间戳识别规范，需要添加毫秒，如 [03:45.12]
