### ISSUE TITLE
平板界面下，按钮颜色 未按下和按下颜色 bug

### ISSUE THREAD

**Issue by MURChen** [Moriafly/SaltPlayerSource#108]
来自三星Oneui 3.1 安卓版本11 tab s6平板
软件版本 5.0.0-beta04-2021112201
按钮未按下时出现按下颜色（变暗），左侧菜单也会出现，频率高，消失的时间无规律
但不确定其他设备是否会出现该情况

![SmartSelect_20211123-145528_Salt Player](https://user-images.githubusercontent.com/47627266/142982715-b7be4612-6feb-40b8-876b-3f5af6f0efdf.jpg)

**Comment by MURChen** [comment]
似乎只用触摸是没事的
但使用三星spen时，悬停在页面上方会出现这个bug
可能其他系统的平板用笔是也会出现这种情况
![Screenshot_20211123-150748_Salt Player](https://user-images.githubusercontent.com/47627266/142983143-e2c87edc-3c28-4bf3-a785-48d3e66e652d.png)
![Screenshot_20211123-150739_Salt Player](https://user-images.githubusercontent.com/47627266/142983158-6c83f013-0a55-40b5-90b9-5c7f5679c970.png)

**Comment by Moriafly** [comment]
感谢反馈，此应该是安卓 Jetpack Compose 库的问题，后续会持续关注谷歌团队的更新。

**Comment by MURChen** [comment]
在最新版中问题已修复
