### ISSUE TITLE
关于SPW演示版本在详情页的艺术家过多自动分行导致遮挡专辑封面的问题

### ISSUE THREAD

**Issue by limengansaski** [Moriafly/SaltPlayerSource#1080]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 设备型号 Device Model

raphael

### 系统版本 System Version

Windows 11 专业版 22h2 22621.3007

### 软件版本 App Version

SPW演示版本 1.0.830

### 描述问题 Describe issue

如图
![5ae10ad9ea22cd75aa1ae05e7546617a](https://github.com/user-attachments/assets/b8be1ba0-2756-4fb4-95f9-a56d0b0f2a6d)

**Comment by Moriafly** [comment]
1.0.862 修复
