### ISSUE TITLE
播放界面展开关闭动画打断偶尔无法快速触发

### ISSUE THREAD

**Issue by LingVT** [Moriafly/SaltPlayerSource#1083]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 描述 Describe

希望SPW支持动画打断，就比如“歌词界面”到主页之间的切换

**Comment by Moriafly** [comment]
我不是很理解具体是？

**Comment by LingVT** [comment]
> 我不是很理解具体是？

就比如重复点一个按键，希望能在动画结束前响应，而不是傻愣着等动画结束

**Comment by Moriafly** [comment]
在软件中无法复现此情况，如果可以提供某部分的视频会更好

**Comment by LingVT** [comment]
> 在软件中无法复现此情况，如果可以提供某部分的视频会更好

您可以尝试重复点击进入到歌词界面，您应该就能感受到了

**Comment by univers629** [comment]
https://github.com/Moriafly/SaltPlayerSource/issues/1083#issuecomment-2525398259
猜你想看：
https://github.com/user-attachments/assets/fe9fbb45-ad3c-46d5-9361-624ffb03d235

**Comment by univers629** [comment]
> > 在软件中无法复现此情况，如果可以提供某部分的视频会更好
> 
> 您可以尝试重复点击进入到歌词界面，您应该就能感受到了

猜你想看：

https://github.com/user-attachments/assets/96d5efcb-8a3e-4a4a-85a3-e21b4e2f755b

**Comment by univers629** [comment]
> 我不是很理解具体是？

意思是当点进歌词播放页时，正好反悔想回到主页点击某个选项，但是此时必须等待播放界面完全展开，才能再次点击封面缩略图返回主页，不能临时打断动画放弃进入播放页

**Comment by Moriafly** [comment]
目前可能偶尔点击不连贯，会尽快优化

**Comment by Moriafly** [comment]
1.0.862 修复
