### ISSUE TITLE
鼠标双击打开SPW时有时可以同时打开两个界面（可复现）

### ISSUE THREAD

**Issue by 27stark** [Moriafly/SaltPlayerSource#1085]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 设备型号 Device Model

Jiaolong5 Series GM5BGEE

### 系统版本 System Version

版本：Windows 11 专业工作站版   版本号：23H2

### 软件版本 App Version

版本：1.0.830 演示版本

### 描述问题 Describe issue

鼠标双击打开SPW时有时可以同时打开两个界面（可复现）
![SPW问题1](https://github.com/user-attachments/assets/1498c5ed-c7df-4299-8857-a6678c600a15)

**Comment by Moriafly** [comment]
已更改逻辑，1.0.862
