### ISSUE TITLE
深色模式下音频输入信息置顶页面时文字显示问题（稳定复现）

### ISSUE THREAD

**Issue by 27stark** [Moriafly/SaltPlayerSource#1086]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 设备型号 Device Model

Jiaolong5 Series GM5BGEE

### 系统版本 System Version

版本：Windows 11 专业工作站版   版本号：23H2

### 软件版本 App Version

版本：1.0.830 演示版本

### 描述问题 Describe issue

在深色模式下，当音频输入信息窗口置顶时，首行文字以及关闭按钮会无法显示，当光标移动到关闭按钮或者点击桌面使音频输入信息窗口失去焦点时，文字信息及关闭按钮会重新显现（稳定复现）
![Snipaste_2024-12-07_23-12-34](https://github.com/user-attachments/assets/5f5863e5-2347-46d8-bed7-a4fe2f13db40)
![Snipaste_2024-12-07_23-12-28](https://github.com/user-attachments/assets/1c694c3f-a517-4747-84b3-273257e9f1df)

**Comment by Moriafly** [comment]
感谢反馈，此问题和 #1054 重复
