### ISSUE TITLE
播放界面能够查看输出设备等的更详细信息

### ISSUE THREAD

**Issue by LineCatOvO** [Moriafly/SaltPlayerSource#1089]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 描述 Describe

>  首先，这个可能是我个人问题。

在调整椒盐音乐的音频输出时，调整页面内可调的只有api和频率。在插入dac的情况下，我试过了opensl，audiotrack和aaudio这三个，配合频率192khz和强制更改采样率开关为开，但是最终似乎都没有绕开安卓的系统接口，我从两个方面判断：  
  1. 主观听上去没区别，使用的是24bit，176400hz的alac音源，分别输出192khz和44.1khz。*当然这个完全可以说是我木耳的原因*
  2. 从poweramp equalizer内的输出信息看，无论哪种情况，信号处理的采样率都是显示48khz，不过有一点是椒盐输出192khz时，eq的波形可视化只有从左边开始2/3区域有效，右边的1/3罢工了

所以我觉得可能椒盐根本没接进我连接的dac，但是我又无从查证。所以就想来询问一下。因为知识不足造成的困扰，实在是抱歉。
至于别的软件的测试，有两个，网易云独占罢工，完全用不了，可能是手机的问题；poweramp是没有问题的，hires变量为 direct hd，任务栏也有hires标了（

**Comment by Moriafly** [comment]
1. 对于 176.4 kHz 的频率文件，设置为 44.1 kHz 会是一个比较好的选择。
2. 音频输出配置和 OEM 厂商的音频策略有关，如在音频策略中添加了一些特殊的选择，如 Hi-Res 标志（属于 OEM 自定义）。
3. 只要手机 -> DAC -> 耳机，您能听到声音，则表示 DAC 一定是在工作的（当您连接 DAC，安卓系统通知栏会提示“正在通过 USB 设备输出音频”）。

**Comment by Moriafly** [comment]
如果未出现【当您连接 DAC，安卓系统通知栏会提示“正在通过 USB 设备输出音频”】表示 DC 转换可能发生手机内部而非 DAC 设备。

**Comment by LineCatOvO** [comment]
好快的回复！但是您真的说对了，通知栏什么都没有，除了耳机图标和椒盐panel。。。
总之十分感谢您！我会再自己尝试的。
