### ISSUE TITLE
SPW播放界面缩略图不清晰，压缩率过高·

### ISSUE THREAD

**Issue by limengansaski** [Moriafly/SaltPlayerSource#1092]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 设备型号 Device Model

raphael

### 系统版本 System Version

Windows 11 专业版 22h2 22621.3007

### 软件版本 App Version

SPW演示版本 1.0.862

### 描述问题 Describe issue

图片不清晰
![いのち 2024 ver  - AZKi](https://github.com/user-attachments/assets/33379515-b99b-42a0-b508-deb30aca97e7)
![屏幕截图 2024-12-10 211624](https://github.com/user-attachments/assets/08b3dc01-2e76-4a09-9dcf-cb4860897605)
![屏幕截图 2024-12-10 213838](https://github.com/user-attachments/assets/992b944e-48f6-44ab-a8be-10bdd0578035)

**Comment by Moriafly** [comment]
已修复
