### ISSUE TITLE
Some Advice&Bug

### ISSUE THREAD

**Issue by Blooming298K** [Moriafly/SaltPlayerSource#11]
Bug:
1.桌面图标全白显示；
2.音乐通知栏有些许错位；
3.跳转到历史界面无法呼出播放界面；
4.切换播放器主题时候几率性无法切换；

Advice:
1.建议更换应用图标（原稿可参考酷安@Eirperuier）
2.播放设备切换界面可以以按钮形式突出当前播放设备 MD2）
3.进度条调整可在调整时显出白点，方便调整
4.自建歌单和收藏功能

**Comment by Blooming298K** [comment]
1.基于Color OS11.1 RMX1901反馈；
2.图标问题已解决，取消该建议。

**Comment by Moriafly** [comment]
好的收到~谢谢🥰

**Comment by Moriafly** [comment]
已分 issue #12 #13 #14 #15 #16 ，部分关闭

**Comment by Blooming298K** [comment]
希望该应用能够成为像 清浊、flomo一样的国内中小型开发者开发的优秀APP榜样。
特别是现在离线播放器虽然使用人数不多，且多为国外开发者开发多，希望椒盐能够更多人发现吧。

**Comment by Moriafly** [comment]
谢谢支持！道阻且长，会继续努力的~
