### ISSUE TITLE
在QQ音乐下载的歌曲没有封面

### ISSUE THREAD

**Issue by 112211ss** [Moriafly/SaltPlayerSource#1100]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 设备型号 Device Model

iqoo neo5

### 系统版本 System Version

基于安卓14的origin os4

### 软件版本 App Version

10.6.0.1

### 描述问题 Describe issue

在QQ音乐下载的歌曲没有封面

**Comment by Moriafly** [comment]
您好可能是您获取的音频文件本身没有内嵌在文件中的封面，如果是软件识别的问题可以发送样本文件。

流媒体软件可能对本地音乐进行了网络方面匹配，但是封面并没有写入文件中。

您可以使用一些第三方音频编辑软件，如音乐标签等对封面进行自定义编辑。
