### ISSUE TITLE
在α02中会有概率闪退

### ISSUE THREAD

**Issue by AlierKitten** [Moriafly/SaltPlayerSource#1101]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 设备型号 Device Model

Xiaomi 14

### 系统版本 System Version

OS2.0.7.0

### 软件版本 App Version

10.7.0-α02

### 描述问题 Describe issue

salt player好像没有日志功能，在我测试下似乎只有播放那一首歌时会导致闪退
但这首歌旧版本或其他播放器不会导致闪退
我觉可能是歌曲标题编码格式的问题

![image](https://github.com/user-attachments/assets/f1cc44a2-896e-4d7f-ad21-b9d855b5ae33)

![IMG_20241216_105951](https://github.com/user-attachments/assets/835eabd6-72c0-4355-8029-a1c827ff25b0)

![gt_20241216_24682_v_gif](https://github.com/user-attachments/assets/3d6d533e-5a5a-4820-9833-2e557a37041c)

**Comment by Moriafly** [comment]
可以提供下那首歌的文件吗？前面发布了 10.7.0-alpha03 也会崩溃吗？

**Comment by AlierKitten** [comment]
> 可以提供下那首歌的文件吗？前面发布了 10.7.0-alpha03 也会崩溃吗？

03不会闪退了
歌曲文件：
`https://www.123865.com/s/jywDVv-eBIvd`
