### ISSUE TITLE
深色主题应用问题

### ISSUE THREAD

**Issue by tigerJX95** [Moriafly/SaltPlayerSource#1103]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 设备型号 Device Model

huawei pura70

### 系统版本 System Version

Harmony OS 4.2

### 软件版本 App Version

10.7.0-alpha03

### 描述问题 Describe issue

app主题颜色设置为深色时，只有最左侧的选项卡页（有歌曲、专辑、艺术家、文件夹等等）和点开这些选项页面应用了深色。但是，具体到某首歌曲的详情页、音频信息页和歌词页浏览，则还是默认的浅色

**Comment by Moriafly** [comment]
您好，软件【设置】->【用户界面】->【播放界面】选项可以将颜色设置为浅色、深色、跟随用户界面

默认为浅色，属于一个 V7 版本历史遗留
