### ISSUE TITLE
Lyrics UI 3 逐字LRC的翻译歌词末尾的[时间戳]以及翻译歌词前后的<时间戳>识别错误

### ISSUE THREAD

**Issue by kvetc** [Moriafly/SaltPlayerSource#1108]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 设备型号 Device Model

Xiaomi 14

### 系统版本 System Version

HyperOS 2.0 Android15

### 软件版本 App Version

10.7.0-alpha3 2024121602

### 描述问题 Describe issue

逐字LRC的翻译歌词末尾的[时间戳]以及翻译歌词前后的<时间戳>识别错误。此问题在多个平台上测试均存在。
Salt Player Lyrics UI 3在使用逐字LRC时，若翻译歌词的末尾也存在[]形式时间戳，Salt Player会将此时间戳识别为翻译歌词。
即当翻译歌词为“[XX.XX.XXX]翻译歌词[XX.XX.XXX]”时，Salt Player会将后面一个[XX.XX.XXX]识别为翻译歌词的内容。
同样的，当翻译歌词为“[XX.XX.XXX]<XX.XX.XXX>翻译歌词<XX.XX.XXX>”时，Salt Player会将前后两个<XX.XX.XXX>识别为翻译歌词的内容。
这种翻译歌词的时间戳形式符合ESLyric和增强型LRC的标准格式，在其他支持ESLyric和增强型LRC的播放器上均能正常识别，希望椒盐也能正常识别。
[截图.zip](https://github.com/user-attachments/files/18153955/default.zip)

**Comment by Moriafly** [comment]
10.7.0-beta01 修复，若依旧出现此问题请重新打开 issue
https://github.com/Moriafly/SaltPlayerSource/releases/tag/10.7.0-beta01
