### ISSUE TITLE
Lyrics UI 3 逐字LRC两个逐字时间戳之间无内容或者为“ ”（空格）时，歌词被截断不显示

### ISSUE THREAD

**Issue by kvetc** [Moriafly/SaltPlayerSource#1109]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 设备型号 Device Model

Xiaomi 14

### 系统版本 System Version

HyperOS 2.0 Android15

### 软件版本 App Version

10.7.0-alpha3 2024121602

### 描述问题 Describe issue

Lyrics UI 3 逐字LRC两个逐字时间戳之间无内容或者为“ ”（空格）时，歌词被截断不显示。
举例：在显示逐字歌词“[00:17.499]<00:17.499>あ<00:17.626>と<00:17.837><00:17.838>一<00:18.484><00:18.485>匙<00:19.224>の<00:19.458>”时，因为“あと”后的两个<时间戳>之间为空（或空格），该句歌词在Salt Player中就只显示“あと”，该句歌词内后续的部分都被截断不显示。
无论使用[ ]还是< >形式的时间戳都存在这个问题，两个时间戳之间为空时必然触发，两个时间戳之间为“空格”时似乎有概率触发。
PS：经测试，此问题与两个时间戳时间间隔过短无关，因为即使两个时间戳时间间隔较长，其中间为空时，仍然会触发此问题。
此问题在多个设备上测试都存在。
这个歌词符合增强型LRC的标准格式，在其他支持增强型LRC的播放器上均能正常识别，希望椒盐也能正常识别。
[截图2.zip](https://github.com/user-attachments/files/18154177/2.zip)

**Comment by Moriafly** [comment]
10.7.0-beta01 修复，若依旧出现此问题请重新打开 issue
https://github.com/Moriafly/SaltPlayerSource/releases/tag/10.7.0-beta01
