### ISSUE TITLE
更新后启动闪退

### ISSUE THREAD

**Issue by Toskysun** [Moriafly/SaltPlayerSource#1111]
### 在反馈此问题前请注意 Please note before reporting this issue

- [X] 已经查看相关帮助内容 Read more about the Salt Player help content
- [X] 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)

### 设备型号 Device Model

Xiaomi 13 Ultra

### 系统版本 System Version

Android15,HyperOS2.0.0.18beta

### 软件版本 App Version

10.7.0-alpha04-2024121603

### 描述问题 Describe issue

更新10.7.0 alpha4后启动闪退，崩溃日志如下
[crash-com-salt-music-17_12-17-38-57_725.zip](https://github.com/user-attachments/files/18163433/crash-com-salt-music-17_12-17-38-57_725.zip)

**Comment by Moriafly** [comment]
10.7.0-beta01 修复，若依旧出现此问题请重新打开 issue
https://github.com/Moriafly/SaltPlayerSource/releases/tag/10.7.0-beta01
