### ISSUE TITLE
修改Hi-Res音乐识别逻辑

### ISSUE THREAD

**Issue by WarnError** [Moriafly/SaltPlayerSource#116]
建议为所有24bit音乐标记，而不是粗略的根据是否大于1600 Kbps来判断Hi-Res音频

**Comment by WarnError** [comment]
flac ape等等格式都能无损的压缩比特率，直接靠比特率大小判断音频的质量显得有失偏颇

**Comment by WarnError** [comment]
flac ape等等格式都能无损的压缩比特率，直接靠比特率大小判断音频的质量显得有失偏颇

**Comment by Moriafly** [comment]
是的，我也比较头疼，精确的判断会严重影响列表性能。
最精确方法应该仅仅在播放界面显示，但是列表就会没有小标。

**Comment by Moriafly** [comment]
7.0 内测版本已经支持 wav 格式正确判断，其他还需要时间

**Comment by shikkoku** [comment]
遇到了一些有关本问题的情况，我这个专辑下全部音乐都是24bit/48Khz的，只有个别曲目给了小金标（均为flac无损）。
![6323239707634413851_121](https://user-images.githubusercontent.com/4697177/184520490-2823ac77-d7dd-4276-85e6-6dca0b2c4acc.jpg)


另外列表中的小金标图标出现被压扁显示失真的情况。
![6323239707634413852_121](https://user-images.githubusercontent.com/4697177/184520511-5eb9ef99-483b-45f1-9e39-60e888c76e06.jpg)


是否能统一显示为原有的HQ标记或者多加一个HR的缩略字符标记？（这首歌曲是24/96，不知道为什么椒盐音乐读不出tag。而且只有这一首标记为HQ）
![6323239707634413853_121](https://user-images.githubusercontent.com/4697177/184520520-488b30f5-332b-40ec-bae4-5afea9aa6101.jpg)

**Comment by Moriafly** [comment]
先以 24 bits / 44.1 kHz 为最低标准，适用于 FLAC / WAV 格式。
