### ISSUE TITLE
读取云盘（WebDAV / OneDrive 等）、自建流媒体服务器等歌曲

### ISSUE THREAD

**Issue by opcck** [Moriafly/SaltPlayerSource#117]
就比如我把音乐存在了onedrive，可以直接连接云端听歌，像谷歌相册备份照片那样

**Comment by UTAKO-TAKI** [comment]
强烈建议，有了这个功能我这种懒狗就可以当做主力使用了。(๑>؂<๑）

**Comment by dengjunjian23** [comment]
我也有类似需求，不过我更需要的是支持局域网共享（SMB）

**Comment by KYatoo** [comment]
同求。希望可以提供常见协议（webdav/smb/ftp等）支持。可以在文件夹中添加网络地址。

**Comment by onlyJinx** [comment]
+1，希望支持播放局域网文件，因为无损音乐我都是放在nas上的

**Comment by Roufoye** [comment]
附议~~~

**Comment by wubenefit** [comment]
附议V●ᴥ●V

**Comment by TensorABC** [comment]
附议( ･⊝･∞)
另外可不可以修改一下播放队列的布局 
![Screenshot_20220723_102238_com vanced android apps youtube music](https://user-images.githubusercontent.com/95612401/180587032-569cfc77-030b-4997-9a19-4f16a882dba6.jpg)
学习一下youtube music的布局

**Comment by Moriafly** [comment]
关于 WebDAV 云盘支持，有计划。
说明一下，不使用这不会占用内存，对不喜欢的用户它仅是一个开关。
目前在椒盐笔记中开始实际使用 WebDAV ，做为技术积累，相信我以后有能力将 WebDAV 播放做好。还有很多的一些问题，如文件夹浏览，缓存等等，这不是一蹴而就的。
那么它不是一个当前很重要的开发目标，甚至还不在预计的 V8 计划中，有进度会在仓库的第一个 Pin 的云盘 issue 更新。

**Comment by YKYCYKYC** [comment]
附议，现在安卓几个支持网盘挂载播放的软件都是国外的，操作方式和界面等对国内用户不太友好，而且不支持内嵌歌词，大佬加油，希望未来成为国内本地音乐播放器功能最强大的。

**Comment by BenzLeung** [comment]
附议，求jellyfin和/或subsonic连接

**Comment by Howard20181** [comment]
> 同求。希望可以提供常见协议（webdav/smb/ftp等）支持。可以在文件夹中添加网络地址。

目前能找到的支持SMB的音乐播放器有很多，但是都不能显示同目录下同名的歌词文件
找到支持的是个视频播放器（nPlayer），只能作为字幕显示2行

希望椒盐音乐能实现播放SMB音乐同时能读取LRC歌词

**Comment by moke8** [comment]
附议~~~

**Comment by yzj-oss** [comment]
附议，一直在等webdav,有了这个就把其它软件全卸载了，哈哈哈

**Comment by shwhy1998** [comment]
希望能连接plex音乐库，我的无损音乐全在nas里

**Comment by Benjamin-Watson0** [comment]
参考下vlc for android?

**Comment by moke8** [comment]
nas 附议

**Comment by gldl137** [comment]
迫切需要

**Comment by bxb100** [comment]
@Moriafly 能否弄个 fs layer, 然后用插件的形式来提供对远程内容的支持, 这样也不需要公布源码, 只要公布 specification 就行了

可以参考一下 https://github.com/tachiyomiorg/tachiyomi-extensions 社区插件方式

**Comment by Nydxsst** [comment]
支持，作者加油！

**Comment by qinfengge** [comment]
webdav+1

**Comment by HMQYHM** [comment]
webdav+1

**Comment by FeiLZX3Km** [comment]
不知道能不能支持直接读取华为云盘内的音乐文件？（虽然感觉可能性不大）

**Comment by im-zhangxi** [comment]
新来的, 想问下webdav这个支持有计划弄吗?或者已经再弄?

**Comment by Joker-lm** [comment]
啥时候能有这个功能呢啊，我nas里存了好多歌

**Comment by meinaOfficial** [comment]
OneDrive云盘听歌期待中……
云盘听歌大部分都是国外的，用起来不适合咱们，希望有个适合中国人习惯的。大佬加油！

**Comment by zhougengxu1990** [comment]
已经有支持阿里云盘的了。messense/aliyundrive-webdav。

**Comment by Joker-lm** [comment]
> 已经有支持阿里云盘的了。messense/aliyundrive-webdav。

哪款软件？

**Comment by TianMiao8152** [comment]
椒盐音乐还有计划吗？还是移到云听去了

**Comment by wxyShine** [comment]
+1

**Comment by iopkl2012** [comment]
+1

**Comment by tvba365** [comment]
webdav+1

**Comment by Hwenray** [comment]
同求+1

**Comment by bcuiwikb** [comment]
+1

**Comment by orange-io** [comment]
都快2025年了，希望可以有这个功能，安卓这边就没几个支持smb的音乐播放软件

**Comment by opcck** [comment]
> 都快2025年了，希望可以有这个功能，安卓布拉格没几个支持smb的音乐播放软件

早就有了，都用一两年了

**Comment by HKMV** [comment]
> > 都快2025年了，希望可以有这个功能，安卓布拉格没几个支持smb的音乐播放软件
> 
> 早就有了，都用一两年了

来个支持Navidrome的

**Comment by SuSuSoo** [comment]
SMB+1

**Comment by jayhao004** [comment]
webdav+1

**Comment by xiyue-11** [comment]
2026了，还有希望吗
