### ISSUE TITLE
歌曲扫描不全

### ISSUE THREAD

**Issue by ttttechno** [Moriafly/SaltPlayerSource#119]
软件版本 Software version：5.0beta06
系统版本 System version：Android10

反馈内容 Content of the feedback
歌曲扫描不全，还会把歌词文件也扫描进来，播放不了的。
![S11126-16453971](https://user-images.githubusercontent.com/64273467/143553139-7e286677-b2fc-41c8-9536-e76b5b16927e.png)
一共有十四首只扫描出了10首，俩个歌词文件。
![S11126-16455175](https://user-images.githubusercontent.com/64273467/143553159-d28ab685-2d2f-412c-a5e1-9429270b1030.png)
poweramp能扫描出来
![S11126-16462364](https://user-images.githubusercontent.com/64273467/143553376-70257b33-a5bc-4110-96f3-58923a8cbd60.png)
文件夹📁

**Comment by Moriafly** [comment]
抱歉漏回复了 https://moriafly.xyz/HiMoriafly/salt-player/help.html#%E6%89%AB%E6%8F%8F%E6%AD%8C%E6%9B%B2%E4%B8%8D%E5%85%A8
