### ISSUE TITLE
歌曲信息问题

### ISSUE THREAD

**Issue by tjXG** [Moriafly/SaltPlayerSource#124]
![Screenshot_2021-12-04-21-09-04-917_com salt music](https://user-images.githubusercontent.com/90078071/144710835-620ed5e2-6f9c-419c-849b-3b8d9a1e0f02.jpg)
版本：V3.9.1
已经将信息内嵌在歌曲里面，但有许多歌曲都会这样显示成其他的信息，如图

**Comment by Moriafly** [comment]
是从外部打开吗？

**Comment by Soulballad** [comment]
歌曲信息无法编辑手动修改不了，出现乱码和unknown

**Comment by Moriafly** [comment]
外部打开不支持信息显示
