### ISSUE TITLE
沉浸模式下按钮可能容易烧屏

### ISSUE THREAD

**Issue by tongxin0520** [Moriafly/SaltPlayerSource#131]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

<在此输入你的建议 Enter your suggestions here>

无论是普通模式还是沉浸模式“上一曲”“播放/暂停”“下一曲”按钮均无法隐藏，OLED屏幕长时间停留在此页面时可能出现烧屏现象，能否增加“沉浸模式下一定时间后隐藏按钮”。

**Comment by Moriafly** [comment]
谢谢建议，不过此不会变更

**Comment by dengjunjian23** [comment]
这应该无法从根本解决，因为就算按钮不显示了，专辑图片同样会导致烧屏
