### ISSUE TITLE
后台播放逻辑

### ISSUE THREAD

**Issue by DDYYLLL** [Moriafly/SaltPlayerSource#134]
一加7pro Oxygen11.0.4.1

软件版本 Software version：5.5.0
系统版本 System version：Android11

反馈内容 Content of the feedback
划掉后台后无法播放。软件设置为智能控制，后台划掉后实际仍在运行（见下图）
![Screenshot_20211225-202041.jpg](https://user-images.githubusercontent.com/47361807/147384751-fd7316b8-f9ac-472d-9b47-f90c7173f9df.jpg)

**Comment by Moriafly** [comment]
此受厂商系统控制
