### ISSUE TITLE
建议添加一个“流畅模式”

### ISSUE THREAD

**Issue by Duck-Deng** [Moriafly/SaltPlayerSource#137]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

<椒盐的界面设计用了大量模糊、渐变等效果，虽然让界面更美观，但这些效果在低配置和老设备上会造成卡顿，可以添加一个开关关闭部分视觉效果，类似于QQ音乐的流畅度设置。>
![Screenshot_2022-01-01-15-39-35-69](https://user-images.githubusercontent.com/64295725/147846255-db58ea41-32d3-4447-bb08-8bd05e6972db.png)

**Comment by Moriafly** [comment]
新版本对一些影响性能的默认关闭。
