### ISSUE TITLE
关于封面加载方案的探讨。Talk about how to well load music cover.

### ISSUE THREAD

**Issue by aecra** [Moriafly/SaltPlayerSource#139]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposal

当前版本（浔阳江头夜送客）封面采用只展示页面显示出来的歌曲的封面，当上下滑动歌曲列表时需要大量加载歌曲信息，这造成了严重的页面卡顿，这个选择是不是优化大量歌曲情况下的内存占用问题呢？我没有如何优化更好的建议，但能否可以不展示歌曲封面呢？

The cover of the current version (浔阳江头夜送客) uses only the cover of the song displayed on the page. When the song list is swiped up and down, a large amount of song information needs to be loaded, which causes serious page freezes. Is this choice to optimize memory usage? I don’t have any suggestions on how to optimize, but can I not show the cover of the song?

**Comment by Moriafly** [comment]
你好，当前版本使用了 Compose 1.1.0-rc01 和 Coli-Compose 的 AsyncImage，实现了延迟图片加载，不过目前 Compose 的列表性能存在很大的问题，会在后续版本跟随谷歌的优化。
