### ISSUE TITLE
暂停后播放无音量

### ISSUE THREAD

**Issue by subframe7536** [Moriafly/SaltPlayerSource#145]
#### 基本信息 The basic information

软件版本 Software version：移船相近邀相见 2022020401
系统版本 System version：Android12，miui13

#### 反馈内容 Content of the feedback

1. 关闭音量淡入淡出，暂停后点击播放无音量
2. 打开音量淡入淡出，播放后点击暂停有音量减弱的效果，但播放时还是无音量
3. 点击播放后没有音量恢复？还是miui的锅？

**Comment by Moriafly** [comment]
已在 5.12.2 版本修复，可以在酷安更新此版本。
