### ISSUE TITLE
非mp3的音乐格式不识别

### ISSUE THREAD

**Issue by 0302-Darren** [Moriafly/SaltPlayerSource#146]
我本地有m4a和ape格式的音乐 在app内的音乐库中扫描时均不识别

**Comment by Moriafly** [comment]
1. 需要给椒盐音乐读取外部存储权限（确保，椒盐音乐会在首次启动时候请求此权限，请同意；若拒绝可以重新启动应用或者在系统应用设置中重新授予此权限）。

2. **椒盐音乐会读取系统媒体库（com.android.providers.media），若你的一些歌曲文件路径位于无法被扫描的文件夹下（以 . 开头的隐藏文件夹、包含 .nomedia 文件的文件夹、其他应用的私有目录），那么无法出现在椒盐音乐的歌曲列表中。建议移动音频文件到 Music 文件夹下或者你自建的文件夹（注意此文件夹不得以 . 开头，父目录和自身目录下不含 .nomedia 文件）。**

3. **不被你手机内置的解码支持的格式（包含安卓提供的媒体解码和手机厂商提供的解码，请在椒盐音乐【设置】-【音频输出】-【此设备提供的媒体解码】查看具体支持的格式，如部分手机不支持扫描 APE、DSD 格式音频文件）**将不会出现在列表中（虽然椒盐音乐可能支持此音频格式解码播放）。当然你可以用些格式转换工具转换音频格式使得让系统支持扫描此音乐。

4. 椒盐音乐不支持扫描 .wma 文件，尝试更换其他音频格式。

5. 一些流媒体应用（如某 Q、某云等），其 VIP 收费歌曲格式可能加密，系统媒体库无法扫描且椒盐音乐无法播放（自带此解码可能会有某些风险），尝试更换其他被支持的音频格式。

6. **若以上方法未解决你的问题（确保正确尝试），那么可能是你的系统媒体库未重新扫描文件，如新下载的歌曲无法被扫描出来。可以尝试重新启动手机（注意不是软重启）；或下载椒盐音乐推荐的媒体重新扫描应用：https://foyou.lanzoui.com/inR3iuarmaj ，此软件会对全文件进行扫描来刷新系统媒体库。**

**Comment by 0302-Darren** [comment]
使用推荐的app重新扫描后m4a可以了，但是ape格式始终扫不到
系统自带的音乐可以扫描并播放m4a ape格式音乐

**Comment by pth2000** [comment]
> 1. 需要给椒盐音乐读取外部存储权限（确保，椒盐音乐会在首次启动时候请求此权限，请同意；若拒绝可以重新启动应用或者在系统应用设置中重新授予此权限）。
> 2. **椒盐音乐会读取系统媒体库（com.android.providers.media），若你的一些歌曲文件路径位于无法被扫描的文件夹下（以 . 开头的隐藏文件夹、包含 .nomedia 文件的文件夹、其他应用的私有目录），那么无法出现在椒盐音乐的歌曲列表中。建议移动音频文件到 Music 文件夹下或者你自建的文件夹（注意此文件夹不得以 . 开头，父目录和自身目录下不含 .nomedia 文件）。**
> 3. **不被你手机内置的解码支持的格式（包含安卓提供的媒体解码和手机厂商提供的解码，请在椒盐音乐【设置】-【音频输出】-【此设备提供的媒体解码】查看具体支持的格式，如部分手机不支持扫描 APE、DSD 格式音频文件）**将不会出现在列表中（虽然椒盐音乐可能支持此音频格式解码播放）。当然你可以用些格式转换工具转换音频格式使得让系统支持扫描此音乐。
> 4. 椒盐音乐不支持扫描 .wma 文件，尝试更换其他音频格式。
> 5. 一些流媒体应用（如某 Q、某云等），其 VIP 收费歌曲格式可能加密，系统媒体库无法扫描且椒盐音乐无法播放（自带此解码可能会有某些风险），尝试更换其他被支持的音频格式。
> 6. **若以上方法未解决你的问题（确保正确尝试），那么可能是你的系统媒体库未重新扫描文件，如新下载的歌曲无法被扫描出来。可以尝试重新启动手机（注意不是软重启）；或下载椒盐音乐推荐的媒体重新扫描应用：https://foyou.lanzoui.com/inR3iuarmaj ，此软件会对全文件进行扫描来刷新系统媒体库。**

遇到一个小问题，如果音乐名称以“.”开头，也会出现扫描不到的问题。这个应该也是系统媒体库的问题吧
（找到这一首没被扫描到的音乐还挺辛苦的）
