### ISSUE TITLE
流光效果卡住不动

### ISSUE THREAD

**Issue by Limbaud** [Moriafly/SaltPlayerSource#152]
### 基本信息 The basic information

> 软件版本 Software version：5.14.0
    系统版本 System version：ONEUI 4.0 (Android 12)

### 反馈内容 Content of the feedback

播放界面流光效果无效，切入歌曲大约三秒左右，图像会迅速转为一副固定色块（如图），经过多次实验，固定色块的分布有所不同。这个问题似乎持续了几个版本。
![图1尚在变化](https://user-images.githubusercontent.com/62022072/154942342-7bd474ca-fc77-43e0-a5f8-02b59cb26593.jpg)
![图2已固定](https://user-images.githubusercontent.com/62022072/154942348-76d94a82-b198-4cd7-9526-835d3527cd26.jpg)
![图3已固定](https://user-images.githubusercontent.com/62022072/154942355-74d2bbf1-e767-4421-a6ab-342b0cb7f786.jpg)

**Comment by Moriafly** [comment]
问题移动至 #159
