### ISSUE TITLE
封面显示有问题

### ISSUE THREAD

**Issue by meinvtuzai** [Moriafly/SaltPlayerSource#155]
椒盐音乐版本：5.14
机型：小米10
系统版本：MIUI13
Android版本：12
我把放到手机的音乐封面都内嵌到歌曲中了，结果椒盐有的显示不了内嵌封面，有专辑的可以显示正常的封面，没有专辑的结果都显示的是一个封面（比如我放的文件件名称music，并且封面是随机的，每次打开不一样），而不是我的内嵌封面。建议优先显示内嵌封面，其次是歌曲所在目录下的同名图片文件，最后是网络搜索，这样比较合理一些。详细见下图
![image](https://user-images.githubusercontent.com/95647691/155872268-df62b169-518c-4144-9c95-a5b33703ff3e.png)

**Comment by Moriafly** [comment]
尝试使用音乐标签编辑歌曲文件【专辑】标签。

**Comment by meinvtuzai** [comment]
编辑专辑标签可以，就是随便填写一个名称就行，关键问题是能批量改专辑名吗？就和歌曲名称一样就行，我有几百首都要修改，一个一个改到猴年马月了，汗汗！再就是软件能自动识别不？不要识别专辑名称，专辑封面优先内嵌的能否做到？如果可以按我的建议，专辑封面的识别顺序是：内嵌封面>歌曲同文件夹下的同名图片文件>网络下载就更好了。

**Comment by Moriafly** [comment]
音乐标签有多选自动匹配选定的信息，会很方便。
