### ISSUE TITLE
西语字母显示问题

### ISSUE THREAD

**Issue by Archwu5** [Moriafly/SaltPlayerSource#156]
如图，特殊的西语字母显示有问题，希望可以解决一下。

另外请问可不可以增加一个删除本地音乐文件的功能？每次要从文件管理里搜索然后删除有点麻烦。
![Screenshot_20220301_015513_com huawei filemanager](https://user-images.githubusercontent.com/98156948/156034885-6562d056-f61f-4123-8573-2a3dd278bde6.jpg)
![Screenshot_20220301_020509_com salt music](https://user-images.githubusercontent.com/98156948/156034892-0dd5dd60-f18b-4c3b-8f45-0d3c3444f7ce.jpg)

**Comment by Moriafly** [comment]
你好，椒盐音乐通过系统媒体库获取内嵌信息，而不仅仅是文件名，可以通过音乐标签软件修改 **标题** 标签，注意需要修复编码为 UTF-8 。
