### ISSUE TITLE
应用安装失败

### ISSUE THREAD

**Issue by Henrylin666** [Moriafly/SaltPlayerSource#157]
#### 基本信息 The basic information

软件版本 Software version：（各版本均出现此问题）
系统版本 System version：Android 11

#### 反馈内容 Content of the feedback

直接打开APK安装，提示“应用未安装”；使用ADB调试安装，报错： 
`INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113`

我不是安卓相关的开发者，不太了解问题的原因，我只是想在新买的MP4上安装椒盐音乐，然后就遇到了这样的错误，望予以解决

**Comment by Moriafly** [comment]
你好，椒盐音乐仅支持 arm-v8a 架构（64 位），可能你的设备是 32 位的。
