### ISSUE TITLE
希望加入回放增益（Replay Gain）功能

### ISSUE THREAD

**Issue by BenzLeung** [Moriafly/SaltPlayerSource#158]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

<在此输入你的建议 Enter your suggestions here>

回放增益（Replay Gain）是记录在ID3的tag里面的一组数值，单位是dB。

维基：https://zh.wikipedia.org/zh-hans/%E5%9B%9E%E6%94%BE%E5%A2%9E%E7%9B%8A

百毒百科：https://baike.baidu.com/item/%E5%9B%9E%E6%94%BE%E5%A2%9E%E7%9B%8A/1799477

回放增益数值表示这首歌曲播放时，如果对音量增加或减少，那么可以让音乐库里面所有歌曲的音量达到平衡，不会这歌音量大那歌音量小。

由于录音技术的不同，经典老歌的整体音量一般比潮流新曲要小，现场live歌曲的音量比正统歌曲也要小。如果播放列表混着新歌老歌live歌，切歌时音量就会时大时小。回放增益可以实现只修改ID3不改变波形数据来解决这个问题，前提是播放器要支持。

我知道的其他支持回放增益的音乐软件：Foobar2000. Poweramp, Auxio

我相信著名的音乐开发库例如ffmpeg都应该直接提供ReplayGain接口或入参吧。所以我猜这需求不难？

**Comment by Moriafly** [comment]
好主意，后续会关注此。

**Comment by BenzLeung** [comment]
我找到了一篇技术文章，详细介绍了回放增益的算法。

https://wiki.hydrogenaud.io/index.php?title=ReplayGain_1.0_specification#Player_requirements

实现**计算**增益数值的算法很复杂难懂，但是网络上已经有不少软件或app帮助实现了。例如 Foobar2000 就有扫描增益值的功能，扫描出来的增益值会写入歌曲文件的元数据（ID3v2 或 APEv2）。

但是，如果只是**应用**增益数值，并内部调整歌曲的音量，那算法还挺简单的。

我帮你们把算法总结一下：

1. 从歌曲文件元数据（ID3v2 或 APEv2）中读取 ReplayGain 的值，这个值的 key 为 `REPLAYGAIN_TRACK_GAIN` 或 `REPLAYGAIN_ALBUM_GAIN`，值的格式为字符串 `"-x.xx dB"`，例如 `"-8.90 dB"`，把单位 `dB` 和中间的空格去掉转换成数字（一般为负数）。
2. 用这个公式计算出一个音量调整比例常数：`10 ^ (ReplayGain / 20)` ，10 的 (ReplayGain / 20) 次方。例如上一步读取的值为 -8.90 ，那么 `-8.90 / 20 = -0.445` ，然后 10 的 -0.445 次方等于 `0.35892`。
3. 把歌曲的音量调整到比例常数，例如上一步 `-8.90` 计算出的常数 `0.35890`，就把音量调整到 35.89% 。

也许你觉得 35.89% 的音量值偏小了，所以那篇技术文章还介绍了『前置放大器』（Pre-amp），可以增加这个选项，让所有增益值都加上前置放大器值。例如用户设置前置放大值为 `+6 dB`，如果元数据的增益值为 `-8.90 dB`，那么就按照 -8.90+6 即 `-2.90 dB` 计算音量调整比例。`-2.90 dB` 计算出来的音量是 71.614% 。

如果大佬们实现了这个功能，我们作为用户就可以先用 Foobar2000 预先对 mp3 或 flac 文件做回放增益值批量扫描、写入元数据，然后用椒盐音乐app欣赏到音量很平衡的音乐。

PS. Foobar2000 的PC版和Android版都有回放增益批量扫描的功能。

目前本issue还是『待讨论』，坐等大佬们继续讨论完善啊~。

**Comment by Moriafly** [comment]
非常感谢提供方法，似乎可行！我会在近期进行对其标签读取的测试。实现步骤：

1. 对标签读取（会测试 Tag18 / Jaudiotagger / Taglib 库）

2. 对最大音量的调整

我会在这里更新进度

**Comment by BenzLeung** [comment]
by the way 其实我看那篇技术文，有一个不严谨的地方。[捂脸] [捂脸] [捂脸] 

用公式计算出 ReplayGain 数值后，原文说的不是直接把它当成音量值，而是让音频的『each sample value』乘以这个 ReplayGain 。其中 sample 我理解应该是 sample rate 的 sample，就是采样率的采样，我们知道一般mp3或flac采样率是44100Hz或48000Hz。『each sample value』就是把音频的每个采样值乘以那个增益值，得到一段新的音频数据，然后播放这段音频就是音量平衡的。

每个采样值乘以增益值，我理解就是相当于把增益值当成音量调整比率的。只是，这毕竟是我自己的理解，不一定正确。如果你们能实现处理『每个采样值乘以增益值』而不是『直接调整音量』，估计会更准确。

**Comment by Moriafly** [comment]
功能已经完成开发，将在后续版本推出

**Comment by BenzLeung** [comment]
哇~

**Comment by Moriafly** [comment]
7.10.0-beta01-2022100401

**Comment by BenzLeung** [comment]
哇哇哇~🥳😍
