### ISSUE TITLE
流光效果更新问题

### ISSUE THREAD

**Issue by minewhn** [Moriafly/SaltPlayerSource#159]
https://user-images.githubusercontent.com/91197879/157037712-7d4680bd-3a9c-44b7-a6ec-f6018a156bb2.mp4

音乐播放时切换流光效果（暗/亮色模式）只会改变字体颜色（黑/白）而不改变流光，切换歌曲（应该重新加载流光）后恢复

**Comment by Moriafly** [comment]
更新 7.2.0
