### ISSUE TITLE
天天好闲啊，一直更新什么垃圾功能，真是小心眼一个偷偷tg群禁止我，我换号了

### ISSUE THREAD

**Issue by dianso** [Moriafly/SaltPlayerSource#160]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：<软件版本 Software version>
系统版本 System version：<系统版本 System version>

#### 反馈内容 Content of the feedback

<在此输入你遇到的问题，必填 Enter the problem you encountered here. Required>

**Comment by Moriafly** [comment]
远离低素质人，谢谢反馈，我闲着无聊。
给个 star 不，亲~

**Comment by Moriafly** [comment]
补一句，我怕你这样阴暗的人，马上去搜索 dianso 踢你。
希望你以后不要恶心我，对了我送你个椒盐音乐 Pro ~ 记得查收哦

**Comment by dianso** [comment]
nonono，你已经踢了我了去才发的i速

**Comment by dianso** [comment]
我早开启了Pro，懒得理你这个小心眼的逼。
事情起因就是我说了四个字：天天更新。
然后一堆水军发了几百条私信黑我

**Comment by dianso** [comment]
祝福你妈健在

**Comment by Moriafly** [comment]
我又做了什么？谢谢你这样高素质人~

**Comment by panda-mute** [comment]
这种人值得踢

**Comment by Moriafly** [comment]
> 补一句，我怕你这样阴暗的人，马上去搜索 dianso 踢你。
> 希望你以后不要恶心我，对了我送你个椒盐音乐 Pro ~ 记得查收哦

注：10 点我就去 tg 踢了它，意思是“补一句，（正因为）我怕你这样阴暗的人，（所以）马上去搜索 dianso 踢你。”来回复这位 dianso 发的 issue 的标题内容。
