### ISSUE TITLE
希望可以支持调用安卓的播放设备切换，不只是MIUI的

### ISSUE THREAD

**Issue by JonyWinner** [Moriafly/SaltPlayerSource#166]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

<在此输入你的建议 Enter your suggestions here>
在类原生点击图一按钮无用，希望支持调用安卓的播放
![Screenshot_20220313-125136_椒盐音乐~2](https://user-images.githubusercontent.com/63949560/158045744-78dd5a46-caec-40d7-b09d-85e08b75121e.png)
![Screenshot_20220313-125223_椒盐音乐](https://user-images.githubusercontent.com/63949560/158045748-73fddef5-b442-4ada-97b2-4bfbe8b5a151.png)
设备切换

**Comment by JonyWinner** [comment]
com.android.systemui.media.dialog.MediaOutputDialog
Activity好像是这个

**Comment by Moriafly** [comment]
迁移 #179
