### ISSUE TITLE
建议支持逐字显示lyrics的格式

### ISSUE THREAD

**Issue by runoutlee** [Moriafly/SaltPlayerSource#167]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals
我从各大音乐网站上下载的滚动歌词，很多格式是这样的：

爱[00:30.84]到[00:31.15]心[00:31.71]破[00:32.02]碎[00:32.65]

这种格式目前salt不支持，在歌词界面会直接原样显示出来

谢谢。

**Comment by nnkn** [comment]
顶一下，我也遇到这个问题，上来发现楼主已经发了
歌有点多，一个个改歌词恐怕要疯，不需要效果，显示正常就可以
![Screenshot_2022-05-25-18-06-08-17_e53b20ddbf74fed](https://user-images.githubusercontent.com/22342244/170240982-0184c805-94a8-4384-bc4a-e2b1aeee21b3.jpg)

**Comment by Moriafly** [comment]
#764
