### ISSUE TITLE
上面两个小区域的触控有问题

### ISSUE THREAD

**Issue by CONAN-ZDD** [Moriafly/SaltPlayerSource#17]
https://user-images.githubusercontent.com/50905610/128343822-f694463a-79a3-4699-9428-1b4c397525c2.mp4

右侧靠中间点一下是播放暂停，右侧点击是打开和关闭播放列表

**Comment by Moriafly** [comment]
收到~❤️

**Comment by Moriafly** [comment]
开发完成，将于 3.4.0 发布解决
