### ISSUE TITLE
专辑年份信息识别错误/未正确识别

### ISSUE THREAD

**Issue by Xionghaizi001** [Moriafly/SaltPlayerSource#173]
#### 基本信息 The basic information

软件版本 Software version：7.0.0-store-beta01(2022032802)
系统版本 System version：Android 11 / Flyme 9.2.4.2A / MEIZU 18 Pro

#### 反馈内容 Content of the feedback

部分专辑的**年份**标签不能被正确识别，对比多个文件，即使音乐文件中的年份tag存在有效字段，也仅有个别文件被正确识别。如果是安卓媒体库问题，请告知并关闭此issue，如果是app识别问题，请排查改进，谢谢。

*“年份”指专辑详情页中三个数值(歌曲、时长、年份)中第三个*

**Comment by Moriafly** [comment]
尝试使用音乐版权查看是否成功写入了媒体库属性。在音乐标签歌曲编辑界面，点击右上角的三点菜单，在弹出的菜单中选择【属性（媒体库）】，弹出的对话框中查看【年份】属性是否写入成功，若不成功则可能是音乐标签或者是系统原因，也可能是音频格式问题。椒盐音乐对于年份识别基于系统媒体库。
