### ISSUE TITLE
增加文件夹层次结构

### ISSUE THREAD

**Issue by Kotlin537** [Moriafly/SaltPlayerSource#18]
现在是）那样几个分类，但是因为文件夹比较多，实际翻找的时候很麻烦Ծ‸Ծ，能否增加一个「文件夹层次结构」的分类呀），谢谢作者大大，软件很精美！
来自酷友昨晚睡得不好

**Comment by FX9590** [comment]
我有很多同人音声，为了统一目录结构以及为差分音频分类，所以每个作品里面的音频文件均放在一个固定名字的目录下。然后再分类，比如no BGM之类的。
目前的文件夹视图对我来说不友好，满屏幕的目录都是同一个名字。
