### ISSUE TITLE
第三方软件无法获取播放器音乐信息

### ISSUE THREAD

**Issue by MisaLiu** [Moriafly/SaltPlayerSource#191]
#### 基本信息 The basic information

软件版本 Software version：7.0.0-beta1
系统版本 System version：MIUI 12 20.4.27 (Android 9)

#### 反馈内容 Content of the feedback

类似 KWGT 这样的第三方软件无法获取应用的音乐信息，导致在播放音乐时，KWGT 会显示上一个播放器所提供的音乐信息。

**Comment by Moriafly** [comment]
已经支持 KWGT
