### ISSUE TITLE
m4a文件能打开但扫不出来

### ISSUE THREAD

**Issue by SZCDSB** [Moriafly/SaltPlayerSource#196]
- 尽量详细的描述问题。    m4a文件能打开但是扫不出来，在酷安看到可能是三星手机特有的问题

- 提供出现此问题的椒盐音乐版本号。    7.0.0- store - beta01

- 建议提供机型、系统版本。    三星note20ultra   oneui4.0 
 Android12

**Comment by Moriafly** [comment]
你好，是否有以下情况 https://moriafly.xyz/HiMoriafly/salt-player/help.html#%E6%89%AB%E6%8F%8F%E6%AD%8C%E6%9B%B2%E4%B8%8D%E5%85%A8 ？

**Comment by SZCDSB** [comment]
我的m4a文件是下载的B站视频的音轨，不知道是不是视频文件的问题，但后缀改成mp3就能识别了，下面的图片是我手机支持的解码器
![Uploading Screenshot_20220408-212208_Salt Player.jpg…]()

**Comment by SZCDSB** [comment]
我的m4a文件是下载的B站视频的音轨，不知道是不是视频文件的问题，但后缀改成mp3就能识别了，下面的图片是我手机支持的解码器
![Uploading Screenshot_20220408-212208_Salt Player.jpg…]()

**Comment by Moriafly** [comment]
解决就就好 ~
