### ISSUE TITLE
部分机型播放第二首歌无声，进入应用恢复

### ISSUE THREAD

**Issue by EasonGYC** [Moriafly/SaltPlayerSource#20]
手机是mi10pro miui12.5 21.7.21 最新3.3.1beta会出现第一首歌播完第二首歌无声现象 点击状态栏按钮没用 必须得进app才能控制

**Comment by Moriafly** [comment]
这个问题目前仅仅在 K40 和 小米 10 系列出现（统计自 3.2.0 版本），因为淡入淡出造成的（应该是），因为我手头没有这些机器无法准确的定位这个问题的原因。一直在检查代码，希望在 3.3.1 版本内解决，后续会发出更多测试版。

**Comment by EasonGYC** [comment]
佬，有没有tg群啊😶------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月6日(星期五) 中午12:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Moriafly/SaltPlayerSource] 3.3.1beta无声 (#20)

**Comment by Moriafly** [comment]
https://t.me/saltplayer

**Comment by Moriafly** [comment]
> 佬，有没有tg群啊😶------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年8月6日(星期五) 中午12:09 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Moriafly/SaltPlayerSource] 3.3.1beta无声 (#20)

最新测试版已经发布，若有时间可否试试~~~

**Comment by EasonGYC** [comment]
我去试一试------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月6日(星期五) 下午2:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Moriafly/SaltPlayerSource] 部分机型播放第二首歌无声，进入应用恢复 (#20)

**Comment by EasonGYC** [comment]
最新的版本我装了 还是一样的问题😂
干脆就不要淡入淡出了😂

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月6日(周五) 下午2:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Moriafly/SaltPlayerSource] 部分机型播放第二首歌无声，进入应用恢复 (#20)




  
佬，有没有tg群啊😶------------------&nbsp;原始邮件&nbsp;------------------ @.&gt; 发送时间:&nbsp;2021年8月6日(星期五) 中午12:09 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Moriafly/SaltPlayerSource] 3.3.1beta无声 (#20)
  
最新测试版已经发布，若有时间可否试试~~~
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Moriafly** [comment]
好的我还是砍了吧😂

**Comment by Moriafly** [comment]
开发完成，将于 3.4.0 发布解决
