### ISSUE TITLE
播放背景自定义图片增加模糊处理或不透明度设置

### ISSUE THREAD

**Issue by achieve-dream1221** [Moriafly/SaltPlayerSource#203]
![Screenshot_2022-04-12-22-40-09-63_e53b20ddbf74fed48fbb876ec4945b7f.jpg](https://user-images.githubusercontent.com/57209087/162989774-094eb357-135b-42fb-85c5-c2a4fc4420ae.jpg)

使用自定义图片，发现播放ui，包括歌词，不够明显，如果可以，希望增加标题中的功能。
不行的话，那就不行吧，毕竟不是大问题，大不了不用自定义了♥(｡￫v￩｡)♥

**Comment by Moriafly** [comment]
你好，推荐使用系统图库对图片进行透明度处理。
