### ISSUE TITLE
建议抛弃安卓的垃圾媒体库

### ISSUE THREAD

**Issue by Xionghaizi001** [Moriafly/SaltPlayerSource#204]
#### 建议内容 The proposals

安卓媒体库对音乐文件标签的识别很垃圾这个现象也不是一天两天了，WAV文件也识别不了，建议参考海贝音乐app，直接从文件中读取标签然后加载到app里，它也是安卓端少见的能正确读取wav文件的app~~貌似还有kodi~~。这个功能对流畅度的影响微乎其微~~如果实在介意可以加动画拖时间😂~~，对于2020年以后的安卓平台来说不算什么大性能开销的任务。如果不影响开发进度，希望能将这个建议加入考虑，谢谢！

**Comment by Moriafly** [comment]
虽说人们对于媒体库颇有微词，但不至于垃圾，不过在不同设备上的体验不一致确实不好。WAV 属于特殊情况，我个人完全不建议使用此音频格式作为移动端收集音乐的方式。目前来说此任务是无法完成的，不仅仅是技术上，还有现有的软件架构问题。

问题迁移 #195
