### ISSUE TITLE
专辑页面排序错误

### ISSUE THREAD

**Issue by Racemize** [Moriafly/SaltPlayerSource#211]
#### 基本信息 The basic information

软件版本 Software version：< Google商店版 5.19.0>
系统版本 System version：<红米K20 pro  MIUI 12.5>

#### 反馈内容 Content of the feedback

<您好，在软件使用过程发现如果按专辑查看则会出现专辑顺序与字母顺序不符排序混乱的情况，如果按歌曲查看并以专辑为排序条件则专辑顺序能够与字母顺序匹配，请问是否是因为按专辑查看时有比专辑名称更高优先级的排序条件，如果有希望能够增加以字母顺序为最高优先级的排序方式>

**Comment by Moriafly** [comment]
此问题应该在 7.0.3 得到解决。
