### ISSUE TITLE
专辑分类错误

### ISSUE THREAD

**Issue by Devocy** [Moriafly/SaltPlayerSource#214]
#### 基本信息 The basic information

软件版本 ：7.0.0-rc02(2022042101)
系统版本 ：Android 11 
手机型号 ：一加 7 Pro

#### 反馈内容 Content of the feedback

![image](https://user-images.githubusercontent.com/16794969/164592016-2a03acdc-4dc2-498b-bdf8-acd60b2d1978.png)
![image](https://user-images.githubusercontent.com/16794969/164592130-67bc3704-c8e9-48c9-9e69-bbed42a12159.png)

同一张专辑下的歌曲，被分成多张专辑显示

**Comment by Moriafly** [comment]
需要使用 音乐标签 软件正确编辑 【专辑艺术家】标签，未编辑 【专辑艺术家】标签将无法正确分类。
