### ISSUE TITLE
歌曲与名字和专辑封面不匹配

### ISSUE THREAD

**Issue by hanshuang40** [Moriafly/SaltPlayerSource#215]
软件版本 Software version：<5.20.0(2022032401)>
系统版本 System version：<Android8.1>

<我加入了20首歌曲，只给我显示了11首，而且大多数歌曲名字和歌曲不匹配，专辑封面也乱>

**Comment by Moriafly** [comment]
音乐信息可以通过 音乐标签 软件编辑
