### ISSUE TITLE
删除/移动 椒盐音乐仍然保留不存在的mp3

### ISSUE THREAD

**Issue by HOMEMILY** [Moriafly/SaltPlayerSource#216]
#### 基本信息 The basic information
椒盐音乐版本号：7.0.0-rc02
机型：redmi K30pro 系统版本：MIUI13.0.2
#### 反馈内容 Content of the feedback
用手机文件管理删除或移动mp3，椒盐音乐仍有已删除或已移动的mp3，选中播放显示“无法找到此文件，可能文件已被移动或删除。
未删除的mp3和删除的mp3混杂在一起，体验下降

**Comment by Moriafly** [comment]
使用此软件进行重新扫描系统媒体库 https://foyou.lanzoui.com/inR3iuarmaj

**Comment by HOMEMILY** [comment]
> 使用此软件进行重新扫描系统媒体库 https://foyou.lanzoui.com/inR3iuarmaj

感谢解答，已解决
