### ISSUE TITLE
更新状态栏歌词的仓库网址

### ISSUE THREAD

**Issue by xyl23333** [Moriafly/SaltPlayerSource#219]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

<在此输入你的建议 Enter your suggestions here>

目前，设置中的状态栏歌词仓库已经更换位置。建议更换成[新的地址](https://github.com/Block-Network/StatusBarLyric)

![Screenshot_20220426-185802.png](https://user-images.githubusercontent.com/46397979/165285793-0d889e10-e4d1-4bec-8b9b-302fb69894d2.png)

**Comment by Moriafly** [comment]
更新
