### ISSUE TITLE
不显示HQ图标 

### ISSUE THREAD

**Issue by Kotlin537** [Moriafly/SaltPlayerSource#22]
音乐比特率已达到192kbps，却没显示HQ图标 
酷安@机不可失Pro

**Comment by Kotlin537** [comment]
![Uploading 6962d8985df04c2d919251bdef25d271.jpg…]()

**Comment by Kotlin537** [comment]
见图

**Comment by Kotlin537** [comment]
![Uploading 43437e5ffc5253ad709b56d2588da38a.
![a31c32cd3accbc5a222e6f2111a7b03b](https://user-images.githubusercontent.com/78596005/128453584-8c196ca0-e00d-408d-8592-c9757de570cb.jpg)
jpg…]()

**Comment by Kotlin537** [comment]
https://www.coolapk.com/feed/28946481?shareKey=NGRlMGNiNWIwZTg3NjEwY2IxY2E~&shareUid=3368590&shareFrom=com.coolapk.market_11.3-beta1
详情

**Comment by Moriafly** [comment]
文档描述错误，会被修复~
