### ISSUE TITLE
Opus格式不识别

### ISSUE THREAD

**Issue by xtronx** [Moriafly/SaltPlayerSource#222]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：<7.0.0-rc06(2022042802)>
系统版本 System version：<类原生 8.1.0>

#### 反馈内容 Content of the feedback
好像无法扫描出Opus文件呢......以及MPEG这种视频格式当作音频被扫出来了= =
确认过解码器是支持Opus的

**Comment by Moriafly** [comment]
需要给椒盐音乐读取外部存储权限（确保，可以在系统应用设置查看是否授予此权限）。

椒盐音乐会读取系统媒体库（com.android.providers.media），若你的一些歌曲文件路径位于无法被扫描的文件夹下（以 . 开头的隐藏文件夹、包含 .nomedia 文件的文件夹、其他应用的私有目录），那么无法出现在椒盐音乐的歌曲列表中。建议移动音频文件到 Music 文件夹下或者你自建的文件夹（注意此文件夹不得以 . 开头，父目录和自身目录下不含 .nomedia 文件）；

不被你手机内置的解码支持的格式（包含安卓提供的媒体解码和手机厂商提供的解码，请在椒盐音乐【设置】-【音频输出】-【此设备提供的媒体解码】查看具体支持的格式，如部分手机不支持扫描 APE、DSD 格式音频文件）将不会出现在列表中（虽然椒盐音乐可能支持此音频格式解码播放）。当然你可以用些格式转换工具转换音频格式使得让系统支持扫描此音乐。

特别说明一些流媒体应用（如某 Q、某云等），其 VIP 收费歌曲格式可能加密，系统媒体库无法扫描且椒盐音乐无法播放（自带此解码可能会有某些风险）。

若以上方法未解决你的问题（确保正确尝试），那么可能是你的系统媒体库未重新扫描文件，可以尝试重新启动手机（注意不是软重启），或者下载椒盐音乐推荐的媒体重新扫描应用：https://foyou.lanzoui.com/inR3iuarmaj ，此软件会对全文件进行扫描来刷新系统媒体库。
