### ISSUE TITLE
播放歌曲时打开桌面歌词仅显示text_view

### ISSUE THREAD

**Issue by RobotAtri** [Moriafly/SaltPlayerSource#224]
#### 基本信息 The basic information

软件版本 Software version：7.0.0-rc07(2022050101)

系统版本 System version：
设备型号：OPPO Reno4 5G
版本号：PDPM00_11_F.04
ROM 版本：ColorOS 12.1
基于 Android 12

![Screenshot_2022-05-01-16-23-27-11_e53b20ddbf74fed48fbb876ec4945b7f](https://user-images.githubusercontent.com/96921596/166138037-e0761b77-2dac-4c32-a386-9fc1f2928fa5.jpg)
![Screenshot_2022-05-01-16-42-04-79_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/96921596/166138590-0cee3d45-d7f4-4001-ad22-be76d57b54a2.jpg)

#### 反馈内容 Content of the feedback

播放歌曲时打开桌面歌词仅显示 text_view ，有歌词的歌曲会在下一句歌词时显示正常，而纯音乐需通过切换歌曲才能恢复正常。

下面附上问题截图
![Screenshot_2022-05-01-16-25-26-75_e53b20ddbf74fed48fbb876ec4945b7f](https://user-images.githubusercontent.com/96921596/166138411-6c42a667-ea15-4bd9-ac84-0557bd933bf2.jpg)

当切换歌曲后就会恢复正常。
![Screenshot_2022-05-01-16-25-37-51_e53b20ddbf74fed48fbb876ec4945b7f](https://user-images.githubusercontent.com/96921596/166138418-2fec613a-e76b-40c9-8572-3f75996d9314.jpg)

**Comment by Moriafly** [comment]
7.0.1 修复
