### ISSUE TITLE
切换到wav格式歌曲时且标签不带图片，不会自动播放

### ISSUE THREAD

**Issue by MiuJi** [Moriafly/SaltPlayerSource#225]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：<软件版本 Software version>
系统版本 System version：<系统版本 System version>

#### 反馈内容 Content of the feedback

<在此输入你遇到的问题，必填 Enter the problem you encountered here. Required>
软件版本: 7.0.0-rc08(2022050201)
手机型号:
![Screenshot_20220503_135405_com android settings](https://user-images.githubusercontent.com/61742627/166409945-30edb202-7791-4065-9eab-b765b6d44299.jpg)

过程:
1.wav格式歌曲标签不带图片
2.上一首播放完自动一下首或者手动点击该歌曲
![Screenshot_20220503_140534](https://user-images.githubusercontent.com/61742627/166411100-b69a3a29-7168-47a4-954c-86133d62f5c2.jpg)

结果:
![Screenshot_20220503_140621](https://user-images.githubusercontent.com/61742627/166411119-d74b36eb-a1e2-4c91-8256-aedb89ceabc1.jpg)

不会自动播放，且图片会沿用上一首歌的图片

概率:必现

**Comment by Moriafly** [comment]
可否提供下音频文件？

**Comment by Moriafly** [comment]
已经复现

**Comment by Moriafly** [comment]
此问题在 rc10 版本得到解决，若依旧存在请重新开启。
