### ISSUE TITLE
wav格式歌曲，标签无标题显示空白

### ISSUE THREAD

**Issue by MiuJi** [Moriafly/SaltPlayerSource#226]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：<软件版本 Software version>
系统版本 System version：<系统版本 System version>

#### 反馈内容 Content of the feedback

<在此输入你遇到的问题，必填 Enter the problem you encountered here. Required>
软件版本: 7.0.0-rc08(2022050201)
手机型号:
![Screenshot_20220503_135405_com android settings](https://user-images.githubusercontent.com/61742627/166426161-0bcfd264-a156-410c-9703-0694a0896768.jpg)

过程:
1.需要wav格式，且标签无标题
![Screenshot_20220503_164725_com xjcheng musictageditor](https://user-images.githubusercontent.com/61742627/166426595-f1446cee-2ebe-4859-b400-4510390f7132.jpg)

结果:
![Screenshot_20220503_165113](https://user-images.githubusercontent.com/61742627/166427242-6bfea194-a7cc-4645-9f16-3254eac38227.jpg)

区域空白显示，不会用文件名字作为标题

概率:必现

**Comment by Moriafly** [comment]
尝试更新 rc09 版本（已经发布在酷安和 tg），不过在筹备下个版本 rc10 更新，估计明天或者后天更新。

**Comment by Moriafly** [comment]
此暂时可以通过音乐标签编辑

**Comment by MiuJi** [comment]
r09 点击播放无图片的wav以后，就不能切换歌曲了，无论手动点击切换，还是播放完后。

**Comment by MiuJi** [comment]
重启软件也不行，只能清楚应用数据

**Comment by Moriafly** [comment]
更新 rc10 版本
