### ISSUE TITLE
增加歌曲列表文件名排序

### ISSUE THREAD

**Issue by LyntNy4n** [Moriafly/SaltPlayerSource#23]
现在是以标题显示的,但是有些文件的标题没有序号,听的时候就没有办法按顺序听,而且有的是乱码,就更搞不明白了

**Comment by Moriafly** [comment]
好的建议~
乱码是因为编码问题，标签等只支持 UTF-8，可以使用音乐标签进行编码修复。

**Comment by Moriafly** [comment]
有些晚，7.0.0-alpha08 已支持文件名显示

**Comment by Moriafly** [comment]
8.2.4 完成开发
