### ISSUE TITLE
设备从横屏状态切换到竖屏状态时会自动切换下一首歌曲

### ISSUE THREAD

**Issue by G-mare** [Moriafly/SaltPlayerSource#234]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：[7.0.0-release-2022051301](https://github.com/Moriafly/SaltPlayerSource/releases/tag/7.0.0)
系统版本 System version：MIUI12 20.9.4 (Android10)

#### 反馈内容 Content of the feedback

复现步骤:

1. 设备开启自动旋转，打开`椒盐音乐`并停留在软件界面
2. 旋转设备再旋转回来会发现音乐自动切到换下一首

经测试 [5.20.0-release-2022032401](https://foyou.lanzouf.com/iJh8e0324v9a) 不会出现此问题

**Comment by G-mare** [comment]
补充：
复现视频（视频中`椒盐音乐`版本为`7.0.1-release`）

https://user-images.githubusercontent.com/64208603/168964885-6a2c9d1b-327a-44bb-93d8-de4712c3b44e.mp4

模拟器上也有这个情况，不过可能需要多旋转几次

**Comment by rchdliang** [comment]
软件版本 Software version：7.0.4-gamma
系统版本 System version：MIUI12.5.1.0(QDGCNXM)  (Android10)
机型:小米MIX2S
复现视频

**Comment by rchdliang** [comment]
https://user-images.githubusercontent.com/67943933/170291755-1d16a911-4b44-4344-a055-268aaeb5e37c.mp4

**Comment by Moriafly** [comment]
尝试更新 7.0.14 版本
