### ISSUE TITLE
Android 7.0的xp框架版本3.15打开app闪退mini player envi error

### ISSUE THREAD

**Issue by jltxf** [Moriafly/SaltPlayerSource#24]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：<软件版本 Software version>
系统版本 System version：<系统版本 System version>

#### 反馈内容 Content of the feedback

<在此输入你遇到的问题，必填 Enter the problem you encountered here.

**Comment by Moriafly** [comment]
收到反馈~
