### ISSUE TITLE
播放界面信息栏不显示

### ISSUE THREAD

**Issue by MeiLaii** [Moriafly/SaltPlayerSource#240]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：<7.0.1>
系统版本 System version：<miui11,Android 9>

#### 反馈内容 Content of the feedback

<使用返回键回到桌面后,再打开椒盐,音乐播放界面的信息栏不显示.切歌后会恢复显示,但只要用返回键回到桌面就会再次出现
![Screenshot_2022-05-18-13-57-24-729_com salt music](https://user-images.githubusercontent.com/99824318/168968599-85176625-cfc7-4bbf-bf37-e657267b457a.jpg)
>

**Comment by Moriafly** [comment]
尝试更新 7.0.2 版本，若依旧出现请重新打开 issue

**Comment by MeiLaii** [comment]
> 

已更新 7.0.2 版本,尝试清除了椒盐的全部数据,问题依旧出现. 我注意到使用返回键到桌面后再打开椒盐,会有短暂的界面加载过程,然后会出现此bug,直接上划到桌面,再打开没有界面加载过程,不会出现此bug

**Comment by Moriafly** [comment]
尝试更新 7.0.8 版本

**Comment by MeiLaii** [comment]
> 尝试更新 7.0.8 版本

更新了,已修复
