### ISSUE TITLE
播放中突然卡住无声，也无法切换其他任何歌曲，重启亦无法解决

### ISSUE THREAD

**Issue by elijahchan2019** [Moriafly/SaltPlayerSource#241]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------

- 软件版本：7.0.1正式
- 系统版本：真我大探，realme 3.0，安卓12，蓝牙耳机LHDC解码

- 时间：今天数次，此前经常出现
- 触发：播放歌曲时，具体未知

具体情况：使用app播放歌曲，用蓝牙耳机听，听着听着就突然没声了，打开App，发现显示还是在播放中，但是就是无声，此时点击其他任意歌曲，都没有反应（可以点，点了也有高亮交互，但就是没有切换成功）。后台杀掉app重启，还是老样子。进设置中强制逼停app，再打开就恢复了。

**Comment by Moriafly** [comment]
尝试更新 7.0.2 版本
