### ISSUE TITLE
播放页面白屏、歌曲无法切换

### ISSUE THREAD

**Issue by elijahchan2019** [Moriafly/SaltPlayerSource#243]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

-------------------------

软件版本 Software version：7.0.1正式版
系统版本 System version：真我大探，realmeui 3.0 ，安卓12，LHDC

现象：今天第一次打开就加载了2s白屏后才进入app，点击歌单，点击随机播放，下面显示某一首歌曲，却没有开始播放，要手动点一下开始才开始放。但是感觉歌曲好像变慢了（主观感觉，不完全确定）。然后点击播放组件，页面白屏（见图），再切换歌曲，切换失败（见图）。后台杀死app，重启，依然一样。进设置强行停止app，重启，依然一样。卸载重装，按以上流程走一遍，再次复现。目前已经无法正常使用了。

怀疑与昨天我提的另一个bug有关联：https://github.com/Moriafly/SaltPlayerSource/issues/241#issue-1241472966

![201653014365_ pic](https://user-images.githubusercontent.com/51269401/169438645-00a2cf40-b118-4413-9a07-455de04f31c1.jpg)
![191653014365_ pic](https://user-images.githubusercontent.com/51269401/169438670-7e6b1c8c-31e3-40c7-893d-0c0e4760bda6.jpg)

**Comment by elijahchan2019** [comment]
追加：去下载了lite版本，按照以上流程操作，一切正常。不知道是否有可能app均衡器和系统均衡器打架导致的，希望作者大大帮忙看看

**Comment by Moriafly** [comment]
尝试更新 7.0.2 版本，已在 release 发布

**Comment by Moriafly** [comment]
若依旧出现请再次打开 isse

**Comment by elijahchan2019** [comment]
已下载7.0.2，但测试后还是一样的问题，且发现了一个新的情况，如图：
![221653103207_ pic](https://user-images.githubusercontent.com/51269401/169633567-3e8cd9b1-dfd9-4110-8bf6-bb6eb227e268.jpg)

受图启发怀疑是输出模式的问题，去切换成opensl，还是不行。。。

**Comment by Moriafly** [comment]
尝试清楚一下播放队列

**Comment by elijahchan2019** [comment]
播放队列也是一直如图白屏，进不去，所以我索性清除软件重装，也依然不行。
![231653104090_ pic](https://user-images.githubusercontent.com/51269401/169633915-436fb101-1bef-4c3d-b5ae-51c0185492bc.jpg)

**Comment by Moriafly** [comment]
在用户界面设置切换为浅色流光，然后进入播放队列界面，点击清除。

**Comment by Moriafly** [comment]
如果能提供录屏最好了

**Comment by elijahchan2019** [comment]
https://user-images.githubusercontent.com/51269401/169635270-157c9cd5-498e-47b9-8c23-fd3c2e8fad2c.mp4

**Comment by Moriafly** [comment]
似乎是专辑封面无法正确加载，手机系统有使用什么 Xposed 模块吗？【歌曲页面】的歌曲封面可以正常加载吗？

**Comment by elijahchan2019** [comment]
手机没有root，所以没有装Xposed，歌曲页面封面是指这个吧，有很多歌是可以正常加载的。不过我的本地音乐里确实很多专辑自带了封面，我清除一下封面图片试试。
![Screenshot_2022-05-21-13-23-06-99_e53b20ddbf74fed48fbb876ec4945b7f.jpg](https://user-images.githubusercontent.com/51269401/169636868-5cb85a32-7298-47bf-b172-882e6b1a7d23.jpg)

**Comment by elijahchan2019** [comment]
似乎方向对了大佬 

我去本地音乐文件夹把我所有专辑的图片都删掉了，重装app，按照之前出问题的几种操作方法使用，都没有再复现了。

**Comment by Moriafly** [comment]
好的，应该可以确认问题原因。软件设定为首先加载内嵌封面，如果没用就尝试加载文件夹下面的 cover.jpg / cover.png 等格式图片，似乎是此处出了问题。

**Comment by Moriafly** [comment]
尝试更新 7.0.3
