### ISSUE TITLE
支持压缩时间戳的歌词文件

### ISSUE THREAD

**Issue by just2ciao** [Moriafly/SaltPlayerSource#248]
软件版本 Software version：7.0.1
系统版本 System version：MIUI 13.0.7

#### 反馈内容 Content of the feedback

如图.在显示倒数第二行的时候就错误.断开后面就不显示了

![Screenshot_2022-05-12-04-16-15-820_com mixplorer](https://user-images.githubusercontent.com/33555873/169701852-b8c9225c-c829-4098-b3dc-d86fb7172530.jpg)
![Screenshot_2022-05-12-04-17-13-701_com salt music](https://user-images.githubusercontent.com/33555873/169701860-fd9c3616-0f08-47ac-a88c-32ff075ea799.jpg)
![Screenshot_2022-05-12-04-16-46-460_com salt music](https://user-images.githubusercontent.com/33555873/169701866-f2bc0375-bc85-4ce1-8a6f-d5ad54e88122.jpg)

**Comment by Moriafly** [comment]
#764 此反馈比较完整，所以转到此反馈
