### ISSUE TITLE
【方法讨论中】支持 MIUI 系统下通过特殊音频通道输出高品质音频

### ISSUE THREAD

**Issue by Ed20010424** [Moriafly/SaltPlayerSource#249]
#### 建议内容 The proposals

<仅讨论可行性>
MIUI貌似为自己系统播放器的本地状态下提供了一个专用的音频输出通道(OFFLOAD)来绕过系统的SRC，其他地方一律强制重采样，包括椒盐音乐中显示无重采样，但在dumpsys media.audio_flinger的输出日志中，依旧被锁定在48khz
经过我的尝试，这里借用隔壁Aplayer修改包名（仅做尝试，无意冒犯），发现MIUI判断是否调用这个通道就是依靠识别小米音乐的包名(com.miui.player)（根据我的尝试QQ音乐的包名也可以，只是这里破俩玩意本地化功能真的太烂了，国际版小米音乐也只是将就能用）
是否能通过一些方法让椒盐音乐通过MIUI这个通道实现全局绕过MIUI的重采样呢？
这样做的好处是能完美使用miui本地音效以及低延迟
![Screenshot_2022-05-22-21-53-44-189_com miui player](https://user-images.githubusercontent.com/52863141/169714349-f59e7a42-9fd5-4a4b-a8d7-44e3633ca222.jpg)

**Comment by Ed20010424** [comment]
补充:隔壁Retro music不需要任何修改，直接调用这个通道，这是和小米py了吗？直接在白名单里，给我惊了，不知道椒盐能不能实现![IMG_20220523_022228.jpg](https://user-images.githubusercontent.com/52863141/169722928-1b46aa35-b09e-42a4-8a75-aa433a2428d4.jpg)

**Comment by Moriafly** [comment]
APlayer 和 Retro Music 使用的都是框架的 MediaPlayer 播放。我不确定 MIUI 是否是通过白名单来控制。可以试试椒盐音乐 Lite，也是基于 MediaPlayer，如果你能帮我测试❤️，可以在酷安下载它。

**Comment by Ed20010424** [comment]
> APlayer 和 Retro Music 使用的都是框架的 MediaPlayer 播放。我不确定 MIUI 是否是通过白名单来控制。可以试试椒盐音乐 Lite，也是基于 MediaPlayer，如果你能帮我测试❤️，可以在酷安下载它。

你好，我尝试了，lite版本确实实现了全局绕过src，还有隔壁的oto music，MIUI应该针对mediaplayer进行魔改了，并不是白名单机制，这个模式未来有可能下放到完整版椒盐音乐吗？不得不说应该给MIUI一个好评lol![IMG_20220523_045545.jpg](https://user-images.githubusercontent.com/52863141/169735040-74d6ae58-354f-4468-b783-64ee33eef4a9.jpg)

**Comment by Moriafly** [comment]
以前听过 MIUI 工程师似乎提过哈哈哈，不过暂时椒盐音乐可能无法更改。

**Comment by Moriafly** [comment]
QQ 音乐也可以吗？QQ 音乐应该用的是 AudioTrack 。

**Comment by Ed20010424** [comment]
> QQ 音乐也可以吗？QQ 音乐应该用的是 AudioTrack 。
QQ音乐我再次尝试了一下，之前是我搞错了，不是白名单，有可能是和MIUI py交易了，单独走的direct通道，不过锁48khz或者96khz
这首exile是88.2khz的直接被锁48khz
![IMG_20220523_051742.jpg](https://user-images.githubusercontent.com/52863141/169736814-f8782f0c-0bd0-4a38-979c-f663629b4382.jpg)
而这首是96khz的
![IMG_20220523_051721.jpg](https://user-images.githubusercontent.com/52863141/169736875-6a2901ef-0aa0-4b7a-a8f5-6610007a9224.jpg)

**Comment by Ed20010424** [comment]
> QQ 音乐也可以吗？QQ 音乐应该用的是 AudioTrack 。

QQ音乐我再次尝试了一下，之前是我搞错了，不是白名单，有可能是和MIUI py交易了，单独走的direct通道，不过锁48khz或者96khz
这首exile是88.2khz的直接被锁48khz
![IMG_20220523_051742.jpg](https://user-images.githubusercontent.com/52863141/169736814-f8782f0c-0bd0-4a38-979c-f663629b4382.jpg)
而这首是96khz的
![IMG_20220523_051721.jpg](https://user-images.githubusercontent.com/52863141/169736875-6a2901ef-0aa0-4b7a-a8f5-6610007a9224.jpg)

**Comment by shikkoku** [comment]
OPPO Realme基于高通芯片的ColorOS 12也不能绕过系统重采样（OpenSL ES/AAudio）开启或者不开启强制更改输出设备的采样率，全部都是走了Mixer，系统播放器走的是Direct通道，当音频文件为96khz、192khz时走Direct通道。

**Comment by kun-niubi** [comment]
实测，我的miui13系统只支持48kHz、96kHz、192kHz这三种输出，而且全部走MIXER，换了好多个软件都是一样，看来没有办法绕过src了
