### ISSUE TITLE
请求适配Nortical的状态栏歌词

### ISSUE THREAD

**Issue by MikeQu223** [Moriafly/SaltPlayerSource#25]
以下是build.prop中关于nortical的信息：

org.nortical.version.prop=
org.nortical.build_date_utc=1628225040
org.nortical.device=ginkgo
org.nortical.ota.version_code=11-R
org.nortical.codename=Alexandrite
org.nortical.build_version=Nortical-UI_ginkgo-userdebug-11.0-Alexandrite-20210806-0444
org.nortical.ota_support=true
附件：build.prop
[build.txt](https://github.com/Moriafly/SaltPlayerSource/files/6944251/build.txt)

**Comment by Moriafly** [comment]
好的

**Comment by Moriafly** [comment]
将会在下个版本得到支持，若无效请重新开启此 issue
