### ISSUE TITLE
浅色主题下三大金刚键也是浅色，难以与背景区分

### ISSUE THREAD

**Issue by Neonxdusk** [Moriafly/SaltPlayerSource#256]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：7.0.4-gamma
系统版本 System version： Android 11 (设备型号：联想小新Pad 即Lenovo TB-J606F 国际版本系统 可以视作类原生) 

#### 反馈内容 Content of the feedback

浅色模式下三大金刚键也是浅色，和背景融为一体，观感不佳
![image](https://user-images.githubusercontent.com/29981297/169806345-082c6bd2-af9d-494b-b220-339ff02bae2e.png)

**Comment by Moriafly** [comment]
此可能为 Android 框架问题，涉及东西较多，与很多开发者讨论过，可能暂时无法解决
