### ISSUE TITLE
自动旋转导致异常切歌

### ISSUE THREAD

**Issue by Xionghaizi001** [Moriafly/SaltPlayerSource#268]
#### 基本信息 The basic information

软件版本 Software version：7.0.7(2022060401)
系统版本 System version：Android 11, Meizu 18 Pro

#### 反馈内容 Content of the feedback

开启自动旋转后，转至横屏再转至竖屏，app会切换下一首。

复现率：100%

**Comment by Moriafly** [comment]
问题重复 #234
