### ISSUE TITLE
关于翻译按钮

### ISSUE THREAD

**Issue by whghjyh** [Moriafly/SaltPlayerSource#269]
当使用音乐标签编辑歌词时，若选择下载翻译格式为
“[00:05.12]原词 1 
[00:07.05]翻译词 1
 [00:07.06]原词 2”模式时，歌词翻译切换按钮不显示。而若选择
“[00:05.12]原词
 [00:05.12]翻译词”模式时，由于musicolet等部分软件只会显示一种歌词（由于时间线冲突），故第一种模式对我来说是必须的。（两款软件都很好用，我都在用，不存在替代关系）
不知道这个问题可否解决，技术上是否可以实现（不很懂代码），如果不行就算了，这是个小问题，无伤大雅。最后感谢开发者做出如此优秀的软件。祝好运！

**Comment by whghjyh** [comment]
我观察到椒盐的在线歌词做的很好，那么建议有一个歌词来源的切换选项本地lrc/internet/embedded三者切换也不错，如果这是个愚蠢的想法或者已经有了请忽略（我貌似没有找到）🤝🤝

**Comment by Moriafly** [comment]
翻译歌词问题属于其他软件的适配问题，因为时间戳不同椒盐音乐是无法分辨哪句是翻译而哪句是原歌词，如有中英混着的歌等等其他情况。

**Comment by Moriafly** [comment]
椒盐音乐歌词优先获取内嵌，若无法获取内嵌则获取 lrc，最后尝试获取网络歌词。
