### ISSUE TITLE
kwgt无法识别椒盐音乐为音乐APP

### ISSUE THREAD

**Issue by MikeQu223** [Moriafly/SaltPlayerSource#27]
#### 基本信息 The basic information

软件版本 Software version：3.3.0
系统版本 System version：安卓11类原生

#### 反馈内容 Content of the feedback
kwgt无法识别椒盐音乐为音乐APP
![Screenshot_20210807-103356.png](https://user-images.githubusercontent.com/63991532/128585925-67a1bb89-3840-4327-bf4f-1887d4474326.png)

**Comment by JingwenWang-Jingle** [comment]
现在仍然不能🤔😭😭😭

**Comment by Moriafly** [comment]
暂无法完成适配，已关闭
