### ISSUE TITLE
7.x版本失去了5.x版本读取歌曲同一文件夹图片功能

### ISSUE THREAD

**Issue by dgf175** [Moriafly/SaltPlayerSource#272]
RT 在5.x版本会自动读取歌曲同一文件夹下的图片并显示
更新至7.x版本后就没有这个功能了

**Comment by Moriafly** [comment]
因为有些严重问题而移除了（可能造成软件卡死），后续找到更好的方法会尝试加回，此问题会保留。

**Comment by Moriafly** [comment]
问题移至 #290
