### ISSUE TITLE
歌单内容消失

### ISSUE THREAD

**Issue by yufengshijiu03** [Moriafly/SaltPlayerSource#279]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：<软件版本 Software version>7.0.13(2022062301
系统版本 System version：<系统版本 System version>
Xiaomi11V13.0.7.1.39.DEV 开发版
#### 反馈内容 Content of the feedback

<在此输入你遇到的问题，必填 Enter the problem you encountered here. Required>
歌单原有内容消失
![Screenshot_2022-06-24-12-01-23-023_com salt music](https://user-images.githubusercontent.com/79011135/175460558-deaffbb4-587c-48f2-84b4-b51abd9690d2.jpg)
![Screenshot_2022-06-24-12-01-16-461_com salt music](https://user-images.githubusercontent.com/79011135/175460565-24bcb957-8456-41e3-9728-5bea8c038e67.jpg)

**Comment by Moriafly** [comment]
暂时可以尝试点击歌单右侧三点菜单选择修复
因为歌曲文件可能移动或者被删除
椒盐音乐 V7 的逻辑设计存在问题，等待后续修复
