### ISSUE TITLE
歌词bug？

### ISSUE THREAD

**Issue by 233Xie** [Moriafly/SaltPlayerSource#284]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：<软件版本 Software version>7.0.14(2022062601)
系统版本 System version：<系统版本 System version>redmi k50 pro，MIUI 13.0.20.0稳定版

#### 反馈内容 Content of the feedback

<在此输入你遇到的问题，必填 Enter the problem you encountered here. Required>

本地有歌词文件，但是播放的时候没有歌词，而且不知道为什么显示歌词源自网络
![Screenshot_2022-06-30-04-27-28-098_bin.mt.plus.jpg](https://user-images.githubusercontent.com/92447302/176539344-5e647c2c-25ae-41b2-a9b8-78139ffcce70.jpg)![Screenshot_2022-06-30-04-26-52-178_com.salt.music.jpg](https://user-images.githubusercontent.com/92447302/176539358-4fbd9098-080b-4bf2-ad6b-8a8670142006.jpg)

**Comment by Moriafly** [comment]
是否有使用类似存储空间隔离的软件？

**Comment by Moriafly** [comment]
问题过旧，尝试给予下椒盐音乐安装第三方软件的权限。
