### ISSUE TITLE
从网络获取歌词的问题

### ISSUE THREAD

**Issue by KevenSmart666** [Moriafly/SaltPlayerSource#285]
从网络获取歌词有时没法正常获取，我可以通过两首歌之间切换重试多次后便能获取成功
这导致状态栏歌词不能正常使用😫
我的设备网络环境畅通

Project Elixir Android 12
Redmi K30 Pro
7.0.14(2022062601)
海南电信

**Comment by KevenSmart666** [comment]
同一首歌获取到以后，等我再回来听这首歌的时候歌词又得重新获取，像issue274提到的获取到歌词后缓存本地就蛮好的，同时建议对于这个功能做好一个缓存阈值，到了之后自动删除最旧的文件（？

**Comment by Moriafly** [comment]
椒盐音乐网络歌词源来自QQ音乐源，QQ音乐封锁了以前的获取方式。

**Comment by Moriafly** [comment]
更新 7.0.17 版本
