### ISSUE TITLE
切歌后有时音量会变很小

### ISSUE THREAD

**Issue by CCJ623** [Moriafly/SaltPlayerSource#287]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：7.0.15
系统版本 System version：Android 12L

#### 反馈内容 Content of the feedback

<在此输入你遇到的问题，必填 Enter the problem you encountered here. Required>
切歌后有时候会音量变得很小，已尝试过清除软件数据、切换输出模式，都没有用，但用文件管理器播放时毫无问题。我发现了一些规律，播放开始前的平均延迟只有35ms和115ms两个值，当在35ms时音量就会变得非常小，115ms时音量正常
![Screenshot_20220704-221236_椒盐音乐~2](https://user-images.githubusercontent.com/53177879/177172555-089fba01-0ba3-434c-a734-7f68aeaab5ae.png)
![Screenshot_20220704-221249_椒盐音乐~2](https://user-images.githubusercontent.com/53177879/177172570-49002627-3b52-432a-a074-3e6638b27936.png)

**Comment by CCJ623** [comment]
好像是只有蓝牙才会出现这个问题

**Comment by Moriafly** [comment]
是否是切换到特定歌曲发生？还是不可预测？

**Comment by CCJ623** [comment]
现在发现好像是系统crdroid的问题，在播放视频时也会随机的变得小声，必须要重新进入才有几率恢复，这有可能和系统内置的杜比音效有关吗？
