### ISSUE TITLE
求加一个定时关闭的功能

### ISSUE THREAD

**Issue by cs2fupanpibg** [Moriafly/SaltPlayerSource#29]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

<在此输入你的建议 Enter your suggestions here>

**Comment by Moriafly** [comment]
谢谢建议，会在后续开发此功能，暂时被搁置。

**Comment by Moriafly** [comment]
可以关注 #2
