### ISSUE TITLE
所以歌曲都没有歌词

### ISSUE THREAD

**Issue by Unperishability** [Moriafly/SaltPlayerSource#292]
![Screenshot_20220712-163911_Salt Player](https://user-images.githubusercontent.com/109139532/178448204-02f0b473-d99c-4425-a0ec-e475b1bc0b80.jpg)

设备:三星s22 ultra，原本可以正常加载歌词，最近突然所有歌曲都没有歌词了，尝试安装其他版本任然没有歌词

**Comment by Moriafly** [comment]
受版权问题，网络歌词功能受限，推荐使用音乐标签内嵌歌词或者使用 LRC 歌词文件。
