### ISSUE TITLE
歌词滚动优化

### ISSUE THREAD

**Issue by hacamer** [Moriafly/SaltPlayerSource#297]
椒盐音乐的歌词滚动似乎有些生硬，对比过Lite版
感觉Lite版更好
希望大佬可以优化一下:)
![Screenshot_2022-07-20-23-35-43-686_com salt music](https://user-images.githubusercontent.com/73057402/180233402-4b6f02b6-4aa5-4805-ad7c-c77b68fc9207.jpg)

**Comment by hacamer** [comment]
准确来讲，正式版歌词滚动速度比Lite快很多 
Lite版歌词滚动速度刚刚好

**Comment by Moriafly** [comment]
等待谷歌 https://issuetracker.google.com/issues/218542111
