### ISSUE TITLE
两首歌名字一样的话，封面显示的方面有问题，只会将其中一首歌的封面用到两首歌身上，用音乐标签改了也没用，不知道是什么原因造成的。还有滑动音乐列表偶尔会有点顿挫，影响观看。

### ISSUE THREAD

**Issue by LIUYOHIO** [Moriafly/SaltPlayerSource#30]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：<软件版本 Software version>
系统版本 System version：<系统版本 System version>

#### 反馈内容 Content of the feedback

<在此输入你遇到的问题，必填 Enter the problem you encountered here. Required>

**Comment by Moriafly** [comment]
目前软件依赖安卓媒体库，会将同专辑（专辑名且专辑艺术家相同）的歌曲封面保持一致。
若需要支持同目录下以图片作为歌曲封面，尝试在应用设置中开启 **忽略媒体库封面**，并重新启动应用程序。

列表滑动属于性能优化，目前我技术还比较菜鸡，会持续优化~

**Comment by Moriafly** [comment]
**还有滑动音乐列表偶尔会有点顿挫，影响观看。** 将会开启新的 issue 。
若封面还有问题请重新开启此 issue 。

**Comment by Moriafly** [comment]
#31
