### ISSUE TITLE
无法扫描到播放文件夹新的歌曲

### ISSUE THREAD

**Issue by CMingXiang** [Moriafly/SaltPlayerSource#304]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：<软件版本 Software version>
系统版本 System version：<系统版本 System version>

#### 反馈内容 Content of the feedback

<在此输入你遇到的问题，必填 Enter the problem you encountered here. Required>
手机型号：华为荣耀30 BMH-AN10
系统： 鸿蒙 2.0.0
软件版本：7.1.0-beta03(2022072301)
问题：椒盐音乐在第一次扫描歌曲后再当我使用QMD下载歌曲到手机根目录的music文件夹后，椒盐无法扫描到新加入文件夹的歌曲，歌曲的类型为FLAC格式。软件的权限已经给过了。

**Comment by Moriafly** [comment]
可能是你的系统媒体库未重新扫描文件，可以尝试重新启动手机（注意不是软重启），或者下载椒盐音乐推荐的媒体重新扫描应用：https://foyou.lanzoui.com/inR3iuarmaj ，此软件会对全文件进行扫描来刷新系统媒体库。
