### ISSUE TITLE
不兼容VIPER音效的传统模式

### ISSUE THREAD

**Issue by Simlalsy** [Moriafly/SaltPlayerSource#308]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：7.1.0-rc02 (2022080301)
系统版本 System version：Ancient OS 6.2 安卓12

#### 反馈内容 Content of the feedback

无论如何修改软件内的输出以及解码方式，或者关闭自带的音效处理，均无法使输出音频在VIPER的传统模式上运行，若取消传统模式，者可以正常运行，但是，除了椒盐音乐以外的其他音频输出全部消失。推断是SELinux规则导则的音频输出问题

<在此输入你遇到的问题，必填 Enter the problem you encountered here. Required>

**Comment by Moriafly** [comment]
你好，我暂时不是很了解 VIPER 音效。此问题暂时得到保留。

**Comment by Simlalsy** [comment]
第1种情况：直接播放不兼容传统模式
第2种情况：当其他音乐软件播放时，被椒盐音乐的音频输出打断，则兼容传统模式
https://www.123pan.com/s/unH9-bleHh

**Comment by Simlalsy** [comment]
第1种情况：直接播放不兼容传统模式
第2种情况：当其他音乐软件播放时，被椒盐音乐的音频输出打断，则兼容传统模式
https://www.123pan.com/s/unH9-bleHh
