### ISSUE TITLE
读取滚动歌词无法读取时间戳写在一起的段落

### ISSUE THREAD

**Issue by null1229** [Moriafly/SaltPlayerSource#318]
![Uploading Screenshot_2022-08-11-22-58-26-968_com.xjcheng.musictageditor.jpg…]()
[03:54.25][02:30.68][01:06.20]歌词...
像这种时间戳写在一起的段落软件内读取不到，只能读取到第一个时间戳，试了其他的音乐软件都是可以的，但是都没有椒盐音乐的界面好看，恳求作者大大能解决这个问题！万分感谢！

**Comment by Moriafly** [comment]
#248
