### ISSUE TITLE
关于主界面自定义壁纸的一些功能增强建议

### ISSUE THREAD

**Issue by Asanatsu** [Moriafly/SaltPlayerSource#338]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

希望主界面自定义壁纸功能可以支持：
1、图片裁剪
原因：这个不用多说啦，调用系统相册自带裁剪功能就行

2、黑色和白色遮罩，并提供颜色深度滑条
原因：亮度高或颜色鲜艳的图片，会导致白色字体难以辨识，如果支持黑色和白色遮罩覆盖并提供深度调节功能，界面文本UI能见度会得到极大改善（还可以护眼）

**Comment by Moriafly** [comment]
我觉得这些都是可以通过图片处理软件解决的。
