### ISSUE TITLE
随机播放一些思路

### ISSUE THREAD

**Issue by Blooming298K** [Moriafly/SaltPlayerSource#34]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

1.随机播放模式时，播放列表右侧可添加刷新Button，随机刷新当前播放列表（参考Phonograph随机播放）
2.随机播放是否考虑添加Tensorflow Lite等一些AI算法离线研究用户听歌习惯，适度增加插盲率之类。
3.人为调整歌单播放顺序，则播放顺序自动刷新（可结合1考虑）

**Comment by yzsm385** [comment]
随机播放为什么只能在小部分范围（尤其是在几个字母索引内有效，跳到远的范围的概率很低）
