### ISSUE TITLE
快速定位目标音频调整建议

### ISSUE THREAD

**Issue by Taozhi18** [Moriafly/SaltPlayerSource#349]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals
当前版本在浏览音乐时可以利用首字母快速定位，可是当出现首字母一致而又非常多的音频时，就无法快速定位，只能通过上滑屏幕浏览音乐，找到目标音频比较耗时，希望增加一个右侧滑动栏，可以快速滚动，方便找到目标音频。

**Comment by Moriafly** [comment]
在等待谷歌团队对 Compose 滚动条的支持，这可能还需要些时间
![image](https://user-images.githubusercontent.com/62319450/187811203-066e639b-3b99-4f82-a187-48baa8c92489.png)
