### ISSUE TITLE
收藏和定位当前歌曲功能

### ISSUE THREAD

**Issue by AAAAAnguslu** [Moriafly/SaltPlayerSource#36]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

<在此输入你的建议 Enter your suggestions here>
1，希望可以添加收藏功能，方便寻找常听的歌曲，在歌曲播放界面加一个小爱心表示收藏就可以
2，希望可以增加定位当前歌曲的功能，一键定位到当前歌曲在列表中的位置
3，桌面歌词我看有人反映了，希望作者大大可以考虑落实
最后表达对作者大大的感谢，这个app特别好，我非常喜欢，简介美观好用，支持大大！

**Comment by AAAAAnguslu** [comment]
哦，我记起来可以长按播放栏定位当前歌曲位置，不好意思，定位歌曲这条建议作废

**Comment by AAAAAnguslu** [comment]
还有一个小建议，4，希望播放栏加一个下一曲的按钮

**Comment by Moriafly** [comment]
感谢建议~
