### ISSUE TITLE
如果音乐标签信息中存在多个艺术家/歌手，椒盐音乐只识别到其中一个

### ISSUE THREAD

**Issue by nukemiko** [Moriafly/SaltPlayerSource#364]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：7.9.2
系统版本 System version：Android 11 ColorOS V12 A.10

#### 反馈内容 Content of the feedback

如果一个音乐文件的标签信息中，存在多于一个艺术家/歌手，那么椒盐音乐只会识别到其中一个（通常是最后一个）。不仅表现在歌曲信息的显示上，在 左滑菜单>艺术家 中也只能找到它识别出来的这个。

例如以下文件：（[下载链接](https://0x0.st/oWIJ.flac)）

在 Windows 文件资源管理器，和 Poweramp 中，可正确显示两个艺术家“伊藤彩沙”和“生田輝”：
![批注 2022-09-26 180558](https://user-images.githubusercontent.com/53572814/192253243-5fcfba38-0cab-48ba-96aa-06b52dec4dd7.png)
![Screenshot_2022-09-26-18-07-15-26_345bb2134bfb84a7decceb0b36861421](https://user-images.githubusercontent.com/53572814/192253723-eac42277-1ddf-4c5d-9848-c2598d187e2c.jpg)

在 Mp3Tag 中显示的信息：
![Screenshot_20220926_182147](https://user-images.githubusercontent.com/53572814/192253466-b9098e54-fb0b-434a-a7d1-ae9361d726db.png)

但是在椒盐音乐中，只识别到最后一个艺术家“生田輝”：
![Screenshot_2022-09-26-18-07-00-46_e53b20ddbf74fed48fbb876ec4945b7f](https://user-images.githubusercontent.com/53572814/192254217-22585e00-8acd-4a40-8b62-4da5f9d7eb16.jpg)
并且在艺术家列表里找不到另一个艺术家“伊藤彩沙”的信息。

**Comment by Moriafly** [comment]
这是应该是 ID3 标签中不推荐的做法，如果是同级参与艺术家，应该仅写在 TPE1 标签中使用 / 分割。

**Comment by Moriafly** [comment]
![image](https://user-images.githubusercontent.com/62319450/192432283-b1f06611-d9db-4781-ad0a-013a71e6bfb0.png)
![image](https://user-images.githubusercontent.com/62319450/192432330-0db4a047-0b5c-494c-b5b2-288b90099aaa.png)
![image](https://user-images.githubusercontent.com/62319450/192432410-cb26705a-7f93-4e64-8664-562e62eadb2f.png)

**Comment by Moriafly** [comment]
如果他们都是参与的艺术家，应该在第一个 TPE1 中使用 / 分割，而乐队伴奏写于第二个。一般来说仅使用第一个即可，均通过 / 分割。

**Comment by nukemiko** [comment]
> 如果他们都是参与的艺术家，应该在第一个 TPE1 中使用 / 分割，而乐队伴奏写于第二个。一般来说仅使用第一个即可，均通过 / 分割。

虽然 ID3 标准推荐用单斜杠 / 分割，但是使用双反斜杠 \\ 分隔不同的参与艺术家这样的现象确实广泛存在，说明这很可能是一个惯例。

**Comment by Moriafly** [comment]
似乎仅是以 \\ 分割 TPE1 TPE2 等，依旧是不推荐的行为，我会在后续验证。

**Comment by Sanheiii** [comment]
我用windows属性页中默认的“; ”来分隔多个艺术家，在椒盐音乐中“;”被丢弃，剩下的全部被显示为同一位艺术家
![Screenshot_2022-12-21-13-07-02-06_e53b20ddbf74fed48fbb876ec4945b7f](https://user-images.githubusercontent.com/35133371/208826143-d92ec885-acbc-4b8e-8aa8-d9baf8cdba59.jpg)

**Comment by Moriafly** [comment]
和 #460 应该是同个问题
