### ISSUE TITLE
希望软件提供accessibility无障碍支持

### ISSUE THREAD

**Issue by ghost** [Moriafly/SaltPlayerSource#390]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

<在此输入你的建议 Enter your suggestions here>

开发者您好。我是你软件的一个盲人用户。很喜欢您开发的这个软件。但目前在使用软件的过程中，有一些小小的问题。
软件内缺少很多无障碍标签，例如打开侧边栏的标签。以及在播放界面的修改播放模式。这个不仅没标签，连交点都无法锁定在该按钮上。
希望您有时间的时候能优化一下，真的十分感谢。
如果您对此不太了解的话，可以参阅Google的无障碍开发指南。
再次表示感谢。

**Comment by lengyuxiadeshaonv** [comment]
国内也有一个网站提供相关文档的翻译版，如有需要可以看一下，我将链接贴在下面。
[无障碍知识库](http://www.siaa.org.cn/knowledge?id=3)

**Comment by Moriafly** [comment]
非常感谢反馈，我会在后续推进无障碍支持。

**Comment by Moriafly** [comment]
12.2 优化开关选项、播放界面底部按钮、播放队列的无障碍适配

**Comment by Moriafly** [comment]
23/1/2 8.3.0-beta04 音乐通知栏适配无障碍
