### ISSUE TITLE
优化列表性能

### ISSUE THREAD

**Issue by Pr0pHesyer** [Moriafly/SaltPlayerSource#402]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：7.13.1-presale-play(2022111202
系统版本 System version : Pixel 3 Android 12L

#### 反馈内容 Content of the feedback

收到了presale版本，选曲界面性能明显下降，划动时有可感知的卡顿。
请问版本分发是怎么处理的？卡顿会在新版本中解决吗？

**Comment by Moriafly** [comment]
正在关注这个问题。

尝试加入到 Play 商店 beta 渠道，最新的 7.14.0-alpha05 以尝试优化此情况。

**Comment by Pr0pHesyer** [comment]
> 正在关注这个问题。
> 
> 尝试加入到 Play 商店 beta 渠道，最新的 7.14.0-alpha05 以尝试优化此情况。

7.14.0-alpha05中划动情况有好转。快速滑动时，滑动方向的封面缩略图载入较慢，有几首歌会封面白一小会，约为屏幕上歌曲的1/5

https://user-images.githubusercontent.com/74277431/201564794-9048ae21-e210-4efb-8f45-09f07d751e5f.mp4

**Comment by Moriafly** [comment]
软件的列表性能会持续优化，也会持续关注谷歌团队的优化，https://issuetracker.google.com/issues/225186413

**Comment by Pr0pHesyer** [comment]
> 软件的列表性能会持续优化，也会持续关注谷歌团队的优化，https://issuetracker.google.com/issues/225186413

在加入beta计划之前收到preplay版本的更新推送是正常情况吗？

**Comment by Moriafly** [comment]
是正常的
