### ISSUE TITLE
增强扫描 可指定扫描某文件夹 （含.nomedia ）

### ISSUE THREAD

**Issue by chillxxxxxx** [Moriafly/SaltPlayerSource#406]
希望可以增加一个可指定扫描某个文件夹的功能，即使它包含.nomedia   
因为太多媒体文件在手机里显得杂乱无章（例如聊天发送图片时），所以我会将这类屏蔽。
我之前在某款本地音乐播放器上见过可以扫描.nomedia文件夹。
仅仅建议，感谢

**Comment by Moriafly** [comment]
已支持自定义扫描 .nomedia
