### ISSUE TITLE
希望能增加语音助手搜歌功能

### ISSUE THREAD

**Issue by 553421138** [Moriafly/SaltPlayerSource#410]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

用了很多音乐播放软件，只有椒盐是能安装在车机并且在组件中显示歌词的，希望能增加一个语音搜歌功能，能在开车途中让语音助手搜索想听的歌，行车安全也能得到保障，万分感谢，附带目前使用的助手软件https://nas.hk-beautyshop.cn:5001/sharing/16uKtXTTP

**Comment by Moriafly** [comment]
我似乎无法访问此链接 https://nas.hk-beautyshop.cn:5001/sharing/16uKtXTTP

**Comment by 553421138** [comment]
https://nas.hk-beautyshop.cn:5001/sharing/ikeuxCen7
密码jy

**Comment by 553421138** [comment]
![20221116_211855](https://user-images.githubusercontent.com/42268733/202399974-903e905f-2221-4b09-95b0-734d8f2242f3.png)
这是椒盐音乐在车机上播放音乐的样式，在组件和右上角都有歌词在轮播

**Comment by Moriafly** [comment]
已在 8.2.0-beta04 完成开发
