### ISSUE TITLE
同一目录内音乐被分入两个文件夹

### ISSUE THREAD

**Issue by wutong233** [Moriafly/SaltPlayerSource#457]
#### 基本信息 The basic information

软件版本 Software version：8.2.3
系统版本 System version：MIUI14 Android13
机型 Model: Xiaomi 12S Pro

#### 反馈内容 Content of the feedback
扫描音乐后，位于/storage/emulated/0/netease/cloudmusic/Music这一目录内的音乐被分入两个文件夹Music和music，总数相同，具体如图。可是仅仅大小写不同不也是同一目录吗？
![Screenshot_2022-12-15-20-57-20-159_com salt music](https://user-images.githubusercontent.com/35332983/207899340-cffbc341-0e4b-4b8b-97c2-f2084341fcf6.jpg)
![Screenshot_2022-12-15-20-57-22-537_com salt music](https://user-images.githubusercontent.com/35332983/207899356-13472d23-7de2-49bc-a38b-7627e9b565db.jpg)
![Screenshot_2022-12-15-20-57-27-229_com salt music](https://user-images.githubusercontent.com/35332983/207899362-7fc824a8-6cf1-4957-ac4e-564850b23381.jpg)
![Screenshot_2022-12-15-20-57-33-939_bin mt plus](https://user-images.githubusercontent.com/35332983/207899371-d05c8f65-2d4b-4997-a8c3-8e9914bf3d32.jpg)

**Comment by Moriafly** [comment]
检查是否存在 music 文件夹（小写）？
