### ISSUE TITLE
8.3b1更新横屏播放界面左右滑界面显示反馈

### ISSUE THREAD

**Issue by sunkillz** [Moriafly/SaltPlayerSource#462]
#### 基本信息 The basic information
软件版本 Software version：<酷安渠道8.3.0 beta01>
系统版本 System version：<Harmony 3.0.0.190>
#### 反馈内容 Content of the feedback
<播放界面横屏模式下，左滑图片出现歌词，，然后右滑播放界面，又出现歌词，就复现出双倍歌词双倍快乐的场景了～不应该是做成有一边存在歌词界面，滑动另外一侧，会歌词从滑动侧出现，原来存在歌词位置会复原，这才符合用户体验嘛>

**Comment by Moriafly** [comment]
用户有需求专辑封面和歌词同时出现，目前方案是妥协做法，在不影响原先的情况下，让用户自行搭配。
