### ISSUE TITLE
每次打开都显示这个，在资源管理器删除过歌曲

### ISSUE THREAD

**Issue by meihus** [Moriafly/SaltPlayerSource#463]
![e0322800cc22f28ea802c1bf92d2ae7](https://user-images.githubusercontent.com/63285959/209415850-b4f2fcb0-f759-4a5b-aff1-32a3397fb51e.jpg)

**Comment by Moriafly** [comment]
是播放到指定歌曲的时候吗？

**Comment by meihus** [comment]
> 是播放到指定歌曲的时候吗？

没有播放，是划了后台重新打开就会显示

**Comment by Moriafly** [comment]
你好，尝试在歌曲界面下拉刷新扫描，或者在扫描界面重新扫描试试

**Comment by meihus** [comment]
> 你好，尝试在歌曲界面下拉刷新扫描，或者在扫描界面重新扫描试试

现在没有这个问题了
