### ISSUE TITLE
菜单栏自动收回功能

### ISSUE THREAD

**Issue by madara9212** [Moriafly/SaltPlayerSource#47]
![S10827-16145951](https://user-images.githubusercontent.com/36496649/131096183-06d4f0f5-b47a-48f5-989d-bc5b443faa65.png)
希望添加自动收回功能，更顺手方便一点。
菜单栏上下滑动右边的时候，左边导航栏自动收回。

**Comment by Moriafly** [comment]
侧滑操作将在后续版本移除。
