### ISSUE TITLE
音频焦点功能

### ISSUE THREAD

**Issue by d2184** [Moriafly/SaltPlayerSource#48]
无论是关闭还是开启音频焦点，正在播放的音乐都会被系统通知铃声打断而暂停，需要手动点击恢复播放。希望能像Poweramp一样提供 允许在短音频焦点(如系统通知铃声)时降低音量 而不是彻底暂停播放的解决方案。
![Screenshot_20210829-131229~2](https://user-images.githubusercontent.com/63200181/131239453-7eacfa27-dd85-489e-8386-52d73f98af3b.png)
![Screenshot_20210829-131300~2](https://user-images.githubusercontent.com/63200181/131239468-499b4ab6-62dd-4359-bbb4-f6892dfee072.png)

**Comment by Moriafly** [comment]
暂时不会更改，完全安装谷歌开发者文档设计，后续可能变更。
