### ISSUE TITLE
“随机播放”按钮需要点两下才能正常随机播放

### ISSUE THREAD

**Issue by Mr-233333** [Moriafly/SaltPlayerSource#483]
#### _基本信息_

软件版本 ：<8.3.0-beta05>
系统版本 ：< Android12 >

#### _反馈内容_ 

当你目前在听一个歌单时,点歌单顶上的“随机播放”按钮,可以正常随机打乱队列
但当你想换一个歌单听的时候，点歌单顶上的“随机播放”，**永远会首先播放最顶上一首歌**，再点一下“随机播放”才能从歌单里随机挑一首歌播放，**100%复现**
**在任意包含“随机播放”按钮的界面均有此bug**，给随机播放体验带来巨大的麻烦，每次换播放列表都要点两次
猜测是之前改成**真随机**导致的问题，希望今早修复
![Screenshot_2023-01-11-10-31-31-716-edit_com salt music](https://user-images.githubusercontent.com/116350991/211704403-a73beb21-deaf-4e0c-8987-21dea9affdca.jpg)

**Comment by Moriafly** [comment]
尝试更新 8.3.0-beta06
