### ISSUE TITLE
播放音乐时切换到QQ后音乐自动暂停

### ISSUE THREAD

**Issue by Asaka-xin** [Moriafly/SaltPlayerSource#492]
#### 基本信息 The basic information

软件版本 Software version：<**8.3.0-build2023011102**>
系统版本 System version：<**MIUI 12.5 Based on Android 11**>

#### 反馈内容 Content of the feedback

<以下是详细描述>

*该问题是QQ频道群友说的*
播放音乐时切换到QQ(椒盐音乐进入后台运行)(**音频焦点**为关闭)，正在播放被自动暂停。
后面群友说**关闭播放暂停时淡入淡出**就无此现象了

<可能的环境变量>
**- 音频焦点**
**- 播放暂停时淡入淡出**

**Comment by Moriafly** [comment]
你好，可能是因为开启了 QQ 小世界短视频其请求了音频焦点，也可能是使用了 AAudio 输出模式
还可能是其他情况，暂时无法复现，会持续关注
