### ISSUE TITLE
请官方增加对老旧安卓系统版本的支持等，扩展市场占有率，感谢！

### ISSUE THREAD

**Issue by www766** [Moriafly/SaltPlayerSource#501]
现在很多使用场景下还有很多设备为安卓老旧系统，大众等各品牌车机系统、海信等各品牌电视、华为等各品牌电视盒子，这些设备都还是之前的安卓4.几的系统，并且是头几年大批上市智能设备大量上市的阶段，存量相当之大！我目前的车机好像是安卓4.2，安装椒盐直接提示安装包解析错误，无法安装。
1、**建议：**官方增加对安卓4.几的官方支持
2、**问题：**目前APP对安卓系统的要求起步是什么安卓版本？请软件介绍中给予提示或答复。
3、**建议：**既然是本地化软件，网络化是弱项，建议增加对群晖NAS等串流各类协议远程访问支持，增强整体实力。
4、**问题：**我的车机系统下载安装椒盐的哪个版本能够成功安装在车机上（安卓4.2）？
5、**建议：**增加对软件设置、歌单的导入导出功能，这样作为本地播放器虽然不能云同步，但起码可以实现在两个手机、平板、车机等硬件上的配置一致，实现半无感化。
已捐赠，期待作者的答复，问的有点乱不好意思想到哪写到哪请大佬按序号答复，感谢作者出此佳软以飨网友！

**Comment by Moriafly** [comment]
抱歉无法提供对4.x系统的支持，可能会将此工作交给椒盐音乐lite负责

**Comment by Moriafly** [comment]
问题3/5已存在相关issues，问题4目前没有任何可以安装的软件版本
新年快乐

**Comment by FatTurtle2022** [comment]
希望尽快更新支持4.x版本的椒盐音乐Lite，加油！

**Comment by yrd3d** [comment]
> 抱歉无法提供对4.x系统的支持，可能会将此工作交给椒盐音乐lite负责

哎，好可惜啊，我的车机系统也是安卓4.X的，就一直用不上椒盐。
