### ISSUE TITLE
非全面屏或Android 9上浅色模式导航栏（非手势小横条）未适配

### ISSUE THREAD

**Issue by shizheng233** [Moriafly/SaltPlayerSource#505]
#### 基本信息 The basic information

软件版本 Software version：8.3.0 beta7
系统版本 System version：Android 9

#### 反馈内容 Content of the feedback

在Android 9或是非全面屏手机上使用传统导航栏时若是 **浅色主题** 则 _导航栏_ 也是 **白色** ，深色模式无这种情况。在Android10以上我记得应该不用另外适配。

![Screenshot_20230121-145745](https://user-images.githubusercontent.com/28999306/213848384-d2860acf-b567-4f7e-a1d5-4dd33bf54385.png)

幸苦大佬，我本身也是个半吊子的自学的开发者。知道多适配一个Android版本的需要做什么。话说大佬的这个项目是直接迁移到compose还是使用了compose和传统view的混合开发。

**Comment by Moriafly** [comment]
椒盐音乐是一个Compose和View混合项目

**Comment by Moriafly** [comment]
已在8.6b2修复
