### ISSUE TITLE
鸿蒙版封面下面的歌词不显示，但在沉浸模式下仍可以点击

### ISSUE THREAD

**Issue by shanyan-wcx** [Moriafly/SaltPlayerSource#506]
#### 基本信息 The basic information

软件版本 Software version：8.3.0-beta-hmos(2023022302)
系统版本 System version：p20 pro ,鸿蒙3.0

#### 反馈内容 Content of the feedback

鸿蒙版封面下面的歌词不显示，但在沉浸模式下仍可以点击.

**Comment by Moriafly** [comment]
确定是正确的版本号吗？似乎并未发布此版本

**Comment by shanyan-wcx** [comment]
8.3.0-beta06-2023011302
打错了

**Comment by Moriafly** [comment]
是在沉浸模式下小歌词不显示吗？

**Comment by shanyan-wcx** [comment]
![Screenshot_20230130_000210_com jio media jiobeats](https://user-images.githubusercontent.com/58252651/215338864-469a68d1-4caa-4bd8-ae65-1f8b8ce24028.jpg)
![Screenshot_20230130_000222_com jio media jiobeats](https://user-images.githubusercontent.com/58252651/215338917-99fc6b7c-2102-4b79-9b27-ca0e24b6d21b.jpg)
![Screenshot_20230130_000526_com jio media jiobeats](https://user-images.githubusercontent.com/58252651/215339003-4e2cd03d-937d-4321-aeb2-fc10008f1a03.jpg)

正常模式下不显示小歌词，然后沉浸模式下中间那块区域没有东西但是还是能点击。

**Comment by Moriafly** [comment]
鸿蒙版本暂未构建小歌词功能，等待后续更新。“沉浸模式下中间那块区域没有东西但是还是能点击”是目前逻辑，即仅隐藏不影响操作。
