### ISSUE TITLE
关于Direct模式的音频服务在MIUI上的调用策略问题

### ISSUE THREAD

**Issue by Andrea-lyz** [Moriafly/SaltPlayerSource#509]
.#### 基本信息 The basic information

软件版本 Software version：8.3.0-release-2023013001
系统版本 System version：MIUI 14 V14.0.23.1.9 DEV For MIX4

#### 反馈内容 Content of the feedback
经实测，Direct模式在MIUI能够正确激活OFFLOAD通道，但在手动切换不同采样率曲目时，会出现通道掉回Mixer的问题
复现流程：播放列表中两首不通采样率的曲目，首先播放的曲目能正常激活OFFLOAD，然后手动切歌，音频通道100%掉回Mixer通道。而如果正常播放完歌曲，自动下一首，不存在此问题。
经研究发现，包括但不限于自带小米音乐，Play商店的Oto、Retro，以及酷安的APlayer，甚至椒盐Lite，均在我的设备上不存在此问题，似乎椒盐在对比其他播放器的手动切歌时并未释放音频服务，从而导致不同采样率的曲目被系统Mix。但问题就来了，自带小米音乐，Play商店的Oto、Retro，以及酷安的APlayer，甚至椒盐Lite 虽然是避免了这个掉Mixer的问题，但似乎引入了新的问题（这个问题椒盐完整版没有），他们几个播放器在手动切歌时（特别是连续快速切歌时）会出现播放失败的问题，触发概率我自身感受是Oto=椒盐lite＜Retro=小米音乐＜Aplayer，这可能涉及到了MediaPlayer框架的局限性了，不知椒盐是否有解决方案呢？
当然，对于这两种方式，我更希望是后者，保证不被SRC为优先，快速切歌导致播放失败影响不大，没事也不会老快速切歌（doge

**Comment by Moriafly** [comment]
已在8.3.2修复

**Comment by Andrea-lyz** [comment]
> 已在8.3.2修复

修复未成功，手动切歌还是掉mixer
