### ISSUE TITLE
椒盐音乐的歌词格式录入要求和PC端软件不同

### ISSUE THREAD

**Issue by Lost-Voice** [Moriafly/SaltPlayerSource#510]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

（1）原歌词和翻译歌词的显示问题
滚动歌词需要在行首设置时间轴，但是我相同的歌词lrc文件在PC端的音乐播放软件显示时，歌词只需在原歌词行首添加，翻译换行，同一时间可以同时显示原歌词和翻译，如：

txt编辑状态：
[xx:xx.xx]Hello, world！
你好，世界！

PC显示端显示状态：
Hello, world！
你好，世界！

但椒盐音乐的播放器却需要原歌词和翻译在不同行且两行都必须在行首添加时间轴才能同时显示原歌词和翻译，并通过播放器自带的功能切换是否显示翻译（关于这个我也是在自己不断更改歌词文本内容格式时才摸索出来的，我不清楚为了实现椒盐音乐歌词的相关功能到底对于歌词的录入格式有什么要求，一次次试实在是特别痛苦），这与我PC端使用的音乐播放器要求的歌词录入格式冲突（用椒盐音乐要求的歌词录入格式在PC端的播放器上无法正常显示）。

所以能否对歌词的录入格式进行兼容，否则我每首有歌词的曲子都必须在翻译行添加时间轴，歌曲很多，歌词改起来很麻烦；如果功能不允许的话能否添加教程，告诉用户内镶/外置lrc的歌词需要保证怎样的录入格式才能在椒盐音乐播放器中正常显示并满足相应的功能？

（2）歌词空行无法显示
和问题（1）同属歌词录入格式问题，我自己设置的歌词习惯于在歌曲主旋律和副歌之间插入空行，这个在PC端的音乐播放器只需在歌词录入时在两行歌词中加入无内容的歌词行就好，如：

txt编辑状态：
[xx:xx.xx]Hello, world！
你好，世界！
[xx:xx+1.xx]
[xx:xx+2.xx]Goodbye, world!
再见，世界

PC显示端显示状态：
Hello, world！
你好，世界！

Goodbye, world!
再见，世界

但是椒盐音乐播放器却无法显示我编辑歌词文本时特意不添加内容的时间轴空行，请问系统功能的后续更新能否满足这个需求？如果可以能否在教程中也添加相关的歌词格式录入指导？或者说现版本的播放器能够满足我的要求，但我并没有试出来如何实现？

椒盐音乐是我无意间搜索到的播放器，作为第三方软件很简洁，我很喜欢，我想我会继续使用下去。综上所述，无论如何还请提供解决方案，谢谢，我也会继续支持椒盐音乐。

**Comment by Moriafly** [comment]
已在 Lyrics UI 3 初步完成

**Comment by Lost-Voice** [comment]
用上了，效果很棒，谢谢！
