### ISSUE TITLE
在车机上1.4缩放还是有点小，可否上限再设置大一点

### ISSUE THREAD

**Issue by oozzbb** [Moriafly/SaltPlayerSource#526]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

<在此输入你的建议 Enter your suggestions here>

首先非常感谢大佬开发出如此优秀强大的软件！目前用的是8.4beta2版本，在车机上1.4缩放还是有点小，可否上限再设置大一点如2.0，3.0。还有可否在左侧导航位置（歌曲上面）添加一个返回桌面的按钮（参数控制，有需要的可以打开），因为在车机上设置应用全屏（通过命令隐藏车机系统左侧导航栏）后无法返回桌面。其他都非常完美，谢谢！

以下截图供大佬参考
![微信图片_20230305232534](https://user-images.githubusercontent.com/5475510/222969719-8de3c02f-4c78-424d-b9d4-a2665e61b9d5.jpg)
![微信图片_20230305232541](https://user-images.githubusercontent.com/5475510/222969731-333231f2-7298-4a08-9f7c-c49150ce8cca.jpg)

以下为车机参数

![0000](https://user-images.githubusercontent.com/5475510/222969916-efc16f8a-7f12-4ebf-95b3-138653e74f09.png)

![1111](https://user-images.githubusercontent.com/5475510/222969929-ba80688b-d783-4e38-87ac-ef5ab0e6c2cd.png)

**Comment by Moriafly** [comment]
你好，感谢反馈我会尽快和团队沟通开发。

**Comment by Moriafly** [comment]
最新版本提供了最大 1.8 倍放大
