### ISSUE TITLE
歌词页面全屏显示模式

### ISSUE THREAD

**Issue by amokiel** [Moriafly/SaltPlayerSource#527]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

<在此输入你的建议 Enter your suggestions here>
目前的沉浸模式只显示了一小部分歌词，希望可以出个歌词全屏模式，开启之后歌词页面上中下三个部分都有歌词，希望可以考虑增强歌词页面这部分内容。其它部分都很满意，歌词页面这是个人最期望增强的部分。在此感谢您的辛苦工作，辛苦了，多谢！希望可以考虑一下歌词全屏显示功能，真的特别需要这个功能，由衷感谢！

**Comment by Moriafly** [comment]
你好，感谢反馈，团队会尽快推出
