### ISSUE TITLE
歌单能否作为文件保存从而在不同设备的椒盐音乐中导入导出？

### ISSUE THREAD

**Issue by MZZZ-T** [Moriafly/SaltPlayerSource#535]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

<在此输入你的建议 Enter your suggestions here>
        如主题，能不能根据歌单内的歌名（文件名）或者歌曲的别的可以识别的数据，来根据单个歌单创建歌单文件，从而实现在不同设备上导入或者导出歌单？这对于频繁更换播放设备，或者想分享歌单给好友的人来说很有用。

**Comment by motian16** [comment]
+1，以前花老长时间编辑的一个歌单，重装后全没了

**Comment by Moriafly** [comment]
此功能已在排期中，等待团队后续更新

**Comment by Moriafly** [comment]
#365
