### ISSUE TITLE
增加对有卡拉OK时间轴歌词的支持

### ISSUE THREAD

**Issue by 1oschi** [Moriafly/SaltPlayerSource#542]
读取带卡拉OK时间轴的歌词文件时，卡拉OK时间轴会被作为歌词内容显示（如下图），希望能将它过滤掉不显示出来！

![椒盐](https://user-images.githubusercontent.com/79851699/227600612-5e8c29c9-7788-4d2a-a8d8-e9cde8f00c3d.jpg)

**Comment by wdubaiyu** [comment]
合并时间戳的歌词也有问题
![68E5C0F76A9B969B70779E2B3A960D01](https://user-images.githubusercontent.com/9440981/229976316-9948e143-603d-4aa7-8cd2-b98f9dea6a9a.jpg)

**Comment by Moriafly** [comment]
#764 此反馈比较完整，所以转到此反馈
