### ISSUE TITLE
超过100分钟的lrc歌词无法被完整加载

### ISSUE THREAD

**Issue by xixiaxixi** [Moriafly/SaltPlayerSource#552]
#### 基本信息 The basic information

软件版本 Software version：8.6.0  以及8.3.2
系统版本 System version：miui14

#### 反馈内容 Content of the feedback

如题。还是我，日文音声很长，超过100分钟，发现歌词是正好断在100分钟的。

可能是格式字符串[hh:mm:ss]限定了长度导致100分钟后[hhh:mm:ss]格式不匹配读取错误。

复现的话，音声成人向不太好资源直接放这。烦请作者大大自己测一下

**Comment by Moriafly** [comment]
8.15.0 修复❤️
