### ISSUE TITLE
安卓车机界面显示不全，左面被遮挡

### ISSUE THREAD

**Issue by syolemon** [Moriafly/SaltPlayerSource#556]
![9f45183c0785041a01d0cedd4d5bb1a](https://user-images.githubusercontent.com/51316760/230848926-9b3a4bde-0d43-4d55-8f74-6bcf20823a11.jpg)
![7e1cd480355fdcb527db9bef42cf15d](https://user-images.githubusercontent.com/51316760/230848943-62150fd0-11a1-45d2-971b-37b510eb4397.jpg)
#### 基本信息 The basic information

软件版本 Software version：8.6.0-beta03(2023033101)
系统版本 System version：别克安卓中控，安卓9

#### 反馈内容 Content of the feedback

左面显示不全或者界面被遮挡，详见图片。
QQ音乐显示正常、poweramp换主题也会出现显示不全或界面被遮挡、网易云音乐显示不全或界面被遮挡。
实验室放大缩小功能很好，但未能解决问题。

**Comment by luyalu** [comment]
哈哈，我长安车机也是同样的问题

**Comment by jiangyiUI** [comment]
同样的问题

**Comment by Duck-Deng** [comment]
可能是车机系统的问题？左边的栏不会是以“悬浮窗”的方式显示的吧，那样app也很难适配
