### ISSUE TITLE
狀態欄歌詞可選擇不顯示翻譯

### ISSUE THREAD

**Issue by Jason96170** [Moriafly/SaltPlayerSource#58]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

希望希望狀態欄歌詞可以讓使用者選擇在撥放外語歌時，翻譯歌詞不會與歌詞一起顯示到狀態欄中。

**Comment by Moriafly** [comment]
最新版本 4.0.2 新增【设置】-【歌词】-【状态栏歌词不显示翻译】选项（默认关闭）。❤️
