### ISSUE TITLE
从官方仓库下载的hmos专版显示被恶意篡改？

### ISSUE THREAD

**Issue by Pennages** [Moriafly/SaltPlayerSource#580]
#### 基本信息 The basic information

软件版本 Software version： 8.8.0-hmos
系统版本 System version：Android13(OneUI5.1)

#### 反馈内容 Content of the feedback

下载hmos专版显示被恶意篡改。实际上是通过官方仓库下载的。并没有对应用做出任何修改。
或者说这个应用不支持鸿蒙以外的系统启动么？😭
只是想一部手机使用多个椒盐音乐而已😭😭
![Screenshot_20230522_232844_Salt Player](https://github.com/Moriafly/SaltPlayerSource/assets/38871500/eba8fe2d-511c-4d45-a504-39b2c669ccfe)

**Comment by Moriafly** [comment]
可以试试糖醋音乐（

**Comment by FeiLZX3Km** [comment]
> 可以试试糖醋音乐（

在华为应用商店看到一个糖醋音乐，差点以为是第三方盗版上架华为市场，我还专门跑到这里想提醒一下，看到这回复才知道原来是开发者自己改的。
