### ISSUE TITLE
V3重复混响BUG

### ISSUE THREAD

**Issue by minewhn** [Moriafly/SaltPlayerSource#59]
椒盐音乐版本：4.0.1（江月年年望相似）
Android 7.1.1
ColorOS 5.1.1
问题：打开V3 reverb混响后转动屏幕切换横竖屏模式混响开关自动重置为关，但音乐仍在混响，再次打开便会混响两次

**Comment by Moriafly** [comment]
已在最新 4.0.2 版本修复❤️
