### ISSUE TITLE
求支持车机方向盘切歌

### ISSUE THREAD

**Issue by lfeng1420** [Moriafly/SaltPlayerSource#599]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

椒盐音乐灰常好用，感谢作者大佬的辛苦开发😘如果可以的话，求支持一下车机方向盘切歌（上一曲/下一曲）

**Comment by lanpingdegai** [comment]
你车机自带的能方控么？    自带的都不能的话自己去买协议盒匹配去

**Comment by lfeng1420** [comment]
> 你车机自带的能方控么？ 自带的都不能的话自己去买协议盒匹配去

自带的是可以的。已用另一种方式实现了
