### ISSUE TITLE
自定义排序bug

### ISSUE THREAD

**Issue by N-0012** [Moriafly/SaltPlayerSource#607]
bug：自定义排序在拖拽歌曲到屏幕当前显示的曲目范围之上时会被打断拖拽，不能像向下拖拽一样一直下滑到目标位置。

**Comment by N-0012** [comment]
bug细节补充：
    1）列表前两三首歌 (某些版本其他位置也会) 拖拽其先向上移再向下移动时，会突然快速下跳而不是徐徐向下滚动；
    2）列表其他位置的歌曲，向上拖动到当前显示的曲目最上方时，拖动会被打断。

拖拽排序的 bug 一直没有被修复，在最新的 10.0.0-beta04 版本中依然存在，希望可以尽快修复，真的很需要这个功能。
感谢软件的开发者，这款APP的功能非常符合我的需求，唯一的缺憾就是这个bug了。

设备：Realme GT Neo2
系统：Realme UI 4.0 F.04  安卓13

**Comment by Moriafly** [comment]
10.5.0-alpha02 修复
