### ISSUE TITLE
椒盐音乐现版本(8.12.0)中专辑封面显示模糊

### ISSUE THREAD

**Issue by mingqiannailv** [Moriafly/SaltPlayerSource#611]
和椒盐音乐Lite（或其他同类型软件比），椒盐音乐现版本专辑列表中显示图片模糊，但在歌曲播放页面显示正常
![Screenshot_2023-07-08-13-48-23-609_com salt music](https://github.com/Moriafly/SaltPlayerSource/assets/110336013/fdc95cc5-71c8-4e43-9f69-c373505e7a4e)
当前椒盐音乐版本
![Screenshot_2023-07-08-13-51-10-838_com salt music](https://github.com/Moriafly/SaltPlayerSource/assets/110336013/d034abfa-926f-4505-a76d-cf7627563ee5)
椒盐音乐专辑页
![Screenshot_2023-07-08-13-51-21-614_com salt music lite](https://github.com/Moriafly/SaltPlayerSource/assets/110336013/7d64779a-758f-4142-aaa4-888202f1bb8c)
椒盐音乐Lite专辑页
![Screenshot_2023-07-08-13-52-43-594_com salt music](https://github.com/Moriafly/SaltPlayerSource/assets/110336013/967c5579-eac4-43f2-b923-976969c79ecc)
椒盐音乐播放页
![Screenshot_2023-07-08-13-52-35-751_com salt music lite](https://github.com/Moriafly/SaltPlayerSource/assets/110336013/252697f1-b00d-496d-a1d1-b89c4380407f)
椒盐音乐Lite播放页

**Comment by Moriafly** [comment]
已在8.13修复
