### ISSUE TITLE
APP无法扫描到音乐文件，使用自定义文件夹出现异常。

### ISSUE THREAD

**Issue by kenus** [Moriafly/SaltPlayerSource#641]
/仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：8.16.0-beta01-2023092102
系统版本 System version：安卓12

#### 反馈内容 Content of the feedback
安装完APP后，点击扫描，无法获取内部存储上的MP3文件。使用自定义文件夹功能，提示：Can not start DocumentsUI。我试过从8.15至8.16的几个版本，均出现这种情况。我很清楚记得，以前使用旧版本的椒盐音乐，是没有这种情况。

<在此输入你遇到的问题，必填 Enter the problem you encountered here. Required>
![微信图片_20230925150115](https://github.com/Moriafly/SaltPlayerSource/assets/936884/f9d1ecdf-6118-4bba-8127-c2f91d27aed6)

**Comment by nbxuhao** [comment]
+1，鸿蒙 3.0 鸿蒙版本，重启系统之后才可以扫到新的音乐
