### ISSUE TITLE
Lyrics finder option and tag editor

### ISSUE THREAD

**Issue by a1x007** [Moriafly/SaltPlayerSource#651]
Hello, i'm using your app and it's really really good looking music player. I'm loving this but it would be great if you could add music lyrics finder option so that using the song name the app could automatically generate lyrics for the song and also if you could add tag editor.  There's an option for lyrics it says source for lyrics - not found. I don't know how this works.
Overall its the best app ❤️

**Comment by Moriafly** [comment]
Hi, download this zip file and rename to .apk file ext.
[musictag.apk.zip](https://github.com/Moriafly/SaltPlayerSource/files/12837486/musictag.apk.zip)
