### ISSUE TITLE
长音频识别不了

### ISSUE THREAD

**Issue by sherlcok314159** [Moriafly/SaltPlayerSource#657]
我有些音频是有 30min 这种长度，我一般喜欢下些博客来听，但是扫描的时候会被过滤掉

软件：最新版
系统：华为P40, 鸿蒙3

**Comment by Moriafly** [comment]
你好，可以提供下音频文件吗？

**Comment by sherlcok314159** [comment]
链接在这里：https://send.vis.ee/download/2df942487720af71/#7RN0hF493c2KqqUUcTotUg，其他人请勿下载，这是一次性的

**Comment by Moriafly** [comment]
你好，抱歉我到现在才点击，显示此链接已经过期，可以再次提供下吗

**Comment by sherlcok314159** [comment]
你可以点击[这里](https://send.vis.ee/download/7b89c199f45c2bf8/#0hpuTalOSgVviCI31aQB6w)，这个链接是三天有效期

**Comment by Moriafly** [comment]
> 你可以点击[这里](https://send.vis.ee/download/7b89c199f45c2bf8/#0hpuTalOSgVviCI31aQB6w)，这个链接是三天有效期

您好我似乎无法下载它

**Comment by Moriafly** [comment]
您好，我这边使用自定义文件夹扫描可以读取到此文件

**Comment by sherlcok314159** [comment]
十分感谢作者！自定义文件夹的确可以，可是目前听着不对劲，是什么原因呢

**Comment by Moriafly** [comment]
您好，听着不对劲是指？
