### ISSUE TITLE
不能正确识别带有.cue文件的整轨音频

### ISSUE THREAD

**Issue by growingtochase** [Moriafly/SaltPlayerSource#661]
#### 基本信息 The basic information

软件版本 Software version：8.16.2(2023100801)
系统版本 System version：Harmony OS 3.0.0.301 (matepad 11 2021)

#### 反馈内容 Content of the feedback

在扫描整轨歌曲时，扫描到的是一个flac文件，不能像海贝音乐那样将整轨音乐通过同文件夹下的.cue文件进行自动分轨，且无法读取封面。如下图所示。

1. 图一 椒盐音乐不能自动对整轨文件分轨

![Screenshot_20231014_130656](https://github.com/Moriafly/SaltPlayerSource/assets/110030376/73a659e2-15cf-4d57-ae50-7c90dba87a37)

2. 图二 相同文件，海贝音乐可以正常分轨

![Screenshot_20231014_130921](https://github.com/Moriafly/SaltPlayerSource/assets/110030376/0bdb94d5-3587-42be-89c0-cf33a868821f)

3. 图三 整轨文件示意

![Screenshot_20231014_131101_com huawei filemanager_edit_58121914992723](https://github.com/Moriafly/SaltPlayerSource/assets/110030376/e42fb2b1-ae34-4bd4-9d0b-7c7799042e0e)

**Comment by Moriafly** [comment]
感谢反馈
#231

**Comment by nightson** [comment]
啊？为什么直接划入not planned了，这个需求还是很常见的啊
