### ISSUE TITLE
flac 格式的音乐都没有封面图和歌词，是支持不好吗？

### ISSUE THREAD

**Issue by Joeycz** [Moriafly/SaltPlayerSource#684]

**Comment by FeiLZX3Km** [comment]
我2000+本地flac音乐均可显示专辑、歌词。我认为问题出在你的音乐文件上，建议排查。可以使用[音乐标签 - 自动将音乐标题、演唱者、封面图、歌词、专辑名添加到音乐文件内，支持 QQ、网易云、iTunes 信息源[Android/Windows] - 小众软件](https://www.appinn.com/music-tag-editor-windows-and-android/)来添加标签及歌词。
