### ISSUE TITLE
无法识别文件时自动跳过

### ISSUE THREAD

**Issue by lx1001** [Moriafly/SaltPlayerSource#69]
反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

<在此输入你的建议 Enter your suggestions here>

在使用过程中经常发现程序会自动暂停，发现是音乐文件的编码格式无法识别，程序自动停止播放了。
联系增加一个：如果该音乐无法播放，则跳过该首音乐，自动播放下一首的功能。或者，增加一个筛选功能，剔除列表中无法识别的音乐。

**Comment by Moriafly** [comment]
8.2.0-beta02 新增错误逻辑
