### ISSUE TITLE
可否在车机模式下，增加一个返回桌面的按钮。

### ISSUE THREAD

**Issue by qdpatriotcn** [Moriafly/SaltPlayerSource#708]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

<因为车机没有实体的返回键，自己通过adb让椒盐全屏运行了，要想返回系统桌面，只能点椒盐的退出按钮，所以想能不能加一个返回桌面的按钮，可以后台播放。感谢作者。>
![Screenshot_20231207-142117_Salt Player](https://github.com/Moriafly/SaltPlayerSource/assets/105200583/78604fdb-9924-4391-a2a8-6a5e268d2ea5)

**Comment by Moriafly** [comment]
感谢反馈，会关注此问题，留意后续更新。

**Comment by qdpatriotcn** [comment]
> 感谢反馈，会关注此问题，留意后续更新。

谢谢，已经在新版上找到了。辛苦辛苦。

真心希望能够在车机上稳定，流畅。现在就是稍微卡顿，而且还会播放一阵，就退出。很随机的。不知道有没有什么办法能提供日志之类的。帮助解决这种问题。现在只能用musciolet ,很稳定和流畅。只是操作界面实在是太简陋。
