### ISSUE TITLE
能否增加应用自定义字体功能

### ISSUE THREAD

**Issue by PumpkinJui** [Moriafly/SaltPlayerSource#711]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

如题。
指的是用户手动选择一个 TTF/OTF 字体文件，用于软件全局，包括桌面歌词等等。
同时也可以考虑内置一款字体，个人推荐霞鹜文楷的变体 [LxgwBrightGB](https://github.com/lxgw/LxgwBright)。
具体功能可以参考「纯纯写作」、「一叶日历」等应用。
![纯纯写作](https://github.com/Moriafly/SaltPlayerSource/assets/76104432/53c228e4-f4a0-4b40-8bbd-528e5f1fb28b)
![一叶日历](https://github.com/Moriafly/SaltPlayerSource/assets/76104432/960ab7d9-7cd2-4844-ac6e-25c25d34a3e4)

**Comment by Moriafly** [comment]
软件字体跟随系统，对于本软件字体似乎不是重要的关注点。感谢您的建议。
