### ISSUE TITLE
歌词显示建议

### ISSUE THREAD

**Issue by EscapeCar** [Moriafly/SaltPlayerSource#722]
![Screenshot_20231222_182526_com jio media jiobeats](https://github.com/Moriafly/SaltPlayerSource/assets/151177337/7d01548f-ad01-4482-8e30-08bf7d0ec4d6)
建议在当前演唱中的歌词翻译显示为暗色，与正在演唱的白色歌词区分开来，(例图二)
![Uploading Screenshot_20231222_182948_com.jio.media.jiobeats.jpg…]()
如[卡拉OK歌词]功能一样，播放当前歌词时，不会让翻译歌词也显示同样的颜色

**Comment by EscapeCar** [comment]
![Screenshot_20231222_182948_com jio media jiobeats](https://github.com/Moriafly/SaltPlayerSource/assets/151177337/6d2c7049-482d-4fab-bbe3-8ec390fcad3e)
图二补充

**Comment by Moriafly** [comment]
已完成
