### ISSUE TITLE
支持LRC格式的卡拉ok歌词

### ISSUE THREAD

**Issue by bingaha** [Moriafly/SaltPlayerSource#726]
椒盐歌词10.0.0-beta03版本歌词截图
![2ecf38787f151e14eb02f3d4b55cd723_720](https://github.com/Moriafly/SaltPlayerSource/assets/37445781/564d959c-12ff-4bf5-9770-b2516421bc98)

aimp截图
![85ec5651cf84dfdda4b3f7372514a8ef](https://github.com/Moriafly/SaltPlayerSource/assets/37445781/68d640b6-80d9-476a-91e0-b1a937882152)

因为我电脑版的音乐文件都是内嵌的卡拉ok歌词。所以希望手机版也能支持这些歌词的显示。
可以不用按照卡拉ok去一个字一个字去对，在显示的时候如果能把句中的时间戳隐藏掉就挺好了

**Comment by Moriafly** [comment]
#764 此反馈比较完整，所以转到此反馈

**Comment by eehu** [comment]
这个问题到最新版都没解决,希望能解决,我的也都是内嵌的动态歌词.谢谢.
