### ISSUE TITLE
播放界面有些歌曲的专辑封面非常糊

### ISSUE THREAD

**Issue by xtronx** [Moriafly/SaltPlayerSource#74]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：4.4.0 (2021101601)
系统版本 System version：8.1.0 原生 / 11.0 (One UI 3.1)

#### 反馈内容 Content of the feedback

<在此输入你遇到的问题，必填 Enter the problem you encountered here. Required>
如题，我第一次碰到这个问题的时候是在一个屏幕分辨率不常见的手机上面碰到的，当时觉得可能和屏幕分辨率有关系就换了三星Tab S7平板，但还是有这个问题。
我的音乐文件封面大多数都是1000X1000以上的，少数最高4000X4000，但是感觉好像和内嵌封面分辨率没关系？

以下为1620x1080的屏幕上显示的效果。可以察觉封面糊掉了，但是本身屏幕小，问题不那么突出。
![Screenshot_20211024-195949](https://user-images.githubusercontent.com/12118006/138593107-4a15b2fd-7af3-4691-8d6d-1b4eb921995d.png)
以下为2560x1600的屏幕上显示的效果。封面糊掉了（超明显的锯齿），因为是在平板上面导致非常辣眼睛。
![Screenshot_20211024-200252](https://user-images.githubusercontent.com/12118006/138593202-64cf4516-f187-446b-a01e-fd9573aa2d87.png)

**Comment by Moriafly** [comment]
Fixed, https://github.com/Moriafly/SaltPlayerSource/releases/tag/4.6.0 .
