### ISSUE TITLE
增加文件夹结构显示方式

### ISSUE THREAD

**Issue by avadasafc** [Moriafly/SaltPlayerSource#750]
目前，通过椒盐音乐侧栏的文件夹选项进行浏览时，若文件夹A中包含了子文件夹B和歌曲①，文件夹B中包括歌曲②。则会将文件夹A和B同时显示，
希望能增加“按文件夹的层级，分层显示”的功能，即当我在app内浏览时点击文件夹A看到子文件夹B和歌曲①，然后点击子文件夹B看到歌曲②

**Comment by avadasafc** [comment]
原来已经有这功能了，对不起😣一开始没看到

**Comment by ZsOg** [comment]
那最好关掉issue吧🤔🤔🤔
