### ISSUE TITLE
支持两手歌曲之间无缝衔接（不要停顿）

### ISSUE THREAD

**Issue by rogerwang2008** [Moriafly/SaltPlayerSource#755]
#### 建议内容 The proposals

部分专辑中每首歌曲之间是连续的（古典音乐尤为常见）。目前播放器在连续播放时，两曲之间会有短暂停顿，有时会影响体验，希望支持连续播放的两首歌曲之间完全连续播放，不要有间隙。

**Comment by Moriafly** [comment]
#183
