### ISSUE TITLE
开发者你好，我在开发一款xp模块，将软件歌词显示在状态栏上。我想适配本音乐软件，能提供点支持吗，这对我帮助很大

### ISSUE THREAD

**Issue by xiaowine** [Moriafly/SaltPlayerSource#76]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals
开发者你好，我在开发一款xp模块，将软件歌词显示在状态栏上。我想适配本音乐软件，能提供点支持吗，这对我帮助很大

**Comment by xiaowine** [comment]
> 完成适配，https://github.com/Moriafly/SaltPlayerSource/releases/tag/4.5.0 ，不过我未测试

亲，貌似你icon传错了

**Comment by xiaowine** [comment]
> 完成适配，https://github.com/Moriafly/SaltPlayerSource/releases/tag/4.5.0 ，不过我未测试



> > 完成适配，https://github.com/Moriafly/SaltPlayerSource/releases/tag/4.5.0 ，不过我未测试
> 
> 亲，貌似你icon传错了



> 完成适配，https://github.com/Moriafly/SaltPlayerSource/releases/tag/4.5.0 ，不过我未测试

icon只传
iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACRElEQVRYhe2Xu4sUQRCHv5o59Q45PAVFxUQvUDEQFBQDEQM1MzIw8V/R2D/ASAMTExETwUxBA08wEEwNFHy/z/djZ7qkekt2mZl9zNzcgbC/pdmlt7vr6+7qqm6hT6o5TaRACCqqzIlwUuBMCLozKB9ALopwRYTFVVNTpdHLNfU1B6wDEv+9A2EeZJsI64F5EbYD74DnbQPMAMeBI4Ct5mpgl8CGJIn/TyscVo2AZvzc0NFsC8YsqWo+q5ofUM2vB801yzPtZJlmIVfVWIKVPHTrO1n2ospm0xXYBJwADgH7bOqJCCogPa+SQp+ZNgG2AKeA/cDGaE0qrWpf1c82AaaBrcDm/srilAsglQBJQ4Bf7tU/avSptNUUAJ/VkrUUgFY0AZgATACaAsjwwPcfARRzwUFgDfC7UG+gdl16BTwDvgLfa0bDyrZFgLPArBvoVwp0gNvAZQe0fBDGNC4+xkiAY964ilYd7jHw2a9fo7YwZmlvtHYQWc+C5qOW9CPw0Ge/19Px0JSu2ptOkqYlv6kLUFuqEfqTbVuSpHuK/du4FQ+UavSRe8AtX72Slg1Ao8xZ5b4Il4A/KwKg9unuu2i8iGqKRp/JVgSgCxHd7hvwBHjdBSkd7eUD8LviAnDTvyuXvwog+LH9dxrqhFv1HUhQ3gA3gKtg70MGPjqLAOf9nbcbOFrD+BfgAfDIo+Rb4A7wflS0LAJc8Ah3uiaAhdm7wDU/bjZjgxoZV4oA9n5bBJ4CL/3xMY4sSVkf629hejwBfwErbeElKU4e2AAAAABJRU5ErkJggg==

**Comment by Moriafly** [comment]
好的❤️

**Comment by xiaowine** [comment]
> 好的❤️

除了图标问题以外，一切正常，我已测试。

**Comment by Moriafly** [comment]
已经更新 rc-02 版本，https://github.com/Moriafly/SaltPlayerSource/releases/tag/4.5.0 ❤️

**Comment by Moriafly** [comment]
> > 好的❤️
> 
> 除了图标问题以外，一切正常，我已测试。

是否可以支持不传图标的方式？

**Comment by Moriafly** [comment]
好的
