### ISSUE TITLE
适配逐字增强型 LRC 歌词格式

### ISSUE THREAD

**Issue by MianSoft** [Moriafly/SaltPlayerSource#764]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

是否考虑适配逐字歌词？
已知主流格式有
增强型 LRC (https://en.m.wikipedia.org/wiki/LRC_(file_format))
ESLyric (现在用的也是增强型 LRC，旧版格式见https://github.com/ESLyric/feedback/issues/51)
TTML (https://help.apple.com/itc/videoaudioassetguide/#/itcd7579a252)
YRC (https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%e8%8e%b7%e5%8f%96%e9%80%90%e5%ad%97%e6%ad%8c%e8%af%8d)
QRC (QQ 音乐私有格式，能搜到的解密/转换工具只有https://gitee.com/ying32/MakeLyric)
个人认为只需支持 TTML 和增强型 LRC 就行了
~其他格式都该被历史淘汰 (暴论)~
顺便附几个链接
https://github.com/Steve-xmh/applemusic-like-lyrics/tree/dev/packages/lyric
https://github.com/Steve-xmh/amll-ttml-tool

**Comment by Moriafly** [comment]
这样的卡拉 OK 歌词格式（增强型）存在非常多种变体，会在近期统计格式并进行工作。暂无对 TTML 的支持计划，此歌词来源已经使用用户极低。

**Comment by Moriafly** [comment]
#888 #761 重复时间戳

**Comment by Moriafly** [comment]
重复时间戳已完成

**Comment by Moriafly** [comment]
不计划适配任何第三方格式，将在后续版本仅提供对增强型 LRC 支持

**Comment by bingaha** [comment]
希望能适配增强型LRC

**Comment by Moriafly** [comment]
10.7.0-alpha02 完成
