### ISSUE TITLE
DSD文件疑似无法正确读取音乐标签

### ISSUE THREAD

**Issue by yemijun** [Moriafly/SaltPlayerSource#766]
#### 基本信息 The basic information

软件版本 Software version：10.0.2
系统版本 System version：Android 14
机型：vivo X90s

#### 反馈内容 Content of the feedback
DSD文件无法正确读取音乐标签。在音乐标签APP中可以正常读取，播放时不显示。
![Screenshot_20240212_001339](https://github.com/Moriafly/SaltPlayerSource/assets/67429927/9e116c98-435c-44c4-a516-42b815710b0a)
![Screenshot_20240212_001347](https://github.com/Moriafly/SaltPlayerSource/assets/67429927/7d8ae270-a9a9-45d7-bb30-9cb0b8850126)
播放文件信息：
![1000038077](https://github.com/Moriafly/SaltPlayerSource/assets/67429927/439b3986-fc8f-4920-ab63-af40dab5b1a5)
DSD512

**Comment by Ken-Parker** [comment]
我看你文件夹是`1Bit`，1位深，读取出来却是32Bit

**Comment by Moriafly** [comment]
可以提供文件吗

**Comment by yemijun** [comment]
> 可以提供文件吗

https://mypikpak.com/s/VO0QkJOOvraAw8kUGXyD1KWao1 
my share 
复制链接后打开 PikPak App，保存当前文件
