### ISSUE TITLE
音乐文件的多个艺术家识别问题

### ISSUE THREAD

**Issue by Leilei332** [Moriafly/SaltPlayerSource#771]
#### 基本信息 The basic information

软件版本 Software version：10.0.2.2024020301
系统版本 System version：Android 8.0.0

#### 反馈内容 Content of the feedback

之前下载的包含多个艺术家的音乐中的艺术家元数据为`Artist1、Artist2`时椒盐音乐可以正确识别。但是使用`yt-dlp`下载的音乐的多个艺术家的元数据为`Artist1 / Artist2`，此时椒盐音乐识别出的艺术家的名字前多了一个空格。

在“音乐标签”软件显示的内容：

![Screenshot_20240214-120139](https://github.com/Moriafly/SaltPlayerSource/assets/70204468/48d8b11e-db39-452d-ba48-d8c9ae44ba5b)

椒盐音乐识别错误（Leo Abrahams和Jon Hopkins前面多了空格）：

![Screenshot_20240214-120109](https://github.com/Moriafly/SaltPlayerSource/assets/70204468/3204066a-07ad-4b9e-af94-21d0211095ae)

**Comment by Ken-Parker** [comment]
因为你艺术家标签写的是`Artist1 / Artist 2`，`/`左右多了两个空格，正常应该是写作`Artist 1/Artist 2`吧

**Comment by Moriafly** [comment]
10.3.0-beta01 已修复
