### ISSUE TITLE
使用大于6M的png图片做flac专辑的封面时，在专辑列表无法正常显示

### ISSUE THREAD

**Issue by ahbksdmz** [Moriafly/SaltPlayerSource#776]
### 基本信息 The basic information

软件版本 Software version：10.1.0
系统版本 System version：xiaomi HyerOS 1.0.4.0

#### 反馈内容 Content of the feedback

使用大于6M的png图片做flac专辑的封面时，在专辑列表无法正常显示封面，但是点击播放时可以正常显示封面。

**Comment by Moriafly** [comment]
10.6.0-beta03 修复
