### ISSUE TITLE
跪求对Subsonic以及webdav等的支持

### ISSUE THREAD

**Issue by ametoyuki098** [Moriafly/SaltPlayerSource#780]
是的。如果椒盐音乐能支持Subsonic，那椒盐可能是我手机上唯一一个播放音乐的软件了。在某知名音乐客户端广告满天飞的情况下，自建音乐服务或使用访问webdav。 添加对Subsonic的支持非常有必要。
辛苦开发者早日实现这个请求。谢谢！

**Comment by Nick-DL** [comment]
青盐云听适配了WebDAV，这是椒盐音乐的另一个分支，现在还在内测

**Comment by Tzz-halo** [comment]
> 青盐云听适配了WebDAV，这是椒盐音乐的另一个分支，现在还在内测

我可以在什么地方下载并体验到 青盐云听吗？

**Comment by shellus** [comment]
建议改为syncthing同步，同步方案比实时云盘（webdav、samba之类）方案更可靠，更快

**Comment by Moriafly** [comment]
#117
