### ISSUE TITLE
鸿蒙 4 新特性 4.0.0.200 版本 音乐控制中心不适配

### ISSUE THREAD

**Issue by Colour1205** [Moriafly/SaltPlayerSource#787]
#### 基本信息 The basic information

软件版本 Software version：10.0.0-beta02-hmos
系统版本 System version：4.0.0.200

#### 反馈内容 Content of the feedback

更新到鸿蒙 4 beta 4.0.0.200 鸿蒙版 Salt player 音乐控制中心显示不了了

**Comment by Moriafly** [comment]
#757
