### ISSUE TITLE
建议首次启动 Salt Player 时展示使用指南

### ISSUE THREAD

**Issue by Nick-DL** [Moriafly/SaltPlayerSource#798]
反馈区偶尔会出现一些比较浅显的问题，比如怎么扫描音乐，怎么给音频适配歌词、专辑封面，hmos版下载渠道等，还有很多细碎的用法可以直接告诉用户，所以可以在第一次打开时展示开屏指南。

**Comment by Moriafly** [comment]
软件致力于将学习成本降低，会在后续持续改进操作
