### ISSUE TITLE
在播放有歌词的歌时应用崩溃

### ISSUE THREAD

**Issue by bushishiba114** [Moriafly/SaltPlayerSource#799]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：10.2.7
系统版本 System version：类原生安卓7.1.2

#### 反馈内容 Content of the feedback

在播放有歌词的歌时崩溃
复现步骤：进入主界面-随便播放有歌词的歌
预期结果：播放出音乐
现象：应用崩溃

https://github.com/Moriafly/SaltPlayerSource/assets/161920757/6d187f91-462a-47b8-a298-443a0d531a47

**Comment by Moriafly** [comment]
您好，在最新 10.2.10.1 中还存在此问题吗？
