### ISSUE TITLE
英文和中文混合歌词显示

### ISSUE THREAD

**Issue by LVCC1596** [Moriafly/SaltPlayerSource#822]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 
歌词内嵌如下:
07:29.78]I'll never我永远不会
这样就会造成英文和中文混在一起
如果要在当下逻辑不变的情况下就会英文中文堆在一起不美观，
要优化可以手动修改为
07:29.78]I'll never
[07:29.78]我永远不会
这样就不会了，请看洋张，不过我已经准备好了Python和Java代码:
import re

def process_lyrics(lyrics):
    pattern = re.compile(r'\[(\d{2}:\d{2}\.\d{2})\](.*)')
    processed_lyrics = []

    for line in lyrics.split('\n'):
        match = pattern.match(line)
        if match:
            time_stamp = match.group(1)
            lyric = match.group(2)
            if ' ' in lyric:
                en, cn = lyric.split(' ', 1)
                processed_lyrics.append(f'[{time_stamp}]{en}')
                processed_lyrics.append(f'[{time_stamp}]{cn}')
            else:
                processed_lyrics.append(f'[{time_stamp}]{lyric}')
    
    return '\n'.join(processed_lyrics)

# 使用示例
lyrics = """
[00:16.08]I've been living on the road 我漂泊在路途上
[00:18.72]Made a buck off my soul 灵魂投进音乐生涯 用来维持生计
"""
print(process_lyrics(lyrics))

java:
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class LyricsProcessor {
    public static void main(String[] args) {
        String lyrics = "[00:16.08]I've been living on the road 我漂泊在路途上\n" +
                        "[00:18.72]Made a buck off my soul 灵魂投进音乐生涯 用来维持生计\n";

        System.out.println(processLyrics(lyrics));
    }

    public static String processLyrics(String lyrics) {
        Pattern pattern = Pattern.compile("\\[(\\d{2}:\\d{2}\\.\\d{2})\\](.*)");
        Matcher matcher = pattern.matcher(lyrics);

        StringBuilder processedLyrics = new StringBuilder();

        while (matcher.find()) {
            String timeStamp = matcher.group(1);
            String lyricLine = matcher.group(2);
            if (lyricLine.contains(" ")) {
                String[] parts = lyricLine.split(" ", 2);
                processedLyrics.append("[").append(timeStamp).append("]").append(parts[0]).append("\n");
                processedLyrics.append("[").append(timeStamp).append("]").append(parts[1]).append("\n");
            } else {
                processedLyrics.append("[").append(timeStamp).append("]").append(lyricLine).append("\n");
            }
        }

        return processedLyrics.toString();
    }
}
![Screenshot_2024-05-01-00-12-48-80_e53b20ddbf74fed48fbb876ec4945b7f](https://github.com/Moriafly/SaltPlayerSource/assets/33076061/a216fd7a-8783-4c7c-939b-e238f6812b49)

![Screenshot_2024-05-01-00-13-12-95_e53b20ddbf74fed48fbb876ec4945b7f](https://github.com/Moriafly/SaltPlayerSource/assets/33076061/2f459ee0-7fe2-44fe-953b-82797c3f65c9)

**Comment by Moriafly** [comment]
这个应该由用户自行更改，歌词存在需要情况，中英文混在一起的也很常见
