### ISSUE TITLE
建议增加在线搜寻歌词的功能

### ISSUE THREAD

**Issue by YanBai233** [Moriafly/SaltPlayerSource#843]
仅仅提交一个建议。Submit just one proposal.
在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

### 一、 建议内容 The proposals

建议增加在线搜寻歌词的功能，该功能可以参考foobar2000

**该功能的使用形式**
- 第一种
 对接第三方歌词库，用户自行查找下载，自行加载歌词标签
（法律风险低，理论上只是提供了一个搜索引擎）
- 第二种
自动匹配歌词（有相同或有多个来源的歌词，需要用户自行选择），自动加载歌词标签
（有一定的法律风险，参见第二点）

### 二、版权与法律问题的规避

**建议使用github插件侧载的方式提供该额外功能**
- 设置插件接口
- 仅仅在github上传该插件
- 插件需要用户手动安装，软件上并不设置插件的下载和安装界面

**对接互联网歌词库**
- 注明歌词的上传者和听写、听译者
- 注明歌词来源
- 明确标识歌词来源于互联网搜集

**其他的方案**
- 建立用户自上传库，允许用户上传**自己搜集的**歌词到自建歌词库，并允许其他用户加载

**另外**
虽然具有一定的法律风险，但是提供歌词匹配与《歌词适配》“盗取”上传**付费乐曲**的风险程度完全不同。
目前，并没有因提供歌词文件而被起诉的版权保护案例

### 如果采纳本enhancement issue，请在必要时删除本issue，以规避法律风险

**Comment by Moriafly** [comment]
因法律风险关闭
