### ISSUE TITLE
歌单长按单曲拖动调整顺序时上下速度不一致

### ISSUE THREAD

**Issue by QingYunYo** [Moriafly/SaltPlayerSource#851]
#### 基本信息 The basic information

软件版本 Software version：<10.2.10.1-release-2024043001>
系统版本 System version：<xiaomi hyperOS 1.0.38.0.UNCCNXM>

#### 反馈内容 Content of the feedback

<歌单长按单曲拖动调整顺序时上下速度不一致，拖动向下时速度特别快，会直接到底，根本不好调整，向上时很慢，且靠近顶部排序栏时会停止调整并置于此处，总之长按拖动调整顺序操作体验有待优化，>

**Comment by whoubeizin** [comment]
该问题同样出现在歌单页面，歌单过多时也会出现这个问题

**Comment by Moriafly** [comment]
#607
