### ISSUE TITLE
歌曲播放时上一句歌词的高亮显示撤回不及时

### ISSUE THREAD

**Issue by yxxQAQ** [Moriafly/SaltPlayerSource#853]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：<10.2.10.1 2024043001>
系统版本 System version：<realme UI V3.0 RMX3560_11_A.27>

#### 反馈内容 Content of the feedback

<在此输入你遇到的问题，必填 Enter the problem you encountered here. Required> 
歌曲播放时上一句歌词的高亮显示撤回不及时
机型：<realme GT neo3>
录屏：

https://github.com/Moriafly/SaltPlayerSource/assets/122793510/ca000da6-b23d-4839-b3f9-e572bd6ec8f2

**Comment by yxxQAQ** [comment]
草 怎么把系统版本和机型给吞了 写的格式有问题吗(º﹃º )​
补一下
系统：realmeUI V3.0 RMX3560_11_A.27
机型：realme GT neo3

**Comment by Moriafly** [comment]
似乎和 #802 一样的问题，但目前我在自己设备上无法复现。
