### ISSUE TITLE
屏蔽文件夹移除按钮

### ISSUE THREAD

**Issue by xihale** [Moriafly/SaltPlayerSource#856]
![Screenshot_20240608_202519.jpg](https://github.com/Moriafly/SaltPlayerSource/assets/62087089/84e27c93-bf42-4d4f-8014-da2c3e0ec61e)

在暗色模式下，移除按钮对比度过低。

版本：10.2.10.1

**Comment by Moriafly** [comment]
10.3.0-alpha04 已修复
