### ISSUE TITLE
还不能完全绕过SRC

### ISSUE THREAD

**Issue by kun-niubi** [Moriafly/SaltPlayerSource#861]
我的MIUI13系统，用椒盐音乐播放时，只支持48kHz、96kHz、192kHz三种输出采样率，其余一律SRC。而且那三种采样率走的都是mixer，而不是direct或offload。望解决SRC问题。

**Comment by Moriafly** [comment]
具体的音频策略和系统相关，先系统的重采样并不差，用户应该无法感知区别
