### ISSUE TITLE
歌名和专辑等都识别为kuwo,无法搜索

### ISSUE THREAD

**Issue by hexw** [Moriafly/SaltPlayerSource#865]
#### 基本信息 The basic information

软件版本 Software version：<10.2..10.1>
系统版本 System version：<Android 12>

#### 反馈内容 Content of the feedback

歌名和专辑等都识别为kuwo,开启列表中显示歌曲文件名后
![Uploading QQ截图20240624171030.png…]()

搜索也无法搜索到

**Comment by Moriafly** [comment]
歌曲是否是在酷我平台下载？

**Comment by hexw** [comment]
> 歌曲是否是在酷我平台下载？

应该是的,从其他渠道下载的,源应该是酷我

**Comment by Moriafly** [comment]
此平台一般将元数据写入 Kuwo，需要自行编辑元数据，如使用音乐标签 App

**Comment by hexw** [comment]
> 此平台一般将元数据写入 Kuwo，需要自行编辑元数据，如使用音乐标签 App

但是文件名是正常的,按文件名搜索不行
