### ISSUE TITLE
优先使用同目录下的lrc文件作为歌词

### ISSUE THREAD

**Issue by Lyif233** [Moriafly/SaltPlayerSource#866]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

我在音乐文件的同目录下放置了lrc歌词文件，但是Salt Player总是优先读取Embedded歌词
希望在设置中增添“优先使用lrc文件”的选项

**Comment by gtianw** [comment]
reopen
