### ISSUE TITLE
无歌词音乐/纯音乐歌词显示有误

### ISSUE THREAD

**Issue by Lyif233** [Moriafly/SaltPlayerSource#867]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：10.2.10
系统版本 System version：Android 13

#### 反馈内容 Content of the feedback

![Screenshot_20240626_065806](https://github.com/Moriafly/SaltPlayerSource/assets/150530146/e59f25d7-6823-4a87-85dd-554b22bfb22a)
如图，播放没有歌词的音乐时歌词显示不正确
是否可以做到“删去前面的时间戳”或“不显示歌词”？

**Comment by Moriafly** [comment]
此时间戳不太符合写法，标识应该为**分钟:秒.毫秒**，秒和毫秒间的符号应该是.而不是:
