### ISSUE TITLE
通过备份/导入歌单功能实现PC和移动端同步，椒盐音乐导入功能出现问题

### ISSUE THREAD

**Issue by Lanmer** [Moriafly/SaltPlayerSource#878]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：10.2.8
系统版本 System version：安卓14

#### 反馈内容 Content of the feedback

<在此输入你遇到的问题，必填 Enter the problem you encountered here. Required>
通过备份导出来歌单后，在windows10系统中，仅通过原文本复制粘贴功能，不做任何修改，到一个新的txt文件中，就只能导入最后一首了。通过在线文本对比工具对比也为发现不同，但是导入仅能导入最后一首。附件中“喜欢.txt”为椒盐音乐导出原始歌单 "11.txt"为复制粘贴，未做任何修改的新建txt歌单备份文件
[喜欢.txt](https://github.com/user-attachments/files/16101224/default.txt)
[11.txt](https://github.com/user-attachments/files/16101225/11.txt)

**Comment by Lanmer** [comment]
是否是因为txt文件结构不同，椒盐无法支持windows创建的txt文件，我通过使用椒盐创建的TXT文件内容后边加入我的PC的歌单，再导入椒盐能够成功，相同的内容，windows创建的TXT文件导入就不可行。“起床啦1.txt”
为原始导出歌单中加入合并，“起床啦新建测试.txt为复制起床啦1.txt内容，粘贴至windows新建TXT”[起床啦1.txt](https://github.com/user-attachments/files/16101435/1.txt)
[起床啦新建测试.txt](https://github.com/user-attachments/files/16101444/default.txt)

**Comment by Lanmer** [comment]
> 是否是因为txt文件结构不同，椒盐无法支持windows创建的txt文件，我通过使用椒盐创建的TXT文件内容后边加入我的PC的歌单，再导入椒盐能够成功，相同的内容，windows创建的TXT文件导入就不可行。“起床啦1.txt” 为原始导出歌单中加入合并，“起床啦新建测试.txt为复制起床啦1.txt内容，粘贴至windows新建TXT”[起床啦1.txt](https://github.com/user-attachments/files/16101435/1.txt) [起床啦新建测试.txt](https://github.com/user-attachments/files/16101444/default.txt)

起床啦1正常导入，起床啦新建测试.txt，仅导入一首

**Comment by Lyif233** [comment]
> ……附件中“喜欢.txt”为椒盐音乐导出原始歌单 "11.txt"为复制粘贴，未做任何修改的新建txt歌单备份文件 [喜欢.txt](https://github.com/user-attachments/files/16101224/default.txt) [11.txt](https://github.com/user-attachments/files/16101225/11.txt)

我用MT管理器看了一下
**喜欢.txt**的md5值
`c78fae28826cb5ad14660de215c76c4a`
**11.txt**的md5值
`52ea40974fde694c955ba896551676aa`
二者均为UTF-8编码
但是是不同的文件

经16进制分析
前者的文本换行符为**LF**(\n, `0x0a`)
后者的文本换行符为**CRLF**(\r\n, `0x0d` `0x0a`)
这个应该就是只能识别到最后一首的问题所在

**Comment by Lanmer** [comment]
> > ……附件中“喜欢.txt”为椒盐音乐导出原始歌单 "11.txt"为复制粘贴，未做任何修改的新建txt歌单备份文件 [喜欢.txt](https://github.com/user-attachments/files/16101224/default.txt) [11.txt](https://github.com/user-attachments/files/16101225/11.txt)
> 
> 我用MT管理器看了一下 **喜欢.txt**的md5值 `c78fae28826cb5ad14660de215c76c4a` **11.txt**的md5值 `52ea40974fde694c955ba896551676aa` 二者均为UTF-8编码 但是是不同的文件
> 
> 经16进制分析 前者的文本换行符为**LF**(\n, `0x0a`) 后者的文本换行符为**CRLF**(\r\n, `0x0d` `0x0a`) 这个应该就是只能识别到最后一首的问题所在

确实，经过换行符替换，已经能够成功导入
