### ISSUE TITLE
关于艺术家的识别问题

### ISSUE THREAD

**Issue by helloFX** [Moriafly/SaltPlayerSource#884]
#### 建议内容 The proposals

当歌手名中有“、”时，顿号前后会被识别成两个歌手
如图：
![Screenshot_20240707_223909](https://github.com/Moriafly/SaltPlayerSource/assets/119987934/3c29cf09-68a4-4f79-89ca-6572f159b9b5)
![Screenshot_20240707_223930](https://github.com/Moriafly/SaltPlayerSource/assets/119987934/33efba08-0a40-40fa-ae79-6e3110df4a17)

因此希望改进一下艺术家的识别逻辑或是添加一个手动修改艺术家的功能

**Comment by Moriafly** [comment]
存在比较多的以 、 分割艺术家，对应使用 、 的特殊艺术家软件应该在内部继续特殊处理

**Comment by pyccl** [comment]
一个人名中会有出现顿号么？我的顿号都是几个人名分割的。
