### ISSUE TITLE
歌词显示的一个BUG

### ISSUE THREAD

**Issue by IDSSC** [Moriafly/SaltPlayerSource#898]
#### 基本信息 The basic information

软件版本 Software version：<软件版本 Software version>
10.4.0-2024071601-moriafly-arm64-v8a

系统版本 System version：<系统版本 System version>

#### 反馈内容 Content of the feedback
我有一些比较特别的歌词文件，比如局部内容是这样的，几个时间戳共用一行显示

[03:55.09][02:00.44][00:02.50]	
[02:12.87][00:18.19]赤道的边境 万里无云 天很清

以上内容歌词界面不是显示空行，而是把最后这个最尾的时间戳[00:02.50]显示上去了，希望下一版顺带修复一下啊
很优秀的软件，现在已经当平板和车机的主力音乐播放软件了，希望越来越好。

**Comment by Moriafly** [comment]
已修复
