### ISSUE TITLE
希望能够支持OriginOS"原子随身听"

### ISSUE THREAD

**Issue by Zake-arias** [Moriafly/SaltPlayerSource#901]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

##### 希望能够支持OriginOS"原子随身听"
原子随身听作为系统级的音乐控制卡片非常方便
希望能够接入：
> * 播放/暂停
> * 上一首/下一首
> * 循环模式

作为vivo用户非常希望能够加入该功能

**Comment by IDSSC** [comment]
都是意见反馈，就合并在楼下说吧
设备：
Lenovo 小新Padpro2022  ZUI15/安卓13
IQOO neo7r  OriginOS4.0/安卓14
版本：
10.4.2-2024072001-moriafly-arm64-v8a.apk)
意见反馈：
1.专辑封面目前只支持jpg/jpeg格式，png格式的无法显示，希望下一个版本支持png格式显示，heic若也能支持就好了。
2.歌词显示，MAC(CR)换行的只能显示第一行内容，后面从第二行的就不继续显示了，需要修复。
3.小新Pad在播放界面切换下一曲偶尔会出现未知情况的闪退。

**Comment by Lyif233** [comment]
OriginOS的原子随身听目前仅支持下列应用，目前未开放相关api
_此为系统原因_，需要vivo针对Salt Player主动适配，软件开发者大概率无法对此issue进行处理
![Screenshot_20240723_140228](https://github.com/user-attachments/assets/c5666937-0039-4317-9875-6ed57758e3ee)

**Comment by Moriafly** [comment]
#749
