### ISSUE TITLE
歌曲艺术家分割错误

### ISSUE THREAD

**Issue by Lyif233** [Moriafly/SaltPlayerSource#902]
#### 基本信息 The basic information

软件版本 Software version: 10.4.2
系统版本 System version：Android 13

#### 反馈内容 Content of the feedback

如图，在10.4.0版本中，歌曲艺术家标签中的顿号“、”以及斜杠“/”可对歌手进行分类
更新10.4.2版本后，顿号不再视为分隔符，同名歌手无法合并
![Screenshot_20240724_100559](https://github.com/user-attachments/assets/af1b5a11-b579-4a37-bd93-2cc1470e6bbb)

我有注意到更新公告里有这样一段文字：
>优化标题、艺术家和专辑艺术家格式化适配

猜测为版本更新内容？

希望开发者可以在Salt Player的设置-实验室中支持自定义艺术家分隔符

**Comment by Lyif233** [comment]
>如图，在10.4.0版本中……

勘误，应为10.2.10.1

**Comment by Moriafly** [comment]
需要在侧栏的“扫描音乐”中重新点击一次扫描音乐

**Comment by Lyif233** [comment]
好好好👍
这下解决了（笑）
