### ISSUE TITLE
适配小米mixflip外屏使用

### ISSUE THREAD

**Issue by feivo** [Moriafly/SaltPlayerSource#907]
希望能适配小米mixflip的外屏使用，谢谢大佬

**Comment by Moriafly** [comment]
需要开发文档，有能找到相关适配文档吗

**Comment by feivo** [comment]
https://dev.mi.com/distribute/doc/details?pId=1826

**Comment by feivo** [comment]
4.16 封面屏幕支持 ，是这个嘛

**Comment by Moriafly** [comment]
感谢，我想可能是的。请问您在使用 mix flip 吗，方便协助测试下吗

**Comment by feivo** [comment]
我在使用，可以协助测试

**Comment by Moriafly** [comment]
方便留个 QQ 吗，这儿不方便可以发送 QQ 号到邮箱 moriafly@163.com

**Comment by feivo** [comment]
好的 已发送
