### ISSUE TITLE
横屏车机模式音乐封面下歌词显示位置错误

### ISSUE THREAD

**Issue by TigGrak** [Moriafly/SaltPlayerSource#913]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：alpha05
系统版本 System version：Android13

#### 反馈内容 Content of the feedback

![Screenshot_2024-08-03-21-56-34-112_com.salt.music.jpg](https://github.com/user-attachments/assets/17dffbab-cdf0-4a9c-8124-51aa91e1ac24)

如图，横屏车机模式音乐封面下面的小歌词由于有翻译所以有两行，垂直居中显示导致两行歌词都显示不全。

**Comment by Lyif233** [comment]
此议题与 Issue https://github.com/Moriafly/SaltPlayerSource/issues/839 雷同

**Comment by TigGrak** [comment]
此议题与 Issue #839 雷同,故关闭
