### ISSUE TITLE
无损音乐半数出现类似收音机”沙沙声“，无法使用。

### ISSUE THREAD

**Issue by salewell** [Moriafly/SaltPlayerSource#921]
歌曲格式为Wav和flac，个别mp3，大小20M~200M不等，差不多半数出现歌曲在播放，但是声音全是”沙沙声“，无法使用。

poweramp播放同样音源，未出现。

手机为iqoo12，系统版本为 origin os4 (PD2307_A_14.0.20.8.w10.v0101L18)

**Comment by Moriafly** [comment]
您好，可以提供下音频文件吗

**Comment by salewell** [comment]
邮件已回复您了，刚试了5首，4首都有问题。直接给您分享所有歌单吧，
故乡、算什么男人、甜蜜蜜三首确定不行，其他没试了。用海贝、poweramp均正常播放。
通过百度网盘分享的文件：喜欢歌曲
链接:https://pan.baidu.com/s/1StDXVcDYLsBYKwiJpb_7pg?pwd=9527 
提取码:9527
复制这段内容打开「百度网盘APP 即可获取」

**Comment by Moriafly** [comment]
您好，链接似乎无法访问，可以检查下吗

**Comment by salewell** [comment]
> 您好，链接似乎无法访问，可以检查下吗

您好，这三首都不行，其他播放器正常。

通过网盘分享的文件：沙沙声
链接: https://pan.baidu.com/s/1kmgptpsUQYxpbyH5ts1O3w?pwd=ynvy 提取码: ynvy

**Comment by Moriafly** [comment]
#377

**Comment by seven3s** [comment]
是的，我也出现了，steam 版和安卓都这样
