### ISSUE TITLE
从后台切换到软件，音乐播放界面出现界面错误

### ISSUE THREAD

**Issue by MURChen** [Moriafly/SaltPlayerSource#93]
MIUI 12.5.10 稳定版 小米11
软件版本：此时相望不相闻

从后台切换到软件时（软件处于音乐封面，歌词界面）
会出现界面错误
可正常使用，且下滑可返回歌曲选择，再次进入是没有错误的
![Screenshot_2021-11-10-19-07-43-245_com salt music](https://user-images.githubusercontent.com/47627266/141106443-275bc9cf-ac4a-460d-9f81-82b3aa4165de.jpg)

**Comment by Moriafly** [comment]
感谢反馈，此问题已经定位，将在下个版本得到解决。

**Comment by Moriafly** [comment]
5.0.0-beta01 已修复
