### ISSUE TITLE
排序不识别I、II、III等罗马数字

### ISSUE THREAD

**Issue by Realzhazha** [Moriafly/SaltPlayerSource#936]
仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.

在你反馈此问题前请注意：Please note before you respond to this question:
-------------------------
- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
- 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述问题。Describe the problem as detailed as possible.
- 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
- 建议提供机型、系统版本。You are advised to provide the model and system version.

#### 基本信息 The basic information

软件版本 Software version：10.5.0-beta02
系统版本 System version: Android 14

#### 反馈内容 Content of the feedback

歌曲标题不识别I、II、III等罗马数字，导致一些古典音乐的第一乐章、第二乐章、第三乐章是倒序排序，希望可以支持识别罗马数字

**Comment by Moriafly** [comment]
无法复现此问题，是否使用了错误的罗马数字？罗马数字 2 为 Ⅱ 而非 II

**Comment by Realzhazha** [comment]
确实写成了II（两个I），但是日常中是II（两个I）更容易打字出，希望可以加入这方面的识别（Windows系统可以识别II（两个I）为罗马数字）

**Comment by Moriafly** [comment]
我理解意思了，具体的设计方案我会在近期想一想，非常感谢反馈🌹

**Comment by Moriafly** [comment]
此问题和排序规则相关，目前使用的是 0-9 数字优先，字母其次，其他字符最后

**Comment by Moriafly** [comment]
Windows 文件管理器应该是按照 ASCII 排序，所以会出现此情况，如以 I、II 这样写，具体排序和后面跟的字符有关

**Comment by Moriafly** [comment]
已找到一个兼容性方法，将测试后上线

**Comment by Moriafly** [comment]
10.6.0 已修复
