### ISSUE TITLE
多歌手分割符號希望增加「\\」

### ISSUE THREAD

**Issue by tony13382** [Moriafly/SaltPlayerSource#937]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

目前多歌手的分割符號為「/」但 mp3tag 所使用的符號為 「 \\\\ 」 希望可以增加這個符號為分隔符。

**Comment by tony13382** [comment]
编辑软件是 Mp3TAG : [mp3tag.app](mp3tag.app)

**Comment by Moriafly** [comment]
感谢反馈这边会尽快确认，如无兼容问题会尽快添加

**Comment by Moriafly** [comment]
您好，请问是在 Mac 上使用吗？我在 Win 上并未看到 \\ 符号，或者可以提供以及修改后的文件吗

**Comment by tony13382** [comment]
windows 的 mp3tag 可以手動設定成 \\ 
以下是[測試音檔](https://drive.google.com/file/d/1YxXDm5FoGuKRkKRmFG6rmMtfOin9HAzH/view?usp=drivesdk)

**Comment by Moriafly** [comment]
您好，已发送请求
![1727492298741](https://github.com/user-attachments/assets/5f541fea-819f-4c1b-8186-e9e4a85effa2)

**Comment by Moriafly** [comment]
#460 相同问题

**Comment by tony13382** [comment]
已更新權限
