### ISSUE TITLE
艺术家名字重复

### ISSUE THREAD

**Issue by JiMoDeJieFang** [Moriafly/SaltPlayerSource#944]
#### 基本信息 The basic information

软件版本 Software version：10.5.0
系统版本 System version：MIUI14.0.6

#### 反馈内容 Content of the feedback

有时候艺术家会出现两个或三个一样的名字，lite版是正常的
![1724453825064](https://github.com/user-attachments/assets/dd146162-e08f-41f3-92e1-0a056800accb)
![1724453825071](https://github.com/user-attachments/assets/56c98ff1-9f7b-4eda-a2ee-b2c3b4df5b1b)

**Comment by Moriafly** [comment]
音频格式是 FLAC 吗

**Comment by JiMoDeJieFang** [comment]
> 音频格式是 FLAC 吗

是

**Comment by Moriafly** [comment]
#460
