### ISSUE TITLE
自动旋转时播放出错

### ISSUE THREAD

**Issue by 1259412328-qq-com** [Moriafly/SaltPlayerSource#945]

**Comment by 1259412328-qq-com** [comment]
> 仅仅反馈你所遇到的一个使用问题，多个请重新提交另外的 issue。Only give feedback on one usage problem you encountered, please resubmit another issue.
> 
> ## 在你反馈此问题前请注意：Please note before you respond to this question:
> * 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).
> * 尝试在仓库 issue 搜索你要反馈的问题，避免重复反馈。Try to search for your feedback in the warehouse issue to avoid repeated feedback.
> 
> ## 反馈时候请注意：When giving feedback, please note:
> * 尽量详细的描述问题。Describe the problem as detailed as possible.
> * 提供出现此问题的椒盐音乐版本号。Provide the version number of SaltPlayer where this problem occurred.
> * 建议提供机型、系统版本。You are advised to provide the model and system version.
> 
> #### 基本信息 The basic information
> 软件版本 Software version：10.2.10 系统版本 System version：redmi K70 hyper os 1.0.17.0
> 
> #### 反馈内容 Content of the feedback
> 旋转屏幕后播放出错，切歌后恢复正常，向前切歌可以恢复正常播放，向后切歌会播放下一首，而切回来之后还能再次出现播放错误，在椒盐音乐内的基本所有页面都能稳定复现。 ![Screenshot_2024-08-24-10-19-39-636_com salt music](https://private-user-images.githubusercontent.com/98075710/361094892-6bbf6bef-80b1-4c52-b4f1-ab29b8c6079d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NjcyNDcsIm5iZiI6MTcyNDQ2Njk0NywicGF0aCI6Ii85ODA3NTcxMC8zNjEwOTQ4OTItNmJiZjZiZWYtODBiMS00YzUyLWI0ZjEtYWIyOWI4YzYwNzlkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDAyMzU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNWE3MmViOTIxYWQ2MmE2ZGI4OGQ2NzU5ZTMwMWMxMjViNGZmM2Y2YzBjZWEwODA5YTdjMTUzMDlkYjY2MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JnSGLayM1bez8QUUi8Otubtb9xeCSKIlIJZlWtQuQQA)

**Comment by 1259412328-qq-com** [comment]
抱歉抱歉，最新beta版本没这个问题了
（所以软件内的检查更新把beta版加到可选更新也挺好……）

**Comment by Moriafly** [comment]
❤️
