### ISSUE TITLE
歌词只显示第一行，需要编辑后才会正常显示

### ISSUE THREAD

**Issue by garyyeap** [Moriafly/SaltPlayerSource#958]
#### 基本信息 The basic information

软件版本 Software version：10.5.0-beta04-play
系统版本 System version：Android 14

#### 反馈内容 Content of the feedback
歌曲文件(AAC)是在 Apple music(iTune) 上编辑，同步到手机。 
所有歌曲文件的歌词只会显示第一行，在手机上编辑后才会正常显示，所谓编辑:

1.加个空格储存，内容没改。
2.把 1 加的空格删掉储存。

外部 lrc 和内嵌都试过一样，做过以上 1 或 2 后都可以正常显示，确定不是格式问题。
用超过 3 个其它 apps 都没这问题，完全正常显示。
有需要的话我可以把歌曲文件寄过去做测试，请提供方式。

![Screenshot_20240830-000539_Oto_Music](https://github.com/user-attachments/assets/57c00e65-3651-4af9-9b68-9a2ca3064949)

![Screenshot_20240830-000620_Salt_Player](https://github.com/user-attachments/assets/840f20c6-08f9-410a-a04a-350528bc51bb)

**Comment by IDSSC** [comment]
好像是非UTF-8格式只显示一行

**Comment by garyyeap** [comment]
我的情況应该是 3，所以是已知问题？没有计划解决吗？

**Comment by Moriafly** [comment]
感谢反馈，将在下个测试版本修复

**Comment by garyyeap** [comment]
@Moriafly  感谢，请问确定是换行符的问题了吗？

**Comment by Moriafly** [comment]
> @Moriafly 感谢，请问确定是换行符的问题了吗？

您好，尝试更新此版本 https://github.com/Moriafly/SaltPlayerSource/releases/tag/10.5.0-beta06，看看问题还存在吗

**Comment by Moriafly** [comment]
客气了
