### ISSUE TITLE
能不能出改DPI功能,求求了

### ISSUE THREAD

**Issue by ygsfh** [Moriafly/SaltPlayerSource#981]
仅仅提交一个建议。Submit just one proposal.

在你提交此建议前请注意：Please note before you submit this proposal:
-------------------------

- 详细阅读椒盐音乐帮助内容（应用设置-帮助）。Read more about the SaltPlayer help content (app Settings - Help).

反馈时候请注意：When giving feedback, please note:
-------------------------
- 尽量详细的描述。Be as detailed as possible.
- 不接收任何 UI 样式调整相关的反馈，出现此类 issue 会被关闭（如 “我不喜欢此设计” 、“我觉得这样设计更好” 、“还没原来好看” 等等类似反馈）。Do not receive any feedback on UI style changes, and the issue will be closed (" I don't like this design ", "I think this design is better", "it's not as good as the original", etc.).

#### 建议内容 The proposals

<在此输入你的建议 Enter your suggestions here

本人非常喜欢这款音乐软件，手机手表都是用这个，但是手表上其他软件都可以通过改签名来改DPI以适配，但是这个好像是改不了，使用体验影响挺大的，所以能不能出应用内改DPI的功能，求求了😊

**Comment by Moriafly** [comment]
您好，软件内设置->无障碍->显示大小缩放，调整数值，看看是否符合需求
