### ISSUE TITLE
关于适配鸿蒙的方法（希望能够采取）

### ISSUE THREAD

**Issue by MicGan6** [Moriafly/SaltPlayerSource#982]
#### 建议内容 The proposals

希望在软件Release的时候增加新的包名 com.kugou.android.lite
用来适配华为的播控中心
虽然会与酷狗概念版冲突，但是能解决播控控制（HarmonyOS 4.2.0.138仍旧可用）

**Comment by MicGan6** [comment]
如果开发者不愿意的话也麻烦跟我说一声，谢谢！

**Comment by Moriafly** [comment]
会在近期尝试和华为联系，始终以添加进入白名单为目标，这样的替换包名方法并不长久也不适合

**Comment by MicGan6** [comment]
> 会在近期尝试和华为联系，始终以添加进入白名单为目标，这样的替换包名方法并不长久也不适合

希望能重新考虑一下这个方法，毕竟...沟通没消息啊
主要是没有播控中心用的太难受了（我这半年基本上用的非常难受），完全离不开播控中心QwQ，在线音乐软件又不喜欢
如果可以的话可以找一些不影响国内用户的包名替换（相对小众）
不行的话就还是算了......
