### ISSUE TITLE
ttml support for word-by-word lyrics/ syllable lyrics

### ISSUE THREAD

**Issue by touchieyou** [Moriafly/SaltPlayerSource#988]
Hi, I really liked the app that I shared it with friends and it certainly has features that other players don't have, it's great, but it doesn't have what is currently in trend, syllable lyrics/  word-by-word lyrics are the ones that are shown in Apple Music songs, please add support since I have all the lyrics in ttml format, that would be all, thank you very much.
![Screenshot_20241003-013458](https://github.com/user-attachments/assets/79dff648-d7a4-490f-b92f-b6b2cfac715c)
I add an example image, this is a useless player that does not work, it has too many lags, but I think that in your application you could do it 100 times better.

**Comment by Moriafly** [comment]
Salt Player does not plan to adapt to third-party lyric formats

**Comment by sujitFYI** [comment]
> this is a useless player

What's name of the format?
